### ISSUE TITLE
Examples of mia functions to OMA book

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#114]
There are many new functions in mia that are not included in [OMA](https://microbiome.github.io/OMA/).

Suggestion: let us systematically go through functions in mia, and open an issue for every functionality that should be demonstrated in mia vignette and/or OMA. Then from now on, let us aim to open such issues whenever new functionality is added.

OMA does not include all functionality, but all relevant functions should be demonstrated in mia vignette and/or OMA.

**Comment by antagomir** [comment]
Note that the mia homepage has a [list of exported functions](https://microbiome.github.io/mia/reference/index.html). This should help in the task. Then you can use grep or other word search methods on the Rmd files in OMA to check which of these are not included yet.

**Comment by FelixErnst** [comment]
Any news on this?

**Comment by antagomir** [comment]
I have a plan on how to do this but will take till Feb/March before it can be completed, unless there are some faster volunteers.

**Comment by antagomir** [comment]
@RiboRings is now completing this.
