### ISSUE TITLE
manipulating data with the tidyverse when working in mia

### ISSUE THREAD

**Issue by HenrikEckermann** [microbiome/mia#115]
Hi,

just as in `phyloseq`, in `mia` you can quickly and easily extract, `colData`, `assays` and `rowData`. However, to use `dplyr` functions to manipulate e.g. `colData`, such as join-functions, you will have to extract the data, convert it to a `data.frame` and then in another step add the rownames to a column. The latter step has to be done not only for joining but also because if you use `dplyr` functions on a `data.frame` the function will convert it to `tbl_df` and then by by default drop the rownames. The rownames are needed once you want to put it back into the `tse` object. 

When I worked with `phyloseq` I wrote short functions that in one step extract `sample_data` into `tbl_df` and also a function that would do the reverse. So a typical workflow would be:

```
# extract sample_data
df <- sd_to_df(pseq)
# manipulate df: typically join other metadata or create new vars etc…
df <- mutate(df, …) 
# update pseq object
sample_data(pseq) <- df_to_sd(df)
```

On the one hand, this functionality would be only useful for a group of people that works a lot with tidyverse functions. And any individual could easily write those functions for themselves. But on the other hand, this group is probably significant given that the `tidyverse` is coherent and offers a ton of functionality for data manipulation. Obviously that function would also automate the rownames to column thing and reverse. What do you think?

Maybe something like this:

```
colData_to_tbl <- function(
  x, 
  id_name = "sample_id", # the default here should be most common sample id naming convention
  add_rownames_to_column = TRUE
  ) {
    
    tb <- dplyr::as_tibble(
      colData(tse), 
      rownames = if (add_rownames_to_column) id_name else NULL
    )
    return(tb)
}

tbl_to_colData <- function(
  x, 
  id_name = "sample_id",
  id_is_rowname = FALSE
  ) {
    
    # check that there is either rownames or id_name is in data
    if (!id_is_rowname) {
      x <- tibble::column_to_rownames(x, id_name)
    } 
    
    x <- DataFrame(x)
    return(x)

}
```

The same could be done for any kind of data that you can extract from a tse object but I used it mostly for sample data.

**Comment by antagomir** [comment]
> "The rownames are needed once you want to put data.frame back into the `tse` object." 

I have the impression that the use of rownames in data.frames is generally discouraged these days. If `tse` object construction requires this feature, we may want to revise this choice. We can open up another issue on that question if it seems relevant. This would have implicatins for the rest of this discussion.

Otherwise, I think there are benefits in supporting `tidyverse` way but this should not exclude other ways to go around given tasks. If we can realize this by some helper functions, why not.

**Comment by microsud** [comment]
Hi both- there is a set of tools that bridge BioC objects with tidyverse 
https://stemangiola.github.io/tidySummarizedExperiment/
Something to inspect in detail.

**Comment by antagomir** [comment]
Good catch, thanks!

**Comment by FelixErnst** [comment]
> "The rownames are needed once you want to put data.frame back into the tse object."

Can you give an example including the error given?

**Comment by HenrikEckermann** [comment]
> > "The rownames are needed once you want to put data.frame back into the tse object."
> 
> Can you give an example including the error given?

I just tried it out. It does not lead to an error. However, it will delete the column names of the assays automatically, which makes samples unidentifiable. It might lead to an error further down the line in case we have functions that work with rownames of the colData or columnnames of the assays.

However, given what Sudarshan found, we maybe do not have to think about this anymore. From my side, we can close it for now. I would work with this tidySummarizedExperiment package. If I encounter issues there, I could still reopen this here...

Here is a reproducible example of the issues when not specifying rownames. But also I show how it would work with the functions shown above and finally the easiest way seems to be with tidySummarizedExperiment. 

```r
library(mia)
library(dplyr)
library(tibble)
data("GlobalPatterns")



tse <- GlobalPatterns
# these are the column names of the assay 
colnames(assay(tse))
# lets say we want to use dplyr functions, e.g. full_join to join new data 
# to our existing colData:

# make up some data that we want to add to existing colData
df <- tibble(
  X.SampleID = colData(tse)$X.SampleID,
  zbmi = rnorm(n = length(colData(tse)$X.SampleID))
)
# The following object will have the colData + the data in df. Note that 
# the rownames are dropped by any dplyr function by default:
colData_new <- colData(tse) %>% 
  as.data.frame() %>%
  full_join(df, by = "X.SampleID")
# After manipulating/joining, we we want to update the existing coldata:
colData(tse) <- DataFrame(colData_new) 
# once we do that (without manually adding back the rowdata), we delete the 
# columnnames of the assay, which might lead to issues down the line.
colnames(assay(tse))




# if we add the rownames back this problem does not appear:
tse <- GlobalPatterns
colData_new <- colData(tse) %>% 
  as.data.frame() %>%
  full_join(df, by = "X.SampleID") %>%
  column_to_rownames("X.SampleID")
colData(tse) <- DataFrame(colData_new) 
colnames(assay(tse))





# define the potential functions: 
colData_to_tbl <- function(
  x, 
  id_name = "sample_id", # the default here should be most common sample id naming convention
  add_rownames_to_column = TRUE
) {
  
  tb <- dplyr::as_tibble(
    colData(tse), 
    rownames = if (add_rownames_to_column) id_name else NULL
  )
  return(tb)
}

tbl_to_colData <- function(
  x, 
  id_name = "sample_id",
  id_is_rowname = FALSE
) {
  
  # check that there is either rownames or id_name is in data
  if (!id_is_rowname) {
    x <- tibble::column_to_rownames(x, id_name)
  } 
  
  x <- DataFrame(x)
  return(x)
  
}



# using the functions it would be a little easier:
tse <- GlobalPatterns
colData(tse) <- colData_to_tbl(tse) %>%
  full_join(df, by = "X.SampleID") %>%
  tbl_to_colData()
colnames(tse)



# however with the package that Sudarshan found we can do this:
devtools::install_github("stemangiola/tidySummarizedExperiment")
library(tidySummarizedExperiment)
tse <- tse %>% full_join(df, by = "X.SampleID")
# the only downside for now: this code runs pretty slow. 
```

**Comment by antagomir** [comment]
The last solution seems pretty neat and perhaps that could be added in the examples and/or OMA data manipulation section. Speedups may appear later.

The ability to easily merge data sets, keeping relevant row and col names is important and should not require sophisticated understanding and steps where these can be avoided.

**Comment by FelixErnst** [comment]
Thanks for the example. I would be picky (sorry for that) and rephrase the sentence "The rownames are needed once you want to put data.frame back into the tse object" to this:

> I have no way of checking if the data is in the correct order, since the rownames are gone.

Since this is the issue, I would go with the `tidySummarizedExperiment` package for now and keep pestering Stefano with issues and requests, if you need additional functions and have suggestions for improving the package

**Comment by FelixErnst** [comment]
But just for clarification: `tidySummarizedExperiment` shouldn't end up in the Imports or Depends, since this blow the footprint out of proportion.
