### ISSUE TITLE
conversion function naming

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#117]
There are now functions `makeTreeSummarizedExperimentFromphyloseq` and `makePhyloseqFromTreeSummarizedExperiment` and capitalization of phyloseq is not uniform in these two. I suggest to unify. But not sure which way (phyloseq or Phyloseq). There are pros and cons. Any preferences?

**Comment by TuomasBorman** [comment]
I vote for Phyloseq because `phyloseq` stands out better, and this follows better the overall naming scheme

**Comment by TuomasBorman** [comment]
Closed via https://github.com/microbiome/mia/pull/119 and https://github.com/microbiome/OMA/pull/54
