### ISSUE TITLE
Naming and subsetting in agglomerations (and elsewhere?)

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#120]
The naming in the output of `agglomerateByRank` is not necessarily as consistent as it could be.

Problem: the examples below show differences in `rownames()` for agglomerated `TreeSE` objects, and the name format varies by agglomeration arguments. This is important because rownames can be used subsetting, for instance by using functions such as `getPrevalentTaxa` (see below). Such operations run smoothly only when the same naming formats are being used.

Possible solution: in some cases, it is difficult/impossible to avoid adding the rank name (like "Genus::Dialister"); should we consider providing rownames always in this format? In addition, there could be a wrapper that allows an easy incorporation of shorter name formats as additional columns in `rowData`. Another option is to keep everything "as is" and trust that the user can clean up names whenever needed. But this will cause extra overheads for many users.

```
library(mia)
data(GlobalPatterns)

tseA <- agglomerateByRank(GlobalPatterns, rank="Genus")
print(rownames(tseA[1:3,]))

```
[1] "Class:Thermoprotei" "Genus:Sulfolobus"   "Class:Sd-NA"  

```
tseB <- agglomerateByRank(GlobalPatterns, rank="Genus", na.rm=TRUE)
print(rownames(tseB[1:3,]))

```
[1] "Sulfolobus"     "Cenarchaeum"    "Nitrosopumilus"

```
tseC <- agglomerateByRank(GlobalPatterns, rank="Genus", agglomerateTree=TRUE)
print(rownames(tseC[1:3,]))

```
[1] "Class:Thermoprotei" "Genus:Sulfolobus"   "Class:Sd-NA"

For instance, getPrevalentTaxa returns the names in the following format and one motivation has been that this could then be used for easy subsetting.

```
  prevalent <- getPrevalentTaxa(tse,                  
                                   rank = "Phylum",
                                   detection = 10,
                                   prevalence = 50/100,
                                   as_relative = FALSE)
     head(prevalent)

```  
[1] "Crenarchaeota"  "Euryarchaeota"  "Actinobacteria" "Spirochaetes"  
[5] "Proteobacteria" "Fusobacteria"

**Comment by TuomasBorman** [comment]
I think shorter names are cleaner. Currently, longer names are used only when it's necessary, i.e., when taxon does not have name in that rank.

We already have function called `subsetByPrevalentTaxa` that does the subsetting. Is that enough?

However, for consistency, I think it could be beneficial to have agglomerated `rownames` always in "Genus:Sulfolobus" format

**Comment by antagomir** [comment]
I agree that shorter names would be nicer but longer might be necessary for consistency. 

It could (?) be an optional argument to provide short names but I am not sure if we like to provide that since removing the prefix is a one-liner.

The `subsetByPrevalentTaxa` is not necessarily sufficient in all cases.

**Comment by TuomasBorman** [comment]
Yep, this should do it

`rownames(x) %>% stringr::str_remove(paste0(c(stringr::str_to_title(TAXONOMY_RANKS), ""), collapse = ":|"))`

it might be too much for this small task, because there are lots of examples about removing patterns from strings

**Comment by FelixErnst** [comment]
Hmm,

It think this is not solved with a additional argument and a requirement via stringr to work on a character vector.

This would have been the easiest solution:

```r
> tseB <- agglomerateByRank(GlobalPatterns, rank="Genus", na.rm=TRUE)
> rownames(tseB) <- getTaxonomyLabels(tseB, with_rank = TRUE)
> print(rownames(tseB[1:3,]))
[1] "Genus:Sulfolobus"     "Genus:Cenarchaeum"    "Genus:Nitrosopumilus"
```

IMO this is a non issue. Do you agree?

MAybe this need some clarification on the man pages?

**Comment by antagomir** [comment]
Good point, ok to me to do like this. 

A clarification and example at the manpage of `agglomerateByRank` would help to clarify. 

And in the related section discussing `agglomerateByRank` in OMA.
