### ISSUE TITLE
ALR and ILR transformations

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#128]
We should consider adding ALR and ILR transformations in mia.

It is possible but [under discussion](https://github.com/vegandevs/vegan/issues/433) that some of the log-ratio transformations may soon be added to **vegan**. Good to wait and see for that outcome before implementing ALR and/or ILR. 

The ILR requires a reference sample and will result in a transformed data that has n-1 samples. It has certain statistical advantages over CLR and is therefore sometimes used. Related to [phILR transformation in issue #103 that returns d-1 features.

**Comment by FelixErnst** [comment]
See my answer there. If a reference feature/samples is used a row/column of zeros or NAs would allow storing the data as assays. The `altExp` alternative is less appealing but might a good option nonetheless.

There is however an additional alternative: dropping the reference samples from the `TSE` and just storing the output as an assay. 

The options best suited depends IMO largely on how much orchestration can/needs to be done with the result. If the transformation is just the second to last step, storing the data is not really efficient, if the calculation is fast and the data cannot be used in more than one subsequent step.

**Comment by FelixErnst** [comment]
Any news on this?

**Comment by antagomir** [comment]
Pending on [vegan #433](https://github.com/vegandevs/vegan/issues/433)

**Comment by antagomir** [comment]
I have concluded that ILR & ALR are not critical at this point, can be added later if necessary.
