### ISSUE TITLE
Import functions need to be fixed because of SE bugfix

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/mia#132]
Hi,

bugfix of `SummarizedExperiment` https://github.com/Bioconductor/SummarizedExperiment/commit/1e1da5b79a035a0f597dedcba42d2cec7a2406c3

Before, `SE` constructor just replaced assay's colnames with coldatas rownames, assay's rownames with rowdata's rownames. But it did not order the data accordingly. Now, **`SE` constructor requires that sample and feature names are in same order as they are in rowdata and coldata.** 

Because of this, we probably need to fix some of our functions. For example,  `loadFromQIIME2` takes only file paths as an input, and user does not have possibility to adjust the order of names in assay, colData, and rowData. 

Should we include a functionality that orders the columns of assay based on coldata's rownames, and rows of assay based on rowdata's rownames?

-Tuomas

**Comment by antagomir** [comment]
So in fact we cannot avoid doing some kind of ordering like this, to use the updated `SE`?

I would implement it as a function argument that indicates how to do to sorting: based on row/colData, or based on assay order, or even custom order could be allowed (user would input a vector of names). The user can then choose. Good default should be chosen.

**Comment by FelixErnst** [comment]
See **https://master.bioconductor.org/checkResults/3.14/bioc-LATEST/mia/nebbiolo2-checksrc.html**

@yiluheihei Can you fix this?

**Comment by yiluheihei** [comment]
@FelixErnst 👌 I will fix it whenever I have time.

**Comment by FelixErnst** [comment]
This is a bit time sensitive. Should some else prepare a fix?

**Comment by yiluheihei** [comment]
Thanks @hpages  for the commit [fb55ce1](https://github.com/microbiome/mia/commit/fb55ce187cc8651ec5ab06bbaa3bafb42e4d8dcb).

**Comment by antagomir** [comment]
Discussion still ongoing in #133

**Comment by TuomasBorman** [comment]
I think we should discuss about these import functions also. There could be that inputs have order mismatch between samples / taxa

I think these are working:

`makeTreeSummarizedExperimentFromPhyloseq` (phyloseq orders names)
`makeSummarizedExperimentFromBiom` (object shares colnames and rownames)
`makeTreeSummarizedExperimentFromDADA2` (doesn't include `rowData` or `colData`)

But I'm not sure about `loadFromMothur `
I think there can be a chance that input files are in different order, so should there be a check and aligning like `loadFromQIIME2` has now?

**Comment by antagomir** [comment]
Should be checked.
