### ISSUE TITLE
agglomerateByRank: agglomerated z-transformed assay lead to meaningless values

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/mia#136]
Hi,

I found a feature from `agglomerateByRank` that might be misleading. 

`agglomerateByRank` sums values. It does it for every assay. For example, `counts` or `relabundance` do not cause any problems. 

However, some other transformations like `Z-transform` lead to meaningless values when it is agglomerated. If user does not check this or if user is not aware of this, this can lead to errors. (In some transformations it might be hard to tell...)

```
> tse <- transformFeatures(tse, method = "z", pseudocount = 1)
> head(apply(assay(tse, "z"), 1, mean))
       549322        522457           951        244423        586076        246140 
-1.918412e-17 -1.705533e-17 -4.270214e-16 -1.704699e-17 -6.831933e-17  1.366658e-16 
> head(apply(assay(tse, "z"), 1, sd))
549322 522457    951 244423 586076 246140 
     1      1      1      1      1      1 
> tse1 <- agglomerateByRank(tse, "Genus")
> head(apply(assay(tse1, "z"), 1, mean))
   Class:Thermoprotei      Genus:Sulfolobus           Class:Sd-NA           Order:NRP-J        Family:SAGMA-X Family:Cenarchaeaceae 
        -1.274355e-17         -4.270214e-16          1.025697e-16         -5.124773e-16         -3.927856e-16         -3.608225e-16 
> head(apply(assay(tse1, "z"), 1, sd))
   Class:Thermoprotei      Genus:Sulfolobus           Class:Sd-NA           Order:NRP-J        Family:SAGMA-X Family:Cenarchaeaceae 
             1.963880              1.000000              2.835166              3.640426              2.964775              8.371031 
```

Should there be an argument that specifies, which assays are added to new agglomerated `TreeSE`? 
By default, `abund_values = c("counts")`

-Tuomas

**Comment by antagomir** [comment]
Agreed. Only "counts" by default. Rest has to be explicitly specified by the user (either by adding to abund_values list, or by operating the new agglomerated object), including relabundance for the agglomerated data. This can help to avoid mistakes and confusion.

**Comment by FelixErnst** [comment]
I don't think this is worth doing. You will never catch all mistakes a user can make with this function. I wouldn't try to do it because it will make a complex function even more complex. In addition, the assay name doesn't mean anything and since we don'Tt force assay names for certain types of data, the user must make sure to analyze the data correctly.

However, is there a test which can tell, if summing is applicable? Like test for negative values or binary values? A warning might do the trick with additional clarification in the examples

**Comment by FelixErnst** [comment]
Also the rule is always to agglomerate before transformation. I mean this is common sense, isn't it?

**Comment by antagomir** [comment]
Perhaps indeed a test and warning for suspicious cases would be a better way of doing this.

I have learned to be careful in trusting common sense, it is good if can help to avoid common accidental mistakes but yes this has to be balanced with other design considerations.

**Comment by TuomasBorman** [comment]
That might be better way to approach this
