### ISSUE TITLE
Replace S4vectors:::make_zero_col_DataFrame internal call

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#139]
This causes a note in `devtools::check()` and could be easily rewritten with exported material.

N  checking dependencies in R code (6.1s)
   Unexported object imported by a ':::' call: ‘S4Vectors:::make_zero_col_DataFrame’
     See the note in ?`:::` about the use of this operator.

**Comment by FelixErnst** [comment]
You can ignore this. This is something like a `Are you really sure?` kind of thing. We are, now way to avoid it and thats fine for everyone.

**Comment by antagomir** [comment]
Fine. Just love the screen empty of NOTEs :-)
