### ISSUE TITLE
sparseMatrix breaks meltAssay

### ISSUE THREAD

**Issue by nr0cinu** [microbiome/mia#151]
Hi :)

SummarizedExperiment objects are allowed to contain sparseMatrix objects instead of base matrix objects in their assays, which is of course very useful for spare amplicon data. However, this breaks meltAssay (and maybe other functions?):

```
library(Matrix)
library(mia)

data(GlobalPatterns, package = "mia")
meltAssay(GlobalPatterns)
# works

assay(GlobalPatterns) <- as(assay(GlobalPatterns), "sparseMatrix")
meltAssay(GlobalPatterns)
# Error in as.data.frame.default(x[[i]], optional = TRUE) :
#    cannot coerce class ‘structure("dgCMatrix", package = "Matrix")’ to a data.frame
```

Thank you!

Best,
Bela

**Comment by antagomir** [comment]
Good catch! 

I am just wondering if this should rather be an issue in the [SummarizedExperiment](https://github.com/Bioconductor/SummarizedExperiment/issues) itself?

**Comment by FelixErnst** [comment]
Hi,

the problem is, that `Matrix` objects don't have conversion functions towards `data.frame`.

```r
> as.data.frame(as(assay(GlobalPatterns), "sparseMatrix"))
Error in as.data.frame.default(as(assay(GlobalPatterns), "sparseMatrix")) : 
  cannot coerce class ‘structure("dgCMatrix", package = "Matrix")’ to a data.frame
```

Since the conversion to matrix is available, we are now doing that first.

**Comment by antagomir** [comment]
Great. Seems to be fixed now.

**Comment by nr0cinu** [comment]
Thank you :)
