### ISSUE TITLE
mergeCols breaks meltAssay

### ISSUE THREAD

**Issue by nr0cinu** [microbiome/mia#154]
Hi,

after using mergeCols, the meltAssay function fails:

```
data(GlobalPatterns)
GlobalPatterns
merged <- mergeCols(GlobalPatterns,colData(GlobalPatterns)$SampleType)
merged

meltAssay(GlobalPatterns)
# works
meltAssay(merged)
# Error in as.vector(x) : no method for coercing this S4 class to a vector
```

Thanks!

**Comment by nr0cinu** [comment]
Seems the assay `counts` contains another STE object instead of an assay object

```
assay(merged)
# class: SummarizedExperiment 
# ...
assay(merged) <- assay(assay(merged))
assay(merged)
meltAssay(merged)
# now it works
```

**Comment by TuomasBorman** [comment]
Hi!

Thanks again! 

It seems that the functionality of function that `mergeCols` is using was changed. `mergeCols` is calling `scuttle::sumCountsAcrossCells`. Instead of matrices (assays) it was returning `SE` objects. Now matrices are extracted from those `SE` objects.

-Tuomas
