### ISSUE TITLE
Feature request: getTopTaxa - percent detected

### ISSUE THREAD

**Issue by FelixErnst** [microbiome/mia#16]
Hi Sudarshan @microsud ,

can you add another option to `getTopTaxa`, which looks for percent detected across samples?

this should be defined probably like this
```
detected <- rowSums(assay(x, abund_values) > 0) / ncol(x)
```

With this function the taxa, which are present in most of the samples, can be access independent of  whether they show a high or low abundance.

Felix

**Comment by antagomir** [comment]
Perhaps good to note that this is also and already provided by the function `getPrevalentTaxa` when using a zero abundance threshold. If this feature is supported in getTopTaxa as well, you could cross-link with the @ seealso tag in royxgen

**Comment by FelixErnst** [comment]
Ah dang I missed that overlap. Maybe catch this case and call `getPrevalentTaxa`. I will have a look at the PR #15  in the afternoon.

**Comment by antagomir** [comment]
yes perhaps that would be the clearest solution.

**Comment by FelixErnst** [comment]
done 9e66539
