### ISSUE TITLE
getUniqueTaxa: return sorted?

### ISSUE THREAD

**Issue by nr0cinu** [microbiome/mia#163]
Hi :)

Wouldn't it be convenient to sort the return value of getUniqueTaxa()? I see no advantage of keeping it unsorted? sort() would also remove the NA that can happen, which would be good too maybe?

https://github.com/microbiome/mia/blob/4a09bbed14c283dbcccf09ea21893c1c8f933f22/R/summaries.R#L135

Thanks!
Bela

**Comment by TuomasBorman** [comment]
Hi,

thanks for your suggestion! I agree that sorting might be nice to have. Also, NA is not very informative, and it cannot be used to subset.

We could add there `sort = TRUE` parameter, so user can choose if return value will be sorted. In addition to that, we could add there a line that removes all the NAs. 

There are also other functions (e.g. `getTopTaxa`) that have this same issue. What do you think @antagomir @FelixErnst?

-Tuomas

**Comment by antagomir** [comment]
Fine with me.

Sorting could happen in different ways, though: abundance, alphabetic, rank.. should the input argument consider these different optons?

**Comment by TuomasBorman** [comment]
I was thinking just alphabetical order. Those others are possible, but they would need more work. For example, getUniqueTaxa is just a wrapper for `unique( rowData(tse)[[rank]] )` 

I'm not sure if that goes too complicated

**Comment by microsud** [comment]
Thanks! I agree. I would avoid sorting on abundance/prevalence as not required for this function. There is getTopTaxa

**Comment by FelixErnst** [comment]
IMO unneccessary.

`sort(getUniqueTaxa())` works fine, doesn't it? And it is less writing, than adding `sort = TRUE`

**Comment by FelixErnst** [comment]
But since Tuomas hid the option in the dots, it is fine for me. Removing the `NA` by default is I think not a good idea, since a selected rank migh derive meaning from a `NA` value e.g. "The one bacteria which we cannot assign information on that rank is unique"

**Comment by TuomasBorman** [comment]
That's true, I added there na.rm to select whether to remove missing values or not

**Comment by nr0cinu** [comment]
Awesome! :) Maybe sort could be TRUE by default?

**Comment by TuomasBorman** [comment]
Hmmm, that would make things easier, if user wants to get taxa in alphabetical order. 

However, it is usually better to not do too much stuff that user is not expecting to happen. Especially, when this is some kind of extra functionality 

Because of that, I suggest that `sort = FALSE` by default

**Comment by antagomir** [comment]
Right - yes I agree for alphabetic sorting being enough for `getUniqueTaxa` but for `getTopTaxa` we might need other sortings because alphabetic may be misleading. However this is not necessarily too critical for now, if it would be lot of additional work

**Comment by TuomasBorman** [comment]
`getTopTaxa` returns currently taxa in "top score" order. I think alphabetical order is also nice option for this, if user wants for example top 50 taxa

**Comment by nr0cinu** [comment]
I personally expected getUniqueTaxa to return alphabetic sorting. Other things in R, like level from as.factor or ggplot2 also always default to alphabetic sorting after all, independent of the order or the underlying data.

getTopTaxa should stay ordered by abundance as it is now imho.

Obviously all options are fine in the end, if we have the parameter to change the behavior. Thanks! :)

**Comment by antagomir** [comment]
agreed with all

**Comment by TuomasBorman** [comment]
Ok, now sorting is also implemented. Another bigger reason for `sort = FALSE` by default is that we have wrapped this in internal function, because now this option can be hidden. This internal function is called from both `getUniqueTaxa` and `getTopTaxa`. 

Because there can be only one default value in this kind of implementation, it had to be `FALSE`, so that taxa are not sorted in alphabetical order in `getTopTaxa` by default. (We could have implemented two internal function but that would not be convenient.)

To get suggested return value, use
`getUniqueTaxa(tse, sort = TRUE, na.rm = TRUE)`

Thanks Bela for your suggestions, these are very valuable!

-Tuomas

**Comment by nr0cinu** [comment]
Awesome! And happy to help!
