### ISSUE TITLE
calculateUniFrac bugfix

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/mia#166]
Hi,

`calculateUniFrac` has currently two input options

- `signature = c(x = "ANY", tree = "phylo")`
- `signature = c(x = "TreeSummarizedExperiment", tree = "missing")`

This `ANY + phylo` causes problems. 

```
data(esophagus)
calculateUniFrac(esophagus, rowTree(esophagus))
 Error in t.default(x) : argument is not a matrix 
```

Because this `ANY + phylo` calls `.calculate_distance`, I think that `x` should be an `assay matrix`. 

1. **--> should the signature be changed to `signature = c(x = "matrix", tree = "phylo")`?**

2. **However, then I think that we should include a test that checks that the assay and tree matches**

```
calculateUniFrac((assay(esophagus)), rowTree(esophagus), weighted = FALSE)
 Error in (function (x, tree, weighted = FALSE, normalized = TRUE, BPPARAM = SerialParam())  : 
  Incompatible tree and abundance table! 
```

```
calculateUniFrac(t(assay(esophagus)), rowTree(esophagus), weighted = FALSE)
          B         C
C 0.5175550          
D 0.5182284 0.5422394
```

3. **OR should there be just signature `signature = c(x = "TreeSummarizedExperiment")`?** 

I'm not sure what is the purpose of `signature = c(x = "ANY", tree = "phylo")`, because the tree should be in `rowTree(x)/colTree(x)`. That `signature = c(x = "ANY", tree = "phylo")` could be converted to internal function.

-Tuomas

**Comment by antagomir** [comment]
Supporting just TreeSE, and dropping support for the any+phylo option might help to encourage the use of that standardized TreeSE container. I am not sure what is gained by supporting any+phylo.

If the any+phylo is kept anyway, then it would be indeed good to specify it as a matrix and/or phyloseq object. Or if there are further formats supported by Unifrac functions, then one could just refer to Unifrac function documentations, and perhaps check internally that the input ("any") is of correct type.

The name of this function should be Unifrac, not UniFrac

**Comment by TuomasBorman** [comment]
Maybe it is best to change `signature = c(x = "ANY", tree = "phylo")` --> `signature = c(x = "matrix", tree = "phylo")`

That is because the function seems to be used in other functions like this:

```
#' esophagus <- runMDS(esophagus, FUN = calculateUniFrac, name = "UniFrac",
#'                     tree = rowTree(esophagus),
#'                     exprs_values = "counts",
#'                     ntop = nrow(esophagus))
```

**Comment by antagomir** [comment]
Sounds fine to me.

**Comment by FelixErnst** [comment]
The ANY dispatch is the catch all, since by design the input must be matrix-like, nothing else. It is also designed that way to be compatible to other `calculate*` functions, e.g. `calculateMDS` and some other functions from `scater`

What is wrong IMO:
1. The error message is not verbose enough for people not reading the man page

Thats it. Nothing more to it. So how do you want proceed? Reinvent the wheel by removing ANY + phlyo?

Apart from that decision, I think the issue description lacks some critical details. The error message is actually thrown in the `runUniFrac` function.

**Comment by TuomasBorman** [comment]
¨So, I think that we could add input check to runUniFrac:

```
if( !is.matrix(as.matrix(x)) ){
    stop("'x' must be a matrix.")
}
```
Everything that can be converted into matrix (==matrix-like) is ok

**Comment by FelixErnst** [comment]
This will remove the support for `DelayedMatrix` and similar objects, which is acutally the reason for the `ANY` dispatch in `calculate*` functions

**Comment by antagomir** [comment]
Fair points and I agree with this entirely. Thanks for clarification.
