### ISSUE TITLE
Improve loadFromQIIME2

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/mia#169]
Hi,

user might have sometimes files in different formats. For example, `loadFromQIIME2` supports only qza format (sample meta in tsv). 

In this case, if user has everything but assay in qza format, he/she cannot import files with our methods, because `.read_qza` is just an internal function. (assay is always needed in importing)

I think we have two options:
1. We can export `.read_qza` (`readQZA`) so that user can import individual files and then create `SE` from them.
2. Allow other file types (csv and tsv) also. I think in this case we need to make a presumption that first column includes rownames, because the format of the file can be anything.

Option 1 is might be the bets in my opinion

-Tuomas

**Comment by antagomir** [comment]
I think we could start with option 1. Point 2 and more could be developed later, if it would seem to make life easier.
