### ISSUE TITLE
estimateDiversity wrapper

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#17]
The `estimateDiversity` functionality has one method per index (estimateShannon, estimateSimpson etc.) but I do not find a generic wrapper that could return a chosen index, like `estimateDiversity(x, index = "Shannon")`. If such wrapper does not exist it would be highly useful. Ping @tvborm

**Comment by FelixErnst** [comment]
The data is saved in the `colData()` of x. As per the examples in `?estimateDiversity`, this should work like this

```
x<- estimateShannon(x)
colData(x)$Shannon
```

The benefit of saving it directly in the `colData()` is, that if the samples are subset using `x[,the_intersting_ones]` and eternal vector doesn't need to be subset as well. All data is kept aligned to the available samples minimizing code redundancies and increasing readability of code.

Did this solve the issue?

**Comment by antagomir** [comment]
We could have both with

```
x<- estimateDiversity(x, index = "Shannon")
colData(x)$Shannon

```

This would seem simpler to me from user perspective.

**Comment by FelixErnst** [comment]
This already available via the `name` argument

```
x <- estimateDiversity(x, name = "something")
colData(x)$something
```

edit: a Sorry. you mean a wrapper. Will add it

**Comment by antagomir** [comment]
Should this work:

```
library(mia)
data(esophagus)
x <- esophagus
estimateShannon(x, abund_values = "counts", name = "Shannon")
```

I get: 
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘estimateShannon’ for signature ‘"TreeSummarizedExperiment"’

**Comment by FelixErnst** [comment]
All the issues should be fixed by e81462e  

Please note that the estimates are now saved in `colData` in all lower caps by default.

edit:
```
data(esophagus)
x <- esophagus
x <- estimateShannon(x)
colData(x)$shannon
x <- estimateShannon(x, name = "Shannon")
colData(x)$Shannon
```

**Comment by antagomir** [comment]
Perfect and works.

One more thing. It is potentially confusing that different casing (lower/upper) is being used in function arguments and outputs, although the indices are otherwise the same. 

My suggestion is to use full lowercase for all, this would be simplest from user perspective and I do not see added value for this difference from developer perspective either (?)

**Comment by FelixErnst** [comment]
With the changes introduced in e81462e arguments and output are lower case by default. See my examples above

**Comment by FelixErnst** [comment]
Additional changes: With aaedf29 `estimateDiversity` will calculate all available diversity measure from a single call by default.

**Comment by FelixErnst** [comment]
Additional changes: With 3978bbf estimateDiversity man page includes plotting examples

can we close this?

**Comment by antagomir** [comment]
Yes, thanks.
