### ISSUE TITLE
Metaphlan3 results loading

### ISSUE THREAD

**Issue by asierFernandezP** [microbiome/mia#170]
Hi,

I have built a Summarized Experiment from Metaphlan3 results. However, I have not seen any previous example of this so I would like to know if the approach used is correct or would you recommend a different strategy to load this metagenomic results and work with them with Mia package:

```
library(dplyr)
library(tidyr)
library("TreeSummarizedExperiment")
library("mia")
library("miaViz")
library("SingleCellExperiment")

# Select rows from metaphlan3 that reach species level (based on the taxonomy/data that AsnicarF provides in "CuratedMetagenomicData" package to create a TSE: he provides only taxa at species level with relative abundances recalculated on this new table so that each sample has a total abundance of 100 (each sample = 100) E.g: a<-tse$`2021-10-14.AsnicarF_2017.relative_abundance`@assays@data$relative_abundance)
filteredM3 <- Metaphlan3[grepl("s__", Metaphlan3$clade_name),]

# Create the taxonomy table
Tax_table <- separate(data = filteredM3, col = clade_name, into = c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species"), sep = "\\|")
Tax_table <- Tax_table[,1:7]
Tax_table<- as.matrix(Tax_table)

# Create the counts table
counts_table <- select(filteredM3, -c("clade_name"))
counts_table <- as.matrix(counts_table)

# Check total abundance in each sample
apply(counts_table, 2, sum)
# Generate new relative abundances by dividing each value by sample
counts_table_rel_ab <- decostand(counts_table, MARGIN = 2, method = "total")

counts  <- counts_table_rel_ab   # Abundance table (e.g. ASV data; to assay data)
tax     <- Tax_table    # Taxonomy table (to rowData)
samples <- metadata # Sample data (to colData)

se <- SummarizedExperiment(assays = list(counts = counts),
                                     rowData = tax,
                                     colData = samples)
                                     #rowTree = row_tree,
                                     #rowNodeLab = row_lab,
                                     #colTree = col_tree)

```

Thank you,

Asier

**Comment by TuomasBorman** [comment]
Hi,

Thanks. 

This is my first time seeing this format. Every step can be easily justified, so I think it looks good.

Do you @antagomir @FelixErnst know more about this? Is there a room for us to create an import function for this?

https://github.com/biobakery/biobakery/wiki/metaphlan3
https://raw.githubusercontent.com/biobakery/biobakery/master/demos/biobakery_demos/data/metaphlan3/output/merged_abundance_table.txt

-Tuomas

**Comment by FelixErnst** [comment]
You can give it a go. However, the tricky bit is the input sanity checks. You have to make sure, the format is recognized and sanitized correctly (version, variants, etc) so that the actual importer can be as streamlined as in the example.

**Comment by antagomir** [comment]
Metaphlan3 outputs are quite common, support would be well justified, if the importer can be sufficiently standardized. This can also support users who have less experience with these formats and who may have a higher threshold of getting started.

The **mia** package has its own functions for relative abundance calculation; I would suggest creating `SE` from the actual count data and then use standard tools `relabundance` / `transformCounts` / `transformSamples` to add relative abundance assay. But yes, this is possible to do either way

**Comment by asierFernandezP** [comment]
Thank you for your answers. Yes, the problem is that Metaphlan does not give you real "absolute counts", so we always work with relative counts. What I did here was to remove the unclassified portion in the result table from Metaphlan and recalculate the relative abundances again with ```relabundance```.

**Comment by antagomir** [comment]
Right, no absolute counts in a sense; but non-relative count data (not sure how that should be called actually).

In the above code the relative abundances are calculated with 
`counts_table_rel_ab <- decostand(counts_table, MARGIN = 2, method = "total")`
and not with `SE` tools, like `mia::transformSamples` - and did not see `relabundance` there, just pointed out in case.

**Comment by asierFernandezP** [comment]
Yes, you are right! Thank you for pointing it out! I guess in this case the results would be similar (just making each sample to have a total relative abundance of 1), but maybe it is easier to work with ```SE``` tools.

**Comment by antagomir** [comment]
yes.

**Comment by FelixErnst** [comment]
Can I close the issue?
