### ISSUE TITLE
function to remove empty rows/cols?

### ISSUE THREAD

**Issue by nr0cinu** [microbiome/mia#173]
Hi!

during subsetting it can happen that the row/colSums of some cols/rows end up being zero. For example, if some samples are removed, it could happen that ASVs only in those samples are now zero in subsetted dataset. Presumably, TreeSummarizedExperiment subsetting on purpose doesn't trim these zeros out, however with amplicons I don't think it ever makes sense to keep those?

So maybe a helper function to trim the tse object would be helpful?

Thanks!
Best,
Bela

PS: something like that:

```
trim_empty <- function(x, ...) {
  rs <- rowSums(assay(x, ...))
  cs <- colSums(assay(x, ...))

  if(any(rs == 0)) {
    remove <- names(rs[rs == 0])
    x <- x[!rownames(x) %in% remove, ]
    message("Removed ", length(remove), " rows.")
  }

  if(any(cs == 0)) {
    remove <- names(cs[cs == 0])
    x <- x[, !colnames(x) %in% remove]
    message("Removed ", length(remove), " columns.")
  }

  x
}
```

**Comment by antagomir** [comment]
Perhaps we could have trim option as an argument in the subsetting functions? Default FALSE.

**Comment by TuomasBorman** [comment]
The problem is that `subsetSamples` and `subsetFeatures` will be removed, because `[]` is preferred

We could probably add it on top of the `[]` function, but I'm not sure if that is wise

**Comment by antagomir** [comment]
Right.. I think `[]` and general solution is preferred indeed.. perhaps some examples could also include and show how to solve this kind of situations, if nothing else-

**Comment by TuomasBorman** [comment]
I think that we do not have suitable function for adding this functionality, and creating own function just for this is more or less like shooting flies with shotgun

This might be useful, so we could add example here https://microbiome.github.io/OMA/datamanipulation.html#subsetting

**Comment by FelixErnst** [comment]
I agree.

Something like this should do the trick as well:
```r
tse[ rowSums(assay(x, ...)) == 0,  colSums(assay(x, ...)) == 0]
```

I don't think this one-liner is worth the implementation of a function.
