### ISSUE TITLE
mergeCols could/should return a sparseMatrix (if input is a sparseMatrix)

### ISSUE THREAD

**Issue by nr0cinu** [microbiome/mia#175]
Hi,

presumably, `sparseMatrix` is the preferred format for storing sparse count data (or it wouldn't exit?), so maybe mia functions like `mergeCols` should return these over base matrices? Always or only if the input is a `sparseMatrix`?

Best,
Bela

**Comment by antagomir** [comment]
I support this idea but good to see if there are other arguments.

**Comment by antagomir** [comment]
I like the idea but then started to think if it is problematic to return a different output vs. input.

Another solution would be to provide conversion option as a function argument.

**Comment by nr0cinu** [comment]
> I like the idea but then started to think if it is problematic to return a different output vs. input.

keeping input and output type the same is a good compromise too I think.

* matrix in, matrix out
* sparseMatrix in, sparseMatrix out

**Comment by FelixErnst** [comment]
Thats how it should be. Only change data types if necessary.

That way less code, less bugs, more expected result, ...
