### ISSUE TITLE
Ribosomal RNA operon copy number correction / rrnDB support

### ISSUE THREAD

**Issue by nr0cinu** [microbiome/mia#179]
Hi,

maybe it would be interesting/useful to add support for things like the [rrnDB](https://rrndb.umms.med.umich.edu/). This is often combined with using absolute abundance measures (see #4) to get estimated genome copy numbers instead of rRNA operon copy numbers, which is a better proxy for cell numbers than just the operon copies.

Possible helpers could be:
1) a function to (download and) match the rrnDB to the row data, at the best/highest/fixed taxonomic level
2) a function to calculate corrected copy numbers (probably in combination with #4) to get absolute genome copy numbers.

Best,
Bela

**Comment by antagomir** [comment]
Thanks! The procedure should be probably tested before deploying it into wider use. Hence, a Rmarkdown vignette (for instance in this or in OMA) might be a good start for the discussion on how to convert it into a R pkg tool. Contributions also very welcome.

**Comment by FelixErnst** [comment]
I think this has to implemented elsewhere, since `mia` can provided the tools for applying a correction, but interlinking with datasources is out of scope IMO.

Maybe and adjacent package would best.
