### ISSUE TITLE
taxonomyRanks update?

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#185]
**Problem**
The `taxonomyRanks` function does not consider "OTU" or "ASV" field as a taxonomic rank. This may be justified but it leads to a problem with `splitByRanks`. This function splits the abundance tables by the ranks listed by `taxonomyRanks`, and as a result the outcome from `splitByRanks` does not contain OTU/ASV table. In many cases the data analyst would like to have that as well. It is available through `assay(..., "counts")` but for automation purposes it would be quite handy to have access to OTU/ASV abundance table also through the `splitByRanks` output, so that operations can be run for all rank levels in a batch mode, and there is no need for a separate treatment of OTU/ASV table. See reproducible example below.

**Possible solutions**
1. Add OTU/ASV as an accepted taxonomic rank in `taxonomyRanks`. Potentially as an optional argument that would be actived in `splitByRanks`.
2. Modify `splitByRanks` so that it uses specified ranks, or `colnames(rowData(se))` by default instead of the outcome of `taxonomyRanks`

Solution 1 might help to avoid some confusion also in other context than just `splitByRanks` but there are pros and cons.

```
library(microbiomeDataSets)
mae <- HintikkaXOData()
tse <- mae[["microbiota"]]
```

`names(rowData(tse))`
[1] "Phylum"  "Class"   "Order"   "Family"  "Genus"   "Species" "OTU"    

`taxonomyRanks(tse)`
[1] "Phylum"  "Class"   "Order"   "Family"  "Genus"   "Species"

`names(splitByRanks(tse))`
[1] "Phylum"  "Class"   "Order"   "Family"  "Genus"   "Species"

**Comment by TuomasBorman** [comment]
I think we could add OTU and ASV to `taxonomyRanks` because in this context they are some kind of

**Comment by FelixErnst** [comment]
I don't think that is a good idea.

I would ask the question, why is the data not reported back? Is it not added or is it removed?

**Comment by antagomir** [comment]
I am not sure what the "why is the data not reported back" refers to?

But at least I often need to run analyses at multiple taxonomic levels, including ASV/OTU level. It is rather inconvenient for the analysis that one of the abundance tables requires a different treatment than others, although it is as much taxonomic features x samples matrix as the other ranks.

**Comment by FelixErnst** [comment]
Sure, I agree with that.

~But instead of diluting the meaning of taxonomyRanks, the question I am asking is, why is `splitByRanks` not returning the data as you would like it to do? I am not sure, because I cannot recite the code from memory.~

~Answering this question would allow a better fix to be implemented, a fix which would be a general fix and not a fix for a column, which is not a taxonomic rank, but rather for any additional column which might be present.~

**Comment by FelixErnst** [comment]
After looking into your example a bit more, I think this an non issue:

```r
> tse_otu <- mergeRows(tse, as.factor(rowData(tse)$OTU))
> tse_otu
class: SummarizedExperiment 
dim: 12706 40 
metadata(0):
assays(1): counts
rownames(12706): GAYR01026362.62.2014 CVJT01000011.50.2173 ... JRJTB:03787:02429 JRJTB:03787:02478
rowData names(7): Phylum Class ... Species OTU
colnames(40): C1 C2 ... C39 C40
colData names(0):
```

**Comment by FelixErnst** [comment]
After reading a bit more into your example, I think this is an non-issue:

First `mergeRows` will give you the result you need using any additional factor in `rowData`
```r
> tse_otu <- mergeRows(tse, as.factor(rowData(tse)$OTU))
> tse_otu
class: SummarizedExperiment 
dim: 12706 40 
metadata(0):
assays(1): counts
rownames(12706): GAYR01026362.62.2014 CVJT01000011.50.2173 ... JRJTB:03787:02429 JRJTB:03787:02478
rowData names(7): Phylum Class ... Species OTU
colnames(40): C1 C2 ... C39 C40
colData names(0):
```

Second, this doesn't make sense with the example data you have provided since there is nothing to be aggregated:
```r
> anyDuplicated(rowData(tse)$OTU)
[1] 0
```

**Comment by antagomir** [comment]
I am not sure if it was really intentional to leave out OTU/ASV level from `splitByRanks`. If it was, I am also curious to learn more about this.

Technically, the OTU/ASV level is left out because `rowData(se)` typically includes that most refined taxonomic level in `rownames`, rather than as an additional `rowData` field (see below). 

The OTU/ASV is not a scientifically characterized taxonomic entity/organism but it is a coherent taxonomic unit. By default it could be included as one of the taxonomic ranks and I think this would solve the issue. But then the `SE` constructor should take care of this. I am not sure if this is justified in all cases because indeed OTU/ASV interpretation is different compared to real biological ranks. 




> data("GlobalPatterns")
> rowData(GlobalPatterns)
DataFrame with 19216 rows and 7 columns
           Kingdom        Phylum        Class        Order        Family
       <character>   <character>  <character>  <character>   <character>
549322     Archaea Crenarchaeota Thermoprotei           NA            NA
522457     Archaea Crenarchaeota Thermoprotei           NA            NA
951        Archaea Crenarchaeota Thermoprotei Sulfolobales Sulfolobaceae
244423     Archaea Crenarchaeota        Sd-NA           NA            NA
586076     Archaea Crenarchaeota        Sd-NA           NA            NA
...            ...           ...          ...          ...           ...
278222    Bacteria           SR1           NA           NA            NA
463590    Bacteria           SR1           NA           NA            NA
535321    Bacteria           SR1           NA           NA            NA
200359    Bacteria           SR1           NA           NA            NA
271582    Bacteria           SR1           NA           NA            NA
             Genus                Species
       <character>            <character>
549322          NA                     NA
522457          NA                     NA
951     Sulfolobus Sulfolobusacidocalda..
244423          NA                     NA
586076          NA                     NA
...            ...                    ...
278222          NA                     NA
463590          NA                     NA
535321          NA                     NA
200359          NA                     NA
271582          NA                     NA

**Comment by FelixErnst** [comment]
>  indeed OTU/ASV interpretation is different compared to real biological ranks.

So there we have it. It is not standardized, it is not a real biological rank, even the name is not since sometimes it is called OTU and sometimes ASV.

So why would it make sense to complicate `taxonomyRanks` for something nobody can agree on?

Using `mergeRows` you can agreggate however you would like to. It is totally up to you, its is even a one-liner. I really don't see the issue

**Comment by antagomir** [comment]
Totally fine with not messing up `taxonomyRanks` with this but I do not yet see how `mergeRows` will solve the issue. Even after that, the `splitByRanks` does not return OTU/ASV table (i.e. the full count assay)  as one of the `altExp` assays. This means that the OTU/ASV level will require separate handling even in cases where it will be analysed in batch with the other levels. Many analyses are routinely done for both ASV as well as Species, Genus, Phylum etc levels. It would be well justified to remove bottlenecks from the data analysis. 

Could `splitByRanks` have an optional argument to include the full abundance table as one of the `altExp` assays?

**Comment by FelixErnst** [comment]
`splitByRanks` is a convenience function, which is really just that. The convenience comes from the fact that biological ranks are agreed upon and everybody can use it.

This little example get you what you want:

```r
> tse_split <- splitByRanks(tse)
> add_lvls <- c("OTU")
> add_split <- SimpleList(lapply(as.list(rowData(tse)[,add_lvls,drop=FALSE]), mergeRows, x = tse))
> tse_split <- c(tse_split, add_split)
> tse_split
List of length 7
names(7): Phylum Class Order Family Genus Species OTU
```

If you really really really think, that saving 2 lines of code is worth writting a function, than write a wrapper and call it `splitByAddRanks` or something., IMO writting 100 lines for man page, examples, the generic and the actual function to save two lines of code is really not worth it.

edit: It is even worse, since the user will never get his independence from some workflow, if he uses functions, which are only usable in that exact workflow. That example above teaches a user more, than explaining a `splitByAddRanks` functions in 100 lines on a man page a user will never read and only complain about on this GitHub section.

**Comment by antagomir** [comment]
From data analysis perspective these are just taxonomic units at different levels. The only exception is that OTU/ASV does not have the same biological interpretation than other ranks. 

But it does have the same technical interpretation as a matrix of taxonomic features vs. samples, and this is often what matters for a data analyst.

I reopen this for now because I in my own experience this would support practical data analysis well, and hence like to spend a moment on thinking and experiment more about this, and check if there are other comments meanwhile. Will aim to come back to this as soon as possible so that we could close the case.

**Comment by antagomir** [comment]
The above example gives an error to me. 

My interest is to just add the lowest level count table to the splitted list. This highest-resolution level (typically the OTU/ASV level) is routinely analysed together with the taxonomic ranks. Then the aggregation with `mergeRows` does not seem necessary(?).

```
library(mia)
data(GlobalPatterns)
tse <- GlobalPatterns
tse_split <- splitByRanks(tse)
tse_split <- c(tse_split, SimpleList(ASV=assay(tse, "counts")))
names(tse_split)
```

This is a one line operation (line 5) but an inconvenient extra step to add on a regular basis. There seems to be support for the idea that the user could choose to include the full assay among the listed abundance tables. 

If `taxonomyRanks` cannot be modified, how about an option to include the full abundance table (`assay(x, abund_values)`) in the output of `splitByRanks`? It could be FALSE by default.

**Comment by antagomir** [comment]
My interest is to just add the full feature table in the splitted list, as in the example below. 

```
library(mia)

# Example data
data(GlobalPatterns)
tse <- GlobalPatterns
tse_split <- splitByRanks(tse)

# Often the lowest level feature names are only at rownames
rowData(tse)$ASV <- factor(rownames(tse))

# Merge, to keep the tree as well
add_lvls <- "ASV"
add_split <- SimpleList(lapply(as.list(rowData(tse)[,add_lvls,drop=FALSE]), mergeRows, x = tse))

# Add ASV as a new level
tse_split <- c(tse_split, add_split)

# Check
tse_split
```

The highest-resolution level (OTU/ASV level in 16S studies) is routinely analysed together with taxonomy ranks. Because it is so common to run this level in batch together with other ranks, it would be an inconvenient extra step to add on a regular basis. There seems to be broader support as well for the idea that the user could choose to include the full assay among the listed abundance tables, and sometimes users might need even other groupings in the same way. 

If `taxonomyRanks` must respect the bio categories and cannot be modified, how about 

1) an option to include the full abundance table (`assay(x, abund_values)`) in the output of `splitByRanks`? It could be FALSE by default; or 
2) providing an analogous but more general function, `splitByLevels` which could be used to obtain the split for any groupings picked by the user from `rowData` fields (including but not limited to taxonomy ranks), with the option of including the full abundance table as one level.

**Comment by FelixErnst** [comment]
Form my point of view adding additional arguments is not helpful. This has been suggested on a lot of issues without taking one step back and looking at it from the point of havinga clear function names which can be intuitively used.

The solution is very simple. Implement a `splitBy` as Tuomas has done in #216. I will have a look at there.

**Comment by antagomir** [comment]
Yes perfect. Might be good to cross-reference these in @seealso field once the `splitBy` is ready.

**Comment by FelixErnst** [comment]
Here is some code simplification:

In your example you used this example 

```r
data(GlobalPatterns)
tse <- GlobalPatterns
# Often the lowest level feature names are only at rownames
rowData(tse)$ASV <- factor(rownames(tse)) # this doesn't work because the rownames are unqiue in the example data
rowData(tse)$ASV <- factor(rowData(tse)$Kingdom) # so let use Kingdrom for the example
# Merge, to keep the tree as well
add_lvls <- "ASV"
add_split <- SimpleList(lapply(as.list(rowData(tse)[,add_lvls,drop=FALSE]), mergeRows, x = tse))
```

The oneliner to replace it is:
```r
tse <- as(tse,"SingleCellExperiment") # required because split is broken for TSE
do.call(rbind,
        mapply(mergeRows, split(tse,rowData(tse)[,"Kingdom"]),
               split(rowData(tse)[,"Kingdom"],rowData(tse)[,"Kingdom"])))
```

@TuomasBorman can you post the bugreport? Thanks

**Comment by antagomir** [comment]
But the point was to add the full feature table as one of the elements in the new list. This is why something like `rowData(tse)$ASV <- factor(rownames(tse))` had to be done for the sake of the example. The point is, excactly, that the rownames are unique because we are willing to include the full abundance table and then this typically is the case. The corresponding onliner would be something like 

```
li <- do.call(rbind,
        mapply(mergeRows, split(tse,rownames(tse)),
        split(rownames(tse),rownames(tse))))
```

but this seems prohibitively slow.

**Comment by FelixErnst** [comment]
Depends on the rownames, doesn't it. They should be unique, so the example lacks some real world applicability.

You don't want a list with SEs, each one row long, don't you?

With the example given above `li` will be the same as `tse`. So I don't see the point. A better very very detailed example with real world example data is needed.

**Comment by antagomir** [comment]
The real world example, where we split by ranks and then add on top of that the full abundance table, which has the most high-resolution features that are available. Often we like to analyse this in batch with the higher level features. This is the same example as above.

```
library(mia)

# Example data
data(GlobalPatterns)
tse <- GlobalPatterns
tse_split <- splitByRanks(tse)

# Often the lowest level feature names are only at rownames
rowData(tse)$ASV <- factor(rownames(tse))

# Merge, to keep the tree as well
add_lvls <- "ASV"
add_split <- SimpleList(lapply(as.list(rowData(tse)[,add_lvls,drop=FALSE]), mergeRows, x = tse))

# Add ASV as a new level
tse_split <- c(tse_split, add_split)

# Check
tse_split


```

**Comment by FelixErnst** [comment]
This is running in circles.

You example is either incomplete or inaccurate in showing what you actually need since:

```r
all(assay(add_split[[1]]) == assay(tse)) == TRUE
```

your result is the same as:

```r
data(GlobalPatterns)
tse <- GlobalPatterns
tse_split <- splitByRanks(tse)
tse_split <- c(tse_split, list(tse))
```

For which operation do we need some new function?

As mentioned above:

>  A better very very detailed example with real world example data is needed.

Please provide it or close the issue. Thanks

**Comment by FelixErnst** [comment]
And if you want to combine the splitByRanks result with original heighest resolution, why not do something like this?

```r
data(GlobalPatterns)
tse <- GlobalPatterns
altExps(tse) <- splitByRanks(tse)
```

**Comment by antagomir** [comment]
The first example works, there is just one minor shortcoming

```
data(GlobalPatterns)
tse <- GlobalPatterns
tse_split <- splitByRanks(tse)
tse_split <- c(tse_split, ASV=list(tse))
names(tse_split)
```

For some reason, name cannot be assigned to the new element this way. But this can be circumvented by adding the names afterwards so I guess it is ok. 

> names(tse_split2)
"Kingdom" "Phylum"  "Class"   "Order"   "Family"  "Genus"   "Species" ""       

The latter does not work as such since the `altExp()` list will not contain the full assay, that would need to be added separately to run things in a batch mode.

Thanks!

**Comment by FelixErnst** [comment]
```r
tse_split <- c(tse_split, list(ASV=tse))
```

should work

**Comment by antagomir** [comment]
omg.  Somehow expected the first one would work as well because c(a=list(1), b=list(2)) does.. nice.
