### ISSUE TITLE
Importer for Biobakery outputs: MetAPhlAn3

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#189]
Data importer for MetaPhlan outputs, to (Tree)SE format, is missing and could be implemented to *mia*.

Here is [metaphlan to phyloseq import function](https://gist.github.com/lwaldron/512d1925a8102e921f05c5b25de7ec94) from @lwaldron

Some more examples [here](https://www.biostars.org/p/449688/) and [here](https://www.nicholas-ollberding.com/post/taxonomic-and-functional-profiling-using-biobakery-workflows/). 

It should be relatively straightforward to implement a similar one for TreeSE.

Some example data is on the way, for a closer look.

**Comment by TuomasBorman** [comment]
So this is different than https://github.com/microbiome/mia/pull/178?

**Comment by antagomir** [comment]
No I think it's the same :DDD

**Comment by TuomasBorman** [comment]
Easiest issue ever :D
