### ISSUE TITLE
Split SE by colData group

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#191]
There is a need to split SE objects by sample groups, typically defined by a colData field (subjectID, for instance).

Searches do not return anything readily available. We could implement the following in *mia* or make a PR in `SummarizedExperiment`. The latter may take a longer time?

```
library(mia)
data(GlobalPatterns)
se <- GlobalPatterns
field <- "SampleType"

# ideally, grouping could be either vector/factor of groups, or a name of colData field
splitSE <- function(se, grouping, use.names=TRUE) {
  # Sample indices for each group
  spl <- split(1:ncol(se), colData(se)[[grouping]])
  se_list <- lapply(seq_along(spl), function(i) se[,spl[[i]]])
  if (use.names) {names(se_list) <- names(spl)}
  return (se_list)
}
se_list <- splitSE(se, field)
```

**Comment by TuomasBorman** [comment]
This works little bit similarly to `splitByRanks`. (`altExp` cannot be used in this case, but maybe `MultiAssayExperiment`?) We could add this to `mia`, at least first. --> `splitByGroups?`

**Comment by antagomir** [comment]
`MAE` is not optimal either because to some extent it assumes that there can be matching between samples, even if it is not one-to-one. If there is a good data structure available that supports this then that would be optimal. If we do not identify such structure, then a simple list of `SE` objects might be the easiest solution. We can give a try to `MAE`, and if it seems to work well in practice, anyway, then whynot. Conceptually it might be a bit confusing, however, since in a typical use case the samples have some matching, and the different experiments correspond to different views or measurements for the same/matched samples.

The `splitByGroups` sounds like a good name. Or perhaps `splitBySampleGroups` or `splitByColData`

**Comment by FelixErnst** [comment]
`splitBy` would be a good name.

The function could use a defined factor or a character name for `colData` to get the factor. In addition the length of the factor could determine if cols or rows are split, either by the length or whether the name is found in col/rowData. colData should take precedence, since the split function is already usable for rows.

**Comment by antagomir** [comment]
When `SE` is split by rowData (e.g. taxonomy), one can use `altExps` because samples remain matched. This is how `splitByRanks` operates, for instance.

When `SE` is split by colData (e.g. whatever grouping there), one cannot use `altExps` because samples are, in general, not matched after the split by an arbitrary grouping factor while `altExp`requires that matching for the samples.

Then would the output from `splitBy` be a list of `SE` objects? This would be different than the output from `splitByRanks`.

**Comment by FelixErnst** [comment]
Sure. It is a differenc operation, therefore a different output is expected, isn't it?

Btw: `splitByRanks` also returns a list of `SE`s so I guess it is not that different after all

**Comment by antagomir** [comment]
`splitBy` with rowData is different from `splitByRanks` but it could be put into `altExp`, unlike `splitBy` with colData.

It might be conceptually more clear that `splitBy` returns a list in both cases. The utilities of `altExp` are not generally applicable in this case but that's probably fine for this one.
