### ISSUE TITLE
getExperimentCrossCorrelation for sample pairs?

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#192]
The current implementation of `getExperimentCrossCorrelation` calculates `n x m` correlation matrix between two input experiments.

There are many use cases, where we need to calculate correlation between sample pairs, when the columns of the two input experiments are paired. In that case, the calculation would return a correlation vector of length `n` instead, assuming that both experiments have `n` columns that are matched (by order, by name, or both). This is a subset of the full correlation matrix between two experiments, but remarkably faster to compute when only the paired correlations are needed.

Is it feasible to implement this as an additional argument in the `getExperimentCrossCorrelation` function? For instance, `paired=TRUE` or a similar argument. Or would it be better to implement an entirely new function? We would have an immediate use case in *miaTime*, if this can be added in one way or another.

**Comment by TuomasBorman** [comment]
Hmmm, yes I think the implementation should be relatively easy. However, I think we should avoid adding too much stuff to one function, because it makes it too complicated to use. Because this is as special case, we could add new function for this, but we can think about that

**Comment by antagomir** [comment]
Implementation and maintenance will be easier if it is a separate function. Then we can cross-reference these two functions in the @seealso field. 

Another important thing: calculating correlation is not sufficient, we will need to have support for general dis/similarity measures.

Perhaps a new function with a name `getExperimentPairedCorrelation` and/or `getExperimentPairedDissimilarity`.

(@YagmurSimsekk might like to wait that this is implemented, before optimizing the time divergence code)

**Comment by TuomasBorman** [comment]
I was starting to implement this and I realized that this function calculates correlations only for feature-pairs. For example, correlation between taxa and metabolites that share same samples. 

Currently we do not have functionality that calculates correlations between samples. We should implement this, I create some kind of draft

**Comment by antagomir** [comment]
Might be easiest to have this in a single function but I am not sure. You can consider something analogous like we have `transformSamples` and `transformFeatures` and `transformCounts` if this seems necessary/clearer to separate.
