### ISSUE TITLE
addPerSampleDominantTaxa looses altExps

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#206]
This happens:

```
data(GlobalPatterns)
tse <- GlobalPatterns
altExps(tse) <- splitByRanks(tse)

altExpNames(tse)
# [1] "Kingdom" "Phylum"  "Class"   "Order"   "Family"  "Genus"   "Species"

# The altExps are lost when adding dominant taxa to colData:
tse <- addPerSampleDominantTaxa(altExp(tse, "Genus"), name = "dominant_genera", abund_values="counts")
altExpNames(tse)
#character(0)
```

Imo this shouldn't happen and should be fixed.

**Comment by antagomir** [comment]
A similar thing seems to happen with runMDS, probably then also with other methods. Should be checked more broadly.

**Comment by TuomasBorman** [comment]
You seem to have a little mistake

`altExp`s are stored in `tse`, however, you are feeding `altExp(tse, "Genus")` as an input which **include genus level data without `altExp`s**

```
data(GlobalPatterns)
tse <- GlobalPatterns
altExps(tse) <- splitByRanks(tse)

altExpNames(altExp(tse, "Genus"))
# do not include altExps
```


Function seems to work as planned. However, I can see what was your intention. Should we have `rank = "Genus"` a parameter for this purpose (to get dominant taxa of certain rank)?

**Comment by antagomir** [comment]
Yes that would be a good solution.

**Comment by TuomasBorman** [comment]
It actually already includes the parameter. These return information on the most dominant phyla

```
data(GlobalPatterns)
tse <- GlobalPatterns

tse<- addPerSampleDominantTaxa(tse, name = "dominant_phyla", 
                               abund_values="counts", rank = "Phylum")

colData(tse)


perSampleDominantTaxa(tse, abund_values="counts", rank = "Phylum")

countDominantTaxa(tse, abund_values="counts", rank = "Phylum")
```

Does this solve your problem?

**Comment by antagomir** [comment]
Ah yes. Thanks.
