### ISSUE TITLE
Functions could/should gracefully handle zero row data 

### ISSUE THREAD

**Issue by nr0cinu** [microbiome/mia#207]
Hi :)

Imho, it would be good if the mia functions would return empty results when nrow(tse)==0.

For example:

```r
tse <- GlobalPatterns[rowData(GlobalPatterns)$Species %in% "not in the data"]
nrow(tse)
# [1] 0
getTaxonomyLabels(tse)
# Error in mapply("[", as.data.frame(t(as.data.frame(rd))), tax_cols_selected,  : 
# zero-length inputs cannot be mixed with those of non-zero length
# In addition: Warning message:
# In max(tax_ranks_selected) :
# no non-missing arguments to max; returning -Inf
agglomerateByRank(tse)
# Error: 'x' has nrow(x) == 0L.
```

If those functions would return `character(0)` or new TSEs with also nrow==0 this would be more consistent and one would not have to setup checks for workflows of nrow==0.

Thanks!
Bela

**Comment by antagomir** [comment]
I think this would be useful, unless @FelixErnst has something to add.

**Comment by FelixErnst** [comment]
Well, I guess I forgot some checks...

**Comment by FelixErnst** [comment]
Looking at it a bit more, I think an error in your first example might be in order. This would stick to the `error early, error often` guideline.

So the error in the second example is valid. I rephrased the error message for more verbosity in #217 

Does this work four you?
