### ISSUE TITLE
Making use of metadata() when processing tse containers with mia functions

### ISSUE THREAD

**Issue by nr0cinu** [microbiome/mia#209]
Hi,

it could be very useful if mia functions would add information about processing to the metadata() part of the container.

For example:
* agglomerateByRank could save the rank it was agglomerated on.
```r
data(GlobalPatterns)
GlobalPatternsGenus <- agglomerateByRank(GlobalPatterns, "Genus")
metadata(GlobalPatternsGenus)$agglomerated_rank <- "Genus" # <--- something like this, but automatically done by agglomerateByRank
metadata(GlobalPatternsGenus) # can then be used downstream
```
* subsampleCounts could save min_size 
* isContaminant could save the decontam options, like threshold.

Something similar is done for phyloseq in [microViz](https://david-barnett.github.io/microViz/articles/web-only/ordination.html#ps_extra), where the processing information (like agglomerated rank) is saved and then noted in output files like ordination plots.

Thanks!
Bela

**Comment by antagomir** [comment]
I think this is an important idea. How to best implement might be more tricky and case-by-case.

One option: user could select to store information in a metadata element, which would be named by the appropriate function. Each function would have some set of standard metadata that they will add this way, if requested. Like `metadata(GlobalPatternsGenus)$agglomerateByRank <- ....`
