### ISSUE TITLE
getTopTaxa rank option?

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#212]
It would handy if the `getTopTaxa` function could be used for any specified level, in the same way as `perSampleDominantTaxa` for instance.

It could work like this (but the rank option does not seem to be available yet, this returns ASVs):
`getTopTaxa(tse, top = 5, abund_values = "relabundance", rank="Phylum")`

This returns genus level info:
`perSampleDominantTaxa(tse, abund_values = "relabundance", rank="Genus")`

**Comment by FelixErnst** [comment]
Closed by 82eb400dab3288b3a81f13cc1c7ff68672cabcc1
