### ISSUE TITLE
relAbundanceCounts function with error.

### ISSUE THREAD

**Issue by ricmedveterinario** [microbiome/mia#222]
Hello, my name is Richard, and I have a question regarding the relAbundanceCounts function.

Is it not working? I tried to run the example you provided, but the same error always appears.

I tried to run it in a number of ways in a very reliable way to the examples. All.

9.1.1 Composition barplot (https://microbiome.github.io/OMA/microbiome-community.html)

GlobalPatterns <- relAbundanceCounts(GlobalPatterns)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘relAbundanceCounts’ for signature ‘"phyloseq"’

 tse <- relAbundanceCounts(tse)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘relAbundanceCounts’ for signature ‘"phyloseq"’

If I made a mistake, I apologize.

Thanks.

**Comment by antagomir** [comment]
It seems to me that you are trying to apply functions from miaverse on a `phyloseq` object. These functions assume `SummarizedExperiment` objects. You can use `data(GlobalPatterns, package="mia")` to make sure you get the example data in the correct format. The GlobalPatterns data set is available in both phyloseq and TreeSummarizedExperiment.
