### ISSUE TITLE
.calculate_rda: na.action option

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/mia#223]
https://github.com/microbiome/mia/blob/9050995ae179842422c51bd33771d6db497ad6f0/R/runCCA.R#L180

`vegan::rda` has an argument `na.action `

> Handling of missing values in constraints or conditions. The default (na.fail)
> is to stop with missing value. Choice na.omit removes all rows with missing
> values. Choice na.exclude keeps all observations but gives NA for results that
> cannot be calculated. The WA scores of rows may be found also for missing
> values in constraints. Missing values are never allowed in dependent community
> data

I was not able to use calculateRDA since I had missing values (some patients did not have "Age"). We might want to consider if we allow `na.action`. Though, I'm not sure if it can be implemented easily.

Downside is that the returned rda object does not have as many samples as `TreeSE` has if there are NAs.  

-Tuomas

**Comment by antagomir** [comment]
IMO we could pass all/most argument options that are available in *vegan* and the user is the one who decides how to deal with those limitations?

The name of this method is "Canonical Correspondence Analysis", and not "Canonical Correspondance Analysis" -> Fix as well.
