### ISSUE TITLE
Replace RDA with dbRDA

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/mia#227]
Hi,

currently `mia` has `runRDA` and `calculateRDA` functions that are wrappers for `vegan::rda()`. However, `vegan::dbrda` is more suitable because  there are also other options than euclidian dissimilarity (all that can be calculated with `vegdist`, I guess, + `dfun` option). 

We should consider replacing `vegan::rda` with `vegan::dbrda`. 

There are few differences that I found already

- No `scale` option --> can be dealt easily
- No _species scores_ returned (https://github.com/vegandevs/vegan/issues/254) --> we could add an option for that or just ignore

-Tuomas

**Comment by TuomasBorman** [comment]
I think function names could be still the same (runRDA and calculateRDA)?

**Comment by antagomir** [comment]
Same naming might work but we need to consider carefully because db-RDA is the "official" name of the newly suggested method, and it is different from the classical / standard RDA. We must also avoid confusion. But rundbRDA does look so nice either..

**Comment by TuomasBorman** [comment]
Yep, the issue with rundbRDA was just what I meant, but the name can be changed easily
