### ISSUE TITLE
Using mia for functional data

### ISSUE THREAD

**Issue by sarahisherb** [microbiome/mia#228]
Hi, I'm wondering if mia can be used to analyse functional data? I have a list of KEGGs with their relative abundances from the HUMANN 3.0 pipeline. It looks like the TSE class uses taxonomy only. Is there a way to work around this? 

Apologies if the question is irrelevant!

**Comment by antagomir** [comment]
Yes indeed it can be used for that, although we can certainly add many more tools in this integration toolkit in the future.

We have example data and already planning to add examples. We can try to check this week, I will mention here when some basic examples with Humann3 are in place, hopefully soon.

**Comment by sarahisherb** [comment]
Thanks for the quick reply! I figured out I have to make a TSE-class object as the input to use mia. I managed to do that, but I get this error when running diversity analysis 

```
diversity <- estimateDiversity(tse, index = "shannon")
```

`Error: 'abund_values' must be a valid name of assays(x)`

I'm not exactly sure what goes in abund_values, but it might have to do with the data import, I guess? I tried a few other options for `abund_values = `, but all come out with an error about the abund_values input. 

For context, I'm working with an abundance table with KO abundances in rows and samples as columns, like so: 
![image](https://user-images.githubusercontent.com/81591832/160745525-934abf3b-2ffd-42e0-b4a6-c0750d824269.png)

and a simple metadata file. To make the tse object, I run 

```
both_tse <- TreeSummarizedExperiment(assays = kegg.df.select,
                                     rowData = kegg.df.select,
                                     colData = metadata)
```

Which _looks like_ it's working fine, but my tse summary is: 

```
class: TreeSummarizedExperiment 
dim: 3950 7 
metadata(2): Species Site
assays(1): ''
rownames(3950): K00001 K00002 ... K22969 K23016
rowData names(0):
colnames(7): AT-2 PS-1 ... TN-2 TN-3
colData names(0):
reducedDimNames(0):
mainExpName: NULL
altExpNames(0):
rowLinks: NULL
rowTree: NULL
colLinks: NULL
colTree: NULL
```

with no data for rowData names. 

I hope this is the right place to ask this question, any help would be much appreciated! Would really like to get over this import step and get stuck into the statistical analyses using mia. 

Thank you!

**Comment by antagomir** [comment]
You can see available assays in your data object with `assayNames(tse)`.

The default is "counts", I think. You can specify this explicitly at the reading phase:

Recommended: `tse <- TreeSummarizedExperiment(assays = SimpleList(counts=myabundancematrix))` 
or
Possible: `tse <- TreeSummarizedExperiment(assays = list(counts=myabundancematrix))` 


The `assay` must be `matrix`. 

The `rowData` and `colData` must be `DataFrame`s (`data.frame` may work, too but is not recommended).

These are specified in `SummarizedExperiment` [documentation](https://www.rdocumentation.org/packages/SummarizedExperiment/versions/1.2.3/topics/SummarizedExperiment-class) (inherited by `TreeSummarizedExperiment` and cited in its manpage) and in [our OMA examples](https://microbiome.github.io/OMA/containers.html#loading-experimental-microbiome-data).  

We have online channels for support (Gitter / email), you can find info on how to subscribe at [https://microbiome.github.io/](microbiome.github.io)

Does this help? We will anyway try to see if some Humann3 examples could be added soon, keeping this open.

**Comment by sarahisherb** [comment]
Hi!! I think I figured it out and it worked,  it was definitely the SimpleList code that helps. I will show my code so you are interested to see if I did it right, and for others who may have the same problem. 

My data is as follows: 

`kegg.f` = abundance table of features as rows and samples in columns (as per image above) 
`metadata` = standard metadata table, but samples in rows and variables in columns 

both were imported to R as data.frames, then 

```
# abund_values has to take a matrix and then made into a SimpleList 
matrix <- as.matrix(kegg.f)
assays <- SimpleList(counts=matrix)

# rowData has to be in DataFrame
rowData <- DataFrame(kegg.f)

# colData contains data on the samples (i.e. the metadata?) and also has to be in DataFrame
colData <- DataFrame(metadata)

tse <- TreeSummarizedExperiment(assays = assays,
                                     rowData = rowData,
                                     colData = colData)
```

`assayNames(tse)` returns `[1] "counts"` 

and the `estimateDiversity`  results and ggplot2s look about right! 

I will leave this thread open though :)  Thanks for your help!

**Comment by antagomir** [comment]
Yes you are doing it right. +1
