### ISSUE TITLE
Alias for getPrevalentTaxa

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#233]
The `getPrevalentTaxa` can be useful function also for other assays and omics. I suggest to add an alias: `getPrevalentFeatures`

**Comment by TuomasBorman** [comment]
Good idea. Should we also consider aliases for other `*taxa` functions?

- getTopTaxa
- getUniqueTaxa
- countDominantTaxa
- getPrevalentTaxa
- getRareTaxa
- subsetByPrevalentTaxa
- perSampleDominantTaxa
- addPerSampleDominantTaxa

**Comment by antagomir** [comment]
Yes.
