### ISSUE TITLE
transformCounts error

### ISSUE THREAD

**Issue by kusandeep** [microbiome/mia#247]
Hi, 
Thanks for creating such an awesome package.
I am getting an error at transformCounts function, must be very basic mistake done by me, but would be great if I can get some help.

`> v5v7 <- transformCounts(v5v7, method = "relabundance") 
Error in MatrixGenerics:::.load_next_suggested_package_to_search(x) : 
  Failed to find a colSums2() method for data.frame objects.`

Thanks and much appreciated for help

**Comment by antagomir** [comment]
What is the class of the `v5v7` object?

**Comment by kusandeep** [comment]
Please see below.  
`> v5v7
class: TreeSummarizedExperiment 
dim: 2713 20 
metadata(0):
assays(1): counts
rownames(2713): OTU1 OTU2 ... OTU2712 OTU2713
rowData names(7): Kingdom Phylum ... Genus Species
colnames(20): S17s1B S17s1RH ... S23s5B S23s5RH
colData names(5): Sample Plot Rep Treat Sample_type
reducedDimNames(0):
mainExpName: NULL
altExpNames(0):
rowLinks: NULL
rowTree: NULL
colLinks: NULL
colTree: NULL`

**Comment by TuomasBorman** [comment]
Hi!

The problem is that your assay is in d`ata.frame `format; assays should be in `matrix` format. 

Does this work:

`assay(v5v7, "counts") <- as.matrix(assay(v5v7, "counts))`

**Comment by kusandeep** [comment]
Yes. All working now. Thanks for the quick response, loving the package so far. 
I probably will come up with some more queries :).

**Comment by TuomasBorman** [comment]
OK, good. All feedback is welcome, and we are happy to help if something is unclear

-Tuomas
