### ISSUE TITLE
Bioc checks

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#25]
Fix all warnings and errors from:

```
R CMD build 
R CMD check mia_x.y.z.tar.gz 
R CMD BiocCheck mia_x.y.z.tar.gz

```

**Comment by FelixErnst** [comment]
update: 2020-12-12 GHA on linux has a problem running the vignette. This is not reproducable locally with the Bioc docker image

**Comment by FelixErnst** [comment]
We take care of this for submission. I think that the GHA currently provides enough feedback. Please reopen, if you feel otherwise
