### ISSUE TITLE
assay in other format than matrix causes an error

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/mia#253]
Hi,

many our functions expect that `assay` is in `matrix` format. However, that is not the case all the time. In `TreeSE`, `assay` can also be in `data.frame` format, for instance. When user imports `counts` data in` df` format, this causes an error which is hard to interpret. 

We should solve this somehow. We could 

1. Add checks for every function that is affected by this problem, (and convert the data in `matrix` format if possible)

1. Add `checkImport` function that checks that the data is imported correctly

-Tuomas

**Comment by antagomir** [comment]
1. I think this is a good solution, when accompanied by an informative warning that might suggest that the user considers converting the assay into matrix format. It is likely that they want to do that, if they are trying to call functions that expect this.
2. It is good to have an object validator and that could potentially check other things at the same go.
