### ISSUE TITLE
agglomerateByRank help

### ISSUE THREAD

**Issue by kusandeep** [microbiome/mia#254]
Hi, 
I wanted to explore family-level abundance density, and for that, I used the code below. 
`v5v7_TSE_family <- v5v7_TSE %>% agglomerateByRank(rank = "Family")`

`plotAbundanceDensity(v5v7_TSE_family, layout = "jitter", abund_values = "relabundance",
                     n = 10, point_size=1, point_shape=19, point_alpha=0.3) + 
  scale_x_log10(label=scales::percent)`

However, when I agglomerate by family, seems like there are some uncultured "families" from different or same "Orders" agglomerating together and creating probably a false family (see the plot below)?. Any suggestion on how to deal with them?
One thought I had was to agglomerate by string up to Family to keep the uniqueness and show the whole string from Phylum up to family or genus. Function similar to 'microbiomeutilities::format_to_besthit'

![image](https://user-images.githubusercontent.com/38409245/169075062-419246e9-04ed-4335-90e3-970ebf64c911.png)

**Comment by antagomir** [comment]
Here the Family field contains "uncultured" members that are associated with multiple different higher ranks depending on the row. I think solutions are:

1) Mark "uncultured" as NA and ignore them; or aggregate data to rank level and discard "uncultured" before visualiztion

2) Rename them, for instance with an extended string as you propose, to distinguish between different uncultured families

With "uncultured" this is still somewhat manageable but the problem gets more tricky when there are cases with non-monophyletic groups with real names as reported [here](https://github.com/joey711/phyloseq/issues/927). I am not sure if there is a good other way to distinguish between terms that are in the same field with a different meaning. Suggestions welcome. 

The desired solution might depend on the context. Hence I am not sure if we want to impose a generic solution. 

However, the agglomeration function could generate an informative warning (or error) in such cases, at least. We could discuss if it should be a warning or error.

You can also check the argument `onRankOnly`: ‘TRUE’ or ‘FALSE’: Should information only from the
          specified rank be used or from ranks equal and above? See
          details. (default: ‘onRankOnly = FALSE’)

**Comment by kusandeep** [comment]
Thanks. Being a beginner would be great if you could please write the code to do the options 1st  (aggregate and discard "uncultured" ) that you suggested as this seems to be the quick fix for now. 
Also if possible, would be great to have the code for the second option as well to cross-check what's happening. I am working in TreeSummarizedExperiment environment so not sure how to apply `microbiomeutilities::format_to_besthit` function here.
Thanks

**Comment by antagomir** [comment]
You can see if this works for you

```
library(mia)
library(miaViz)
library(dplyr)
library(tidyr)

# Load example data and rename it to tse for generality of example
data(GlobalPatterns)
tse <- GlobalPatterns

# Replace NAs with "uncultured" to have similar rowData than in the reported issue
rowData(tse) <- apply(rowData(tse), 2, function (x) {replace_na(x, "uncultured")})
print(head(rowData(tse))) # check


# Option 1: Mark "uncultured" as NA and ignore them

## Replace "uncultured" with NA
rowData(tse) <- apply(rowData(tse), 2, function (x) {na_if(x, "uncultured")})
print(head(rowData(tse))) # check

## Aggregate to family level and add relative abundances
tse_family <- tse %>% agglomerateByRank(rank = "Family", remove_empty_ranks = TRUE)
tse_family <- transformSamples(tse_family, abund_values="counts", method="relabundance")

## We do have here examples of cases where Family names are not unique to order.
## This is confusing since same Family name does not correspond to same taxonomic group
print(unique(subset(rowData(tse), Family == "Piscirickettsiaceae")[, c("Order", "Family")]))
## Combine names as a hack around this:
rowData(tse_family) <- rowData(tse_family) %>%
    as.data.frame %>%
    unite(Group, Phylum:Family, remove=FALSE) %>%
    DataFrame
rownames(tse_family) <- rowData(tse_family)$Group

## Plot
plotAbundanceDensity(tse_family, layout = "jitter", abund_values = "relabundance", n = 10, point_size=1, point_shape=19, point_alpha=0.3) + scale_x_log10(label=scales::percent)
```

**Comment by antagomir** [comment]
@microsud or @TuomasBorman do you have another trick for the "Combine names as a hack" point in my example above (just before the last plot)? I think we already implemented something to combine ranks but could not immediately find where. The `agglomerateByRank` or `plotAbundanceDensity` do not readily provide this.

**Comment by microsud** [comment]
The taxonomic labels are challenging. The option I use is different. Often the uncultured taxa are rare and therefore by using the `agglomerateByPrevalence` you can avoid them. 

```
tse <- GlobalPatterns
# data can be aggregated based on prevalent taxonomic results
tse2 <- agglomerateByPrevalence(tse,
                                rank = "Family",
                                detection = 1/100,
                                prevalence = 1/100,
                                as_relative = TRUE)


## Plot
tse2 <- transformSamples(tse2, abund_values="counts", method="relabundance")
plotAbundanceDensity(tse2, layout = "jitter", 
                     abund_values = "relabundance", 
                     n = 10, point_size=1, 
                     point_shape=19, point_alpha=0.3) + 
    scale_x_log10(label=scales::percent)
```
If they still pop up then they are likely important in your data and you need to investigate them in detail.

**Comment by antagomir** [comment]
It is not clear from the function documentation whether `agglomerateByPrevalence` selects the prevalent ones before or after agglomeration. This makes a difference. The non-prevalent ones can collectively contribute remarkably to relative abundance estimates. 

Action point: 
- clarify the manpage
- make sure that the default is as expected (prevalence filter after agglomeration); otherwise consider providing a warning or, preferably, fixing the function so that it works as could be reasonably expected

**Comment by kusandeep** [comment]
Thanks for providing the code. 

now I am getting error at

> rowData(tse) <- apply(rowData(tse), 2, function (x) {replace_na(x, "uncultured")})
Error in replace_na(x, "uncultured") : 
  could not find function "replace_na"
Called from: FUN(newX[, i], ...)
Browse[1]> 

And then the terminal get stuck at this error!!

**Comment by kusandeep** [comment]
> getting error at
> 
> > rowData(tse) <- apply(rowData(tse), 2, function (x) {replace_na(x, "uncultured")})
> > Error in replace_na(x, "uncultured") :
> > could not find function "replace_na"
> > Called from: FUN(newX[, i], ...)
> > Browse[1]>

**Comment by antagomir** [comment]
The `replace_na` function comes from the `tidyr` R package.. in fact there is a command in the above reproducible example that is loading this package.

**Comment by kusandeep** [comment]
> The taxonomic labels are challenging. The option I use is different. Often the uncultured taxa are rare and therefore by using the `agglomerateByPrevalence` you can avoid them.
> 
> ```
> tse <- GlobalPatterns
> # data can be aggregated based on prevalent taxonomic results
> tse2 <- agglomerateByPrevalence(tse,
>                                 rank = "Family",
>                                 detection = 1/100,
>                                 prevalence = 1/100,
>                                 as_relative = TRUE)
> 
> 
> ## Plot
> tse2 <- transformSamples(tse2, abund_values="counts", method="relabundance")
> plotAbundanceDensity(tse2, layout = "jitter", 
>                      abund_values = "relabundance", 
>                      n = 10, point_size=1, 
>                      point_shape=19, point_alpha=0.3) + 
>     scale_x_log10(label=scales::percent)
> ```
> 
> If they still pop up then they are likely important in your data and you need to investigate them in detail.
Thanks 
This one worked too, however, the figure looks slightly different now with "other" in the list and one unculture still appeared too. 
![image](https://user-images.githubusercontent.com/38409245/169693382-79a0fd4e-e8de-4480-8cef-7e47cd2ecf3b.png)

**Comment by kusandeep** [comment]
> The `replace_na` function comes from the `tidyr` R package.. in fact there is a command in the above reproducible example that is loading this package.

Thanks. It was my R playing funny..

another related query. 
Showing combined name/string is still my favorite option as it does help investigate those uncultured taxon taxonomy strings. 
Also, I was wondering if this can be implied in `plotTaxaPrevalence` too which will solve the non-monophyletic groups issue as you pointed out above. Here I guess the y-axis need to relabel by using a combined string if that makes sense.. 
see the example below.
`plotTaxaPrevalence(tse, rank = "Family",
                   detections = c(0.005, 0.01, 0.02),
                   as_relative = TRUE,
                   min_prevalence = 1)`

**Comment by antagomir** [comment]
We could have an option for "full" names in `plotTaxaPrevalence` I think.

In addition we need an example on how to add such full names in the tse data object (a new field in rowData). Such example could be in `plotTaxaPrevalence` manpage and/or OMA rowData manipulation examples for instance.

**Comment by kusandeep** [comment]
That would be very helpful.

**Comment by antagomir** [comment]
It may take some time, though.

**Comment by kusandeep** [comment]
No worries, Thanks for the help here.

In the meantime. I have recycled your code from above which worked, except for those funny non-monophyletic groups. see the example below.

`
# Replace NAs with "uncultured" to have similar rowData than in the reported issue
rowData(tse) <- apply(rowData(tse), 2, function (x) {replace_na(x, "uncultured")})
print(head(rowData(tse))) # check

# Replace "uncultured" with NA
rowData(tse) <- apply(rowData(tse), 2, function (x) {na_if(x, "uncultured")})
print(head(rowData(tse))) # check

# Transform taxa string
tse_string <- transformSamples(tse, abund_values="counts", method="relabundance")

# Combine names as a hack around this:
rowData(tse_family) <- rowData(tse_family) %>%
  as.data.frame %>%
  unite(Group, Phylum:Family, remove=FALSE) %>%
  DataFrame
rownames(tse_family) <- rowData(tse_family)$Group
# TaxaPrevalence plot
plotTaxaPrevalence(tse_string, rank = "Family",
                   detections = c(0.005, 0.01, 0.02, 0.05),
                   as_relative = TRUE,
                   min_prevalence = 1)`
![image](https://user-images.githubusercontent.com/38409245/170822510-f5401b8f-2f3c-4d9b-86d7-d7fbf36d4c95.png)

**Comment by antagomir** [comment]
Thanks. Is this a general comment, or a question?

**Comment by kusandeep** [comment]
It is a general comment as once you will have all the taxonomic strings concatenated after the agglomeration step, this problem should be solved. So I will wait for that.

**Comment by antagomir** [comment]
I again bumped into this in another way.

```
# Load example data
library(mia)
data(GlobalPatterns, package="mia")

# Aggregate to Genus level
agg <- agglomerateByRank(GlobalPatterns, rank="Genus")

# There are 1516 rows
print(length(rownames(agg)))

# There are 1499 unique rows
print(length(unique(rownames(agg))))
```

The reason seems to be that there are genera with same name but different higher level. 

Row/feature names should be unique if they refer to different things like here (otherwise they should be merged, right?). 

Hence, good default behavior would provide unique names. Either by providing the full concatenated names, or by adding a number after each duplicate name (and thowing a warning).

I am not sure if we should allow having duplicated rownames in the output in the first place.

**Comment by antagomir** [comment]
@Daenarys8 can you check this one?

**Comment by antagomir** [comment]
up

**Comment by 0xMuluh** [comment]
Hi, I have followed up on the thread; This issue is now handled in mia. agglomeratByRank now provides unique names by appending a number.

```
# load sample data
library(mia)
library(tidyr)
data(GlobalPatterns)
tse <- GlobalPatterns

# we just replace na since agglomerateByRank removes by default
rowData(tse) <- apply(rowData(tse), 2, function (x) {replace_na(x, "uncultured")})

# transform taxa
tse_string <- transformSamples(tse, abund_values="counts", method="relabundance")

# plot data with min_prevalence of 0.08 to avoid cluttering the plot
plotFeaturePrevalence(tse_string, rank = "Family",
                                           detections = c(0.005, 0.01, 0.02, 0.05),
                                           as_relative = TRUE,
                                          min_prevalence=0.08)
```

![prevel](https://github.com/user-attachments/assets/02519ba4-0b2f-4e61-ba7a-d883ee0ae0d4)

**Comment by 0xMuluh** [comment]
> The reason seems to be that there are genera with same name but different higher level.
> 
> Row/feature names should be unique if they refer to different things like here (otherwise they should be merged, right?).
> 
> Hence, good default behavior would provide unique names. Either by providing the full concatenated names, or by adding a number after each duplicate name (and thowing a warning).
> 
> I am not sure if we should allow having duplicated rownames in the output in the first place.

```
rowData(tse) <- apply(rowData(tse), 2, function (x) {replace_na(x, "uncultured")})
agg <- agglomerateByRank(GlobalPatterns, rank="Genus")
print(length(rownames(agg)))
[1] 1516
print(length(unique(rownames(agg))))
[1] 1516
```
If there's some additional requirement, we can look at, otherwise we can close issue as resolved.

**Comment by antagomir** [comment]
seems good.
