### ISSUE TITLE
Missing rank at loadFromMetaphlan.R

### ISSUE THREAD

**Issue by ChouaibB** [microbiome/mia#256]
Hi,

When using the function, there seem to be that "Class" is missing at the altExps slot at the returned TreeSE.
It looks that "class" is missing at lines 179 and 200-201 of [loadFromMetaphlan.R](https://github.com/microbiome/mia/blob/master/R/loadFromMetaphlan.R)

![image](https://user-images.githubusercontent.com/86964562/170041445-210b512f-23b0-414b-9acb-c869bbc051f7.png)

![image](https://user-images.githubusercontent.com/86964562/170041495-23de8a40-ca7f-4152-96e3-d47f3bd93750.png)

Thanks

**Comment by antagomir** [comment]
@ChouaibB if the solution is obvious could you create a PR and @TuomasBorman can check and merge?
