### ISSUE TITLE
Function to merge two TSE objects?

### ISSUE THREAD

**Issue by nr0cinu** [microbiome/mia#268]
Hi,

Is there something analogous to `merge_phyloseq`? Otherwise, this would be nice to have.

Thanks,
Bela

**Comment by TuomasBorman** [comment]
Hi,

cbind and rbind work. However, when combining multiple samples (with individual TreeSE) with cbind, it is expected that rows match

Actually, I am currently working with more flexible merge function

I will let you know when it is ready, but before that test if cbind/rbind works in your case

-Tuomas

**Comment by nr0cinu** [comment]
Hi,

thanks. My two TSEs have different rows, so I ended up creating the merged TSE from scratch.

A more flexible merge function would be very appreciated :)

Thanks.

**Comment by TuomasBorman** [comment]
Hi Bela!

Now we have merged this function mergeSEs. Thanks for suggestion!

-Tuomas

**Comment by antagomir** [comment]
Yes, and please test & provide some feedback if you notice anything!
