### ISSUE TITLE
Biom import

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#273]
The mia package has now the function `makeSummarizedExperimentFromBiom`. This creates SE from biom data files.

However, we have decided to use TreeSE for all microbiome data sets, for consistency (SE is missing slots needed by some methods and is therefore suboptimal anyway).

Shall we convert this function into `makeTreeSEFromBiom`? 

Also check if the mia package has other functions that should need a similar conversion.

**Comment by TuomasBorman** [comment]
Yes, this is good. 

Also: In many cases the documentation says SummarizedExperiment. Should we change that to TreeSummarizedExperiment or (Tree)SummarizedExperiment (even though SE is still working normally) --> might be more clear that we use only TreeSE in documention

**Comment by antagomir** [comment]
I think we should use TreeSE everywhere in the examples.

However TreeSE is an SE. Packages could still accept objects from the more generic SE class as input in those cases where stuff from TreeSE is not needed. There is no reason to unnecessarily limit the scope and applicability of the tools. They may find other uses outside of the "miaverse" framework.

But examples in OMA & demo data sets & packages & vignettes are a different case. It is confusing to switch between TreeSE and SE, and bump into compatibility issues all the time. Therefore in all example documentation in the miaverse framework we should switch to TreeSE (IMO).

**Comment by TuomasBorman** [comment]
Yes, SE should be kept in the functions

I meant should we change these SEs from here for example: https://microbiome.github.io/mia/reference/transformCounts.html

Arguments
x
 A SummarizedExperiment object.

--> 
Arguments
x
 A TreeSummarizedExperiment object.

**Comment by antagomir** [comment]
RIght. Tricky question(?). 

It could be one of these:

1. (Tree)SummarizedExperiment
-> would sort of indicate that both are accepted

2. SummarizedExperiment or TreeSummarizedExperiment
-> explicitly tells what is allowed, although potentially redundant

3. SummarizedExperiment
-> might be misleading if some of the functionality uses TreeSE capabilities (there could be tree transformations like phILR but currently we do not have any of those and there was also earlier discussion that we might like to have another package for those things; see #197 )

4. TreeSummarizedExperiment
-> Justified only if this is really required by the function, otherwise misleading (too limiting)

My preference would be perhaps 1 or 2?

**Comment by TuomasBorman** [comment]
Hmm, yes

We could just keep the documentation as it is? (That would take a lot of work to change those, and it might not give any additional value)


My intention was to make documentation more consistent, but it is not good to  say that TreeSE is required when only SE is...

And as you said TreeSE is SE

**Comment by antagomir** [comment]
In OMA, probably best to stick to TreeSE everywhere. Can be changed now (better) or over time (perhaps more practical).

In mia and other R packages, we have 

1) general documentation on function arguments; and 
2) use case @examples. 

In the first case (argument documentation), probably best to stick to SE (or the most generic class whatever it is).

In the second case (examples), this is more flexible I think. In principle it would be useful to have the examples with TreeSE always because these become copypasted elsewhere etc. On the other hand, perhaps this is not so important that everything must be rewritten right now. Would be good to keep in mind, however, when updating the material or creating new examples?
