### ISSUE TITLE
getExprimentCrossAssociation example fails occasionally

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#279]
The example with `microbiomeDataSets::peerj32()` in getExprimentCrossAssociation fails occasionally in automated builds due to network failures. This might be better to replace with a data set that is in the mia package itself. Or we could add peerj32 or HintikkaXO data set in mia for this purpose.

**Comment by TuomasBorman** [comment]
Yes, good idea. hintikkaXO is used in many examples in OMA, so that might be a better choice to add?

**Comment by antagomir** [comment]
Yes I think that's good.

It is now in SE format in microbiomeDataSets, should be put in TreeSE if it is stored in mia.
