### ISSUE TITLE
additional parameters for `agglomerateByRank` or a new supporting function

### ISSUE THREAD

**Issue by microsud** [microbiome/mia#3]
During testing for visualization, I realize the need for some functionality for making the selection of taxa to plot. This feature for aggregating is important to reduce the high number of variables (taxa in this case) for any visualization to a practical number.   

In `microbiome R package`, functions below help in improving visualization by reducing number of taxa to plot. 
see [aggregate_taxa.R](https://github.com/microbiome/microbiome/blob/master/R/aggregate_taxa.R)
see [aggregate_rare.R](https://github.com/microbiome/microbiome/blob/master/R/aggregate_rare.R)
Now deprecated [aggregate_top_taxa](https://github.com/microbiome/microbiome/blob/master/R/aggregate_top_taxa.R) but I think it can be modified to include an option for users to choose a method for selecting top taxa by a custom function like below: 

```
#' @param x \code{\link[SummarizedExperiment:SummarizedExperiment-class]{SummarizedExperiment}}
#' @param top Numeric, how many top taxa to return.
#' @param method Specify the method to determine top taxa. Either sum, mean or median.
#'
#' @examples
#' se <- GlobalPatterns
#' top_taxa <- topTaxa(se, method="median", top=5)
topTaxa <- function(x, method=c("sum","mean","median"), top=5){
    taxs <- NULL
    if(method=="sum"){
        taxs <- sort(rowSums(assay(x)),decreasing = TRUE)[1:top]
    } else if (method=="mean"){
        taxs <- sort(rowMeans(assay(x)),decreasing = TRUE)[1:top]
    } else if (method=="median") {
        taxs <- rowMedians(assay(x))
        names(taxs) <- rownames(assay(x))
        taxs <- sort(taxs,decreasing = TRUE)[1:top]
    }
    return(names(taxs))
}
```
Below is a quick and dirty attempt at barplot.

```
library(mia)
library(dplyr)
library(tibble)
library(tidyr)
library(ggplot2)
library(RColorBrewer)
# edit
data(GlobalPatterns, package="MicrobiomeExperiment")
#
se <- GlobalPatterns
se.sgg <- agglomerateByRank(se, rank = "Phylum")
se.sgg <- relAbundanceCounts(se.sgg)
##### melt SE to long data format

# taxonomy data
me_tax <- rowData(se.sgg) %>% 
    data.frame() %>%
    rownames_to_column("TaxaID") # may need to enfore in case of user supplied duplicate

# Metadata
me_sam <- colData(se.sgg) %>% 
    data.frame() %>%
    rownames_to_column("SamId") # may need to enfore in case of user supplied duplicate

dfSE <- assays(se.sgg)$relabundance %>% # this can be optional (relative==TRUE) or something similar
    data.frame() %>%
    rownames_to_column("TaxaID") %>% 
    # may need to enforce in case of user supplied duplicate names
    pivot_longer(!TaxaID, values_to = 'Abundance', names_to = "SamId") %>%  
    left_join(me_tax, by = "TaxaID") %>% 
    left_join(me_sam, by = "SamId") %>% 
    mutate_if(is.factor,as.character)

top_taxa <- topTaxa(se.sgg, method="median", top=10)

dfSE <- dfSE %>% 
    mutate(TaxVar= ifelse(TaxaID %in% names(top_taxa), TaxaID, "Other"))

p <- ggplot(dfSE, aes_string(x="SamId", y="Abundance", fill="TaxVar")) +
    geom_bar(position="stack", stat="identity") +
    #scale_x_discrete(labels=dfm$xlabel, breaks=dfm$Sample)
    scale_x_discrete() + 
    labs(y = "Abundance",x="") + 
    theme_bw() +
    theme(axis.text.x=element_text(angle=90, 
                                   hjust=0.95,
                                   vjust=0.2),
          panel.grid = element_blank(),
          legend.text = element_text(face="italic")) +
    scale_fill_brewer("Phylum",palette = "Paired") # this can be argument (fill.colors= "Paired") or something similar
p + scale_y_continuous(labels = scales::percent) # this can be optional (relative==TRUE) or something similar

```
![barplotSE](https://user-images.githubusercontent.com/16476233/96480887-1a630700-123b-11eb-82c0-e2409ca6fb2a.png)

```
#Option for facetting by user provided variable. Should match `colnames(colData(se.sgg))`
p + facet_wrap(~SampleType, scales = "free")
```

Heatmap option for `SE` found this package called [SEtools](https://github.com/plger/SEtools).

**Comment by microsud** [comment]
From @FelixErnst 
#https://github.com/FelixErnst/MicrobiomeExperiment/issues/18
Hi Sudarshan,

lets break this down.

The agglomerateByRank or aggValue functions from TreeSummarizedExperiment do the summing up and I guess from your code example this works fine, does it?
Second step melting of data to be plotable
Relabeling of taxonomic information based on n most abundant taxa.
I would suggest, that this goes into the mia package, since it isn't connected to the data structure, but how this data gets visualized.

Can you repost the issued there and close this one? Thanks

**Comment by microsud** [comment]
Hi @FelixErnst 
Thanks for clarity in reporting. 
1. `agglomerateByRank` or `aggValue` functions: Tested only `agglomerateByRank` and it works.
2. Second step melting of data to be plotable: Yes and needs some stricter checks than in the example.
3. Relabeling of taxonomic information based on `n` most abundant taxa: Yes. I showed one example. Other ways of aggregating can be based on user-provided thresholds for abundances and prevalences in samples, `aggregate_rare.R` function in the `microbiome` pkg is an example. These are common approaches in microbiome studies to improve visualization.

Best wishes,
Sudarshan

**Comment by FelixErnst** [comment]
Hi Sudarshan @microsud,

Sounds good. So I guess the next step would getting a `melt` function and the `topTaxa` written up.

Would you author a pull request for a S4 Method for `melt` and `topTaxa`, which includes additional arguments to select the assay? (`abund_values = "relabundance"`).

Felix

**Comment by FelixErnst** [comment]
Maybe a good name for the `melt` function would `meltAssay`, since that is a bit more descriptive than just `melt` or `meltSummarizedExperiment` etc

**Comment by FelixErnst** [comment]
Have a look at #4 . There is a factor for adjustment coming in, which has to get applied per column before melting.

**Comment by microsud** [comment]
@FelixErnst This would be my first S4 method and will need some time 😅

**Comment by FelixErnst** [comment]
You will get there, I am sure.

If you have questions commit the progress made so far to a branch and open a pull request. That would be the right place to discuss the implementation
