### ISSUE TITLE
decontam

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#30]
Identification of potential reagent contaminants; important for low biomass samples. decontam is a commnly used package for this, which is compatible with phyloseq, so would be good to link to mia.

**Comment by FelixErnst** [comment]
I will have a look at it, but maybe this can be only implemented on `decontam`'s side.

**Comment by FelixErnst** [comment]
`decontam` is a rather small package and the code base is quite manageable.

I am not sure, what the interest of the authors is to make the functions accessible for `SE` objects.

@benjjneb: Is there interest in discussing this context?

**Comment by benjjneb** [comment]
> @benjjneb: Is there interest in discussing this context?

Yes.

To date we have prioritized near-zero dependencies (hence the fragile phyloseq integration that doesn't require phyloseq as a package). That is in part because decontam is integrated outside of the R universe, where fewer dependencies are an advantage.

But integrating with SummarizedExperiment would be worth doing I think.

**Comment by FelixErnst** [comment]
I will create a PR for mia and let you know, when it is done. We can discuss any particulars in the PR.

Would you be open to a PR on decontam for better integration, if I need change things around?

**Comment by benjjneb** [comment]
> Would you be open to a PR on decontam for better integration, if I need change things around?

Yes. I will have this weird bias against incorporating new dependencies for the reason describe above, but I'd also like to integrate better with SE packages so...

**Comment by FelixErnst** [comment]
I opened up a PR for decontam benjjneb/decontam#89 restructuring the function to use S4 methods. It shouldn't break any existing code. 

If that goes through and ends up on Bioconductor, we can merge the PR I opened for `mia`

**Comment by FelixErnst** [comment]
#57 and benjjneb/decontam#89

**Comment by benjjneb** [comment]
Apologies for being slow on this. I've been teaching a new class this semester.

I should be able to test the PR on a full decontam workflow I have locally and then pull it (or request changes) in the next week.

**Comment by benjjneb** [comment]
Tests all passed on my end. One last small request to update the documentation for the data types accepted by `isContaminant`: https://github.com/benjjneb/decontam/pull/89#issuecomment-815914287
