### ISSUE TITLE
Generic metaphlan importer

### ISSUE THREAD

**Issue by ChouaibB** [microbiome/mia#306]
Hi,

The `mia` function `loadFromMetaphlan` has been working perfectly with metaphlan version 2 and 3.
After testing the new 4th version, it seems that output samples have an extra header that breaks the merging when using [the script provided by the authors](https://github.com/biobakery/MetaPhlAn/blob/master/metaphlan/utils/merge_metaphlan_tables.py). An example of the extra header which seems that it existed already at the 3.0.14 version:
https://forum.biobakery.org/t/merge-metaphlan-tables-py-broken/3507
Additionally, when running the metaphlans with different parameters additional results could be obtained, e.g. [metaphlan 2 with additional columns](https://s20709.pcdn.co/wp-content/uploads/2018/06/pasted-image-0-4.png) which is the case also for higher versions, which perhaps the user would like to merge and use at downstream analysis.

Modifying [the merging script provided by the authors](https://github.com/biobakery/MetaPhlAn/blob/master/metaphlan/utils/merge_metaphlan_tables.py) would eventually solve all these problems, and eventually different output tables will be produced breaking the standard output upon which  `loadFromMetaphlan` depends on. **The script could be modified especially since it seems no re-norming or transforming of data is performed.**

Could then adding/changing the following features at `loadFromMetaphlan` make it generic for all versions and data produced:

- [The checking of metaphlan file](https://github.com/microbiome/mia/blob/master/R/loadFromMetaphlan.R#L130), by parsing the header separately? And changing [this condition](https://github.com/microbiome/mia/blob/master/R/loadFromMetaphlan.R#L164) to be able to load merged files that do not have the "ncbi_id" column (for instance the new metaphlan 4 is based on the SGB database and when converting to GTDB the specific column is discarded, and file is not able to be loaded)
- Ability to internally merge from the individual files, e.g. by specifying folder path or a wildcard of files names?

Thank you.

**Comment by antagomir** [comment]
How about having separate importers for versions 2,3,4? For those parts that are shared between all, one could use internal functions. This might help to keep things simple.

In addition there could be a wrapper that recognizes the version but I am not sure if this is needed or helpful, the user should know which version they are dealing with.

I would perhaps keep any merging steps explicit and show in examples how to do them? Then it stays a bit more transparent what is being done in the merging operations.

It would be good to have importer at least for the most common expected cases, like the individual files vs. total merge (and others if there are).

**Comment by ChouaibB** [comment]
Going back to official releases (based on github); [metaphlan2](https://github.com/biobakery/MetaPhlAn/tree/2.7.8), [metaphlan3](https://github.com/biobakery/MetaPhlAn/tree/3.0), [metaphlan4](https://github.com/biobakery/MetaPhlAn).
Based on the source code of each version, the one that produces the single sample outputs (metaphlan.py) and the corresponding merging script provided (merge_metaphlan_tables.py); especially looking at the parts of the code when writing output files:

metaphlan2:
* single files: depending on the parameters of the run different headers are obtained; [line 1482](https://github.com/biobakery/MetaPhlAn/blob/2.7.8/metaphlan2.py#L1482); seemingly "clade_taxid" was not present as a column output in this version (in relation to [line 164 of loadFromMetaphlan](https://github.com/microbiome/mia/blob/master/R/loadFromMetaphlan.R#L164); if I understood right?)
* merged file: will merge only "relative_abundance" ([line 55](https://github.com/biobakery/MetaPhlAn/blob/2.7.8/utils/merge_metaphlan_tables.py#L55)), and seemingly header of the form "ID" then samples id names ([line 78](https://github.com/biobakery/MetaPhlAn/blob/2.7.8/utils/merge_metaphlan_tables.py#L78))

metaphlan3:
* single files: similarly as before and "clade_taxid" is present ([line 1034](https://github.com/biobakery/MetaPhlAn/blob/3.0/metaphlan/metaphlan.py#L1034))
* merged file: seemingly either "clade_name, relative_abundance" or "clade_name, clade_taxid,relative_abundance"

metaphlan4:
* single files: same as metaphlan3 ([line 1034](https://github.com/biobakery/MetaPhlAn/blob/3.0/metaphlan/metaphlan.py#L1034)), however with the "pre-headers" different, the ones indicating database version and so on (+ the bug reported earlier; shell command of running it prints there as well)
* merged files: will merge only the first three columns of single files that must include relative_abundance column ([line 25](https://github.com/biobakery/MetaPhlAn/blob/master/metaphlan/utils/merge_metaphlan_tables.py#L25))

I could double check all with some light demo samples (raw sequence samples), with the official tagged releases to confirm.

I don't know if this would be ideal solution, but having global variables (vector of all possible column names) for each single files and merged files, perhaps further per version, and check if they exist in the data to be loaded (single or merged) ?

**Comment by antagomir** [comment]
Generic solutions are good but must be balanced with time and effort.

If the importers for version 2-3 have worked so far without any issues (reports), perhaps there is no urgent need to fix/expand them?

But if new importer is created for version 4, it is good to consider a bit more. Light-weight testing might be good.

**Comment by ChouaibB** [comment]
Sure, I will start with the testing.

**Comment by ChouaibB** [comment]
The demo (3 light weight) raw sequences were taken from [snakemake tutorial](https://snakemake.readthedocs.io/en/stable/tutorial/short.html), and tested on metaphlan v3.0.14 and metaphlan v4.0.1; with default parameters.

metaphlan3 single sample file:
![image](https://user-images.githubusercontent.com/86964562/190386365-234a4d42-9d51-46c6-aad9-d77c220ebd08.png)

metaphlan3 merged samples:
![image](https://user-images.githubusercontent.com/86964562/190386572-8380ae43-80b7-470c-94fd-df32fbaa15b9.png)

metaphlan4 single sample file:
![image](https://user-images.githubusercontent.com/86964562/190386954-73cc1999-140e-4ab3-aeef-d55b449a4adc.png)

metaphlan4 merged samples:
![image](https://user-images.githubusercontent.com/86964562/190387102-d58c0022-3f3f-424a-b8c3-eb3753350142.png)

metaphlan4 single sample file (header) converted from SGB to GTDB:
![image](https://user-images.githubusercontent.com/86964562/190388304-809a08f0-f87c-4deb-a86c-cf3d6f374263.png)

metaphlan4 fail when merging converted SGB to GTDB files:
![image](https://user-images.githubusercontent.com/86964562/190388445-4387a7db-d908-469f-b54d-e8d1c7802b2f.png)

And the test on the current mia::loadFromMetaphlan
![image](https://user-images.githubusercontent.com/86964562/190389055-55eb66f1-ce59-40ec-869f-cf45c8d59617.png)

**Comment by TuomasBorman** [comment]
I believe this is already done or?

**Comment by ChouaibB** [comment]
The PR for it was closed for the moment link: https://github.com/microbiome/mia/pull/308
