### ISSUE TITLE
Sticker

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#307]
Create project sticker. 

See [hexSticker package](https://github.com/GuangchuangYu/hexSticker).

How about just "mia" and/or "OMA" sticker with no more explanation? That might be more compact than "miaverse".

**Comment by TuomasBorman** [comment]
![image](https://user-images.githubusercontent.com/60338854/190866361-e639571c-e256-44e9-b316-a8c561cb11a4.png)

suggestions/feedback

**Comment by antagomir** [comment]
It's great. 

One thing I would consider is whether the title fonts ("mia") should be with more clear type?

Also, considering common sticker sizes, it would be good to extend URL to cover the whole segment (now just 70% or so).

Slightly more margin between text and figure elements.

**Comment by TuomasBorman** [comment]
![figure2](https://user-images.githubusercontent.com/60338854/192004425-ac31f5ed-dd2c-4ef8-afa1-d402c60f34c8.png)

**Comment by antagomir** [comment]
It's nice! Some more suggestions:

- Figure appears a bit crowded. How about fewer arrows, the point would still be clear?
- Microbial ecology has known symbiotic, commensal, and competitive relations and loops; just wondering if the figure could reflect on that a bit (I mean different types of links, like here: https://www.cell.com/cms/attachment/2010698689/2032682312/fx1.jpg)
- I would still increase the font of URL (there is some space left) but perhaps this is more like a matter of taste

**Comment by TuomasBorman** [comment]
![mia_sticker](https://user-images.githubusercontent.com/60338854/192037122-ba4e81cb-83ac-4bc5-9b58-14de106e6b80.png)

**Comment by antagomir** [comment]
Is there an editable version available? We could have some other standard link types in addition to arrows, I could give a shot perhaps. @nuorenarra might have some nice feedback (?)

**Comment by TuomasBorman** [comment]
1 
![mia_sticker](https://user-images.githubusercontent.com/60338854/198566160-d86d1762-3f6d-42e0-9518-01b9c532867a.png)
2 
![mia_sticker2](https://user-images.githubusercontent.com/60338854/198566257-f41b0412-633a-42c9-968f-bda2a19a62b6.png)
3
![mia_sticker3](https://user-images.githubusercontent.com/60338854/198566315-e6349b27-e31f-4183-b35b-f3f074ca9c6c.png)
4
![mia_sticker4](https://user-images.githubusercontent.com/60338854/198566329-9d9ae8c7-1b66-42b9-a4c8-7e10645f4a3b.png)
5 
![mia_sticker5](https://user-images.githubusercontent.com/60338854/198566382-ddc16213-65ee-4195-90d3-4cd5008a9be1.png)
6
![mia_sticker6](https://user-images.githubusercontent.com/60338854/198566397-3fa8887b-3582-4a3e-a369-2bd182b30cdd.png)
7
![mia_sticker7](https://user-images.githubusercontent.com/60338854/198566436-ceee3a85-07e0-4292-a3d6-deed69638581.png)
8 
![mia_sticker8](https://user-images.githubusercontent.com/60338854/198566457-37fae480-27f7-458a-9794-0439208a216a.png)

**Comment by TuomasBorman** [comment]
Is there any suitable one? I would go with 8 so that we get this forward

Or perhaps 7

**Comment by antagomir** [comment]
I like 8. 

Would be good to hear what @nuorenarra view, how does it look?

**Comment by nuorenarra** [comment]
I like 8 too, but arrows seem too narrow to see when its small

**Comment by antagomir** [comment]
This could be tested by printing on real size. Have you tried it out, @TuomasBorman ?

**Comment by antagomir** [comment]
Two other things: 
- check the color palette is coloblind friendly (esp. red/green may cause trouble for some)
- I might like to see 2-3 options for the background color?

**Comment by TuomasBorman** [comment]
![mia_sticker9](https://user-images.githubusercontent.com/60338854/198839743-98050357-4f9b-4bdc-a015-7d2802014459.png)
Here is a version with wider arrows

I haven't printed this in real size, I should test that

1. Arrows are now red and green. They are not color-blind friendly, however, usually these colors are used to reflect positive vs negative effect. Also, the arrows are different whether they denote positive or negative effect, so I think these are ok?

2. The color of edge is Bioc green. The background is just random pinkish color. I try to finds some other combinations but I'm afraid that we are in limit of my expertise on this kind of stuff

**Comment by antagomir** [comment]
Yes test printing, that is essential to see.

Colorblind palette: it works as you explain but at the same time I think this is about positive communication at the level of this kind of details. Even if it is interpretable, we might like to show that we have paid attention.

To my eye the pink is somehow not matching well with the green edge. But that might be just me. Again, like to see if @nuorenarra might have some view here, perhaps even suggestion.

**Comment by nuorenarra** [comment]
I would recommend: 
light yellow background
Dark yellow (golden) edges
Max 3 bacteria, perhaps black, white and grey
Very thick arrows between them, positive marked as bright red, negative as bright blue (this is also common in ecological network plots i think)

Something like this... (just a sketch:)
![mialogo?](https://user-images.githubusercontent.com/77113596/198853920-25fbba0a-a08a-47a0-80d8-3336684bf2c2.png)

**Comment by antagomir** [comment]
Great stuff both :-D 

However for arrows I would still keep the the different types of arrows as Tuomas has.

Red+blue is good for arrows.

I agree with max 3 species.

Border and background colour: I do not have real opinion, just that the pink bg I somehow didn't fancy. 

Tuomas sorry for all the hassle.. but I think we are converging. Any chance for yet one more version based on all these exchanges?

**Comment by TuomasBorman** [comment]
I also like this version with fewer bacteria; yes, we are getting closer...

I like the wider edge, but it is not possible to do that wide with hexSticker (all the tips/edges get rounded)



1
![mia_sticker11](https://user-images.githubusercontent.com/60338854/198886647-0efee325-4c76-40f7-b51b-817b02b441a1.png)

2

![mia_sticker12](https://user-images.githubusercontent.com/60338854/198886652-444eb680-ff68-476d-9639-79d92edda3e1.png)

3


![mia_sticker13](https://user-images.githubusercontent.com/60338854/198886658-4f450dc8-30f4-4cbb-847c-d0c1fb38ed6c.png)

4
![mia_sticker14](https://user-images.githubusercontent.com/60338854/198887066-b1ef2540-6b73-43dc-906d-4bf0f23b2b5d.png)

5

![mia_sticker15](https://user-images.githubusercontent.com/60338854/198887072-677221b7-16b9-4c28-9ac2-dbec9d61eb49.png)

I think 2 is the best one

**Comment by antagomir** [comment]
Yep 2 is quite nice!

**Comment by TuomasBorman** [comment]
![mia_sticker](https://user-images.githubusercontent.com/60338854/200614733-8e683397-3df7-45ff-9c83-4839418ae98d.png)

We have a winner?

**Comment by antagomir** [comment]
It's awesome :1st_place_medal:

**Comment by nuorenarra** [comment]
AMAZING!!!

**Comment by TuomasBorman** [comment]
1. [Sticker with modifiable file](https://github.com/microbiome/outreach/tree/main/figures)
2. [mia](https://github.com/microbiome/mia/pull/323)
3. [miaViz](https://github.com/microbiome/miaViz/pull/61)
4. [https://microbiome.github.io/](https://microbiome.github.io/)
5. [miaSim](https://github.com/microbiome/miaSim/pull/55)
6. [miaTime](https://github.com/microbiome/miaTime/pull/60)
7. [OMA](https://microbiome.github.io/OMA/)

(+ All these have sticker in their readme also)

**Comment by antagomir** [comment]
I would also say that the mia can refer not only to that R package, but to the whole mia family of packages. Then we do not necessarily need a separate logo for each package? 

OMA might deserve its own logo.

**Comment by TuomasBorman** [comment]
Yes, mia could refer to all mia* packages

OMA: hmm, that's good point. mia is in key role but still OMA is its own thing... (and it does not have "mia" in its name)

**Comment by antagomir** [comment]
- - but we can consider that later. No hurry imo.
