### ISSUE TITLE
batch effects

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#31]
Batch comparison and correction for large-scale studies.  It would be also useful for identifying additional reagent contaminants in low biomass samples (proposed by SM)

**Comment by FelixErnst** [comment]
Can you provide more details on what you had in mind?

**Comment by antagomir** [comment]
I got a request online to add such features, and added it here for discussion. This is not a straightforward "function" to add. Might work as an example case study in MiaBook but not sure if this is feasible to mia in the short term at least.

**Comment by FelixErnst** [comment]
I have read up on it. There is a new package, `corral`, which deals with batch correction. From the RNA-seq world additional methods are available as well. Maybe this should be a chapter in `MiaBook`?

**Comment by antagomir** [comment]
Batch correction is a relevant topic, and should be cited in MiaBook at least and a dedicated chapter might be justified. This is not a core topic in my opinion, however. It could also be a subsection in a broader section about biases and quality control.

**Comment by FelixErnst** [comment]
So what is the issue for mia?

Is there something, which you think needs to be implemented? Otherweise I would move the issue to MiaBook

**Comment by antagomir** [comment]
I agree moving this to MiaBook. It also does not make sense to try implementing all possible methodologies in a single R pkg like mia. The book is the correct place to discuss the different problems and solutions.

**Comment by microsud** [comment]
Technical Bias and Quality Control section would indeed be important. 
First we need to find the right example datasets for:
- Contaminants  
- Batch correction   
- Absolute versus Relative Abundances

**Comment by FelixErnst** [comment]
I can omly transfer the issue within a Namespace. I will close it here and open another on MiaBook
