### ISSUE TITLE
agglomerateByRank: NA lead to NA

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/mia#318]
If there is at least one NA in values that are summed-up together, the resulting value will be NA (even when na.rm=T is used). 

--> add na.rm option to summation

```
library(mia)
data("GlobalPatterns")
tse <- GlobalPatterns

assay(tse)[1,1] <- NA

tse <- agglomerateByRank(tse, "Kingdom")

assay(tse)
```

**Comment by TuomasBorman** [comment]
sumCountsAcrossFeatures does not have na.rm option. Converting NAs to 0 would be ok for counts but not for certain assays...

We have to think about how to proceed with this. Updating examples/documentation might be one option

**Comment by antagomir** [comment]
I think the traditional answer from FE would be that the user is responsible. That might be a good solution, if documentation is clear. If this is meant to be used with non-negative assays, then a warning could be thrown when assay contains negative values.
