### ISSUE TITLE
implement estimateEvenness() ?

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#32]
Specific _evenness_ indices exist. Should we implement a separate `estimateEvenness` function, or provide these as an option in the generic `estimateAlphaDiversity` function? We could transfer Camargo, Simpson, Pielou, Evar, and Bulla evenness indices e.g. from [microbiome](https://github.com/microbiome/microbiome/blob/master/R/evenness.R).

**Comment by FelixErnst** [comment]
issue double posted?

**Comment by antagomir** [comment]
Oh - I got some error and had to repost. Closing this one now.
