### ISSUE TITLE
mergeSEs: merge all shared assays

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/mia#322]
Currently, it is possible to merge only one assay. It would be useful to allow merging of all shared assays (or multiple assays specified by user)

**Comment by antagomir** [comment]
Yes. 

However if this is very easy to achieve with some `lapply` type command across assay names, it is worth considering if added complexity in the function is warranted.

However, the assay name could easily be a vector of names (or just "all"). That would make sense.
