### ISSUE TITLE
mergeSEs: same variables but different type leads to an error

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/mia#326]
If objects have equally named variables but the data type differs (continuous age or categorical age), the variable cannot be merged together. This lead to an error

```
data("GlobalPatterns")
tse <- GlobalPatterns

tse1 <- tse

colData(tse)$SampleType <- 1

mergeSEs(tse, tse1)

```

How to fix this? Check if their type is the same. If not --> warning and rename (e.g. Age_character)

**Comment by antagomir** [comment]
Warning + rename would be a good solution I think. 

Warning could include suggested solution (to rename one of the variables or convert them into the same type).
