### ISSUE TITLE
Implement estimateEvenness?

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#33]
Specific _evenness_ indices exist. Should we implement a separate `estimateEvenness` function, or provide these as an option in the generic `estimateAlphaDiversity` function? We could transfer Camargo, Simpson, Pielou, Evar, and Bulla evenness indices e.g. from [microbiome](https://github.com/microbiome/microbiome/blob/master/R/evenness.R).

**Comment by FelixErnst** [comment]
This is next on my agenda. A few questions for that:

- The data should end up saved in the `colData` am I right?
- How computationally expensive are these? Should they be done at the same time or individually?

Thanks for any hints/tips

@microsud

**Comment by antagomir** [comment]
This should be done in the same way than we already implemented `estimateDiversity` and `estimateDominance`. For consistency.

These are not particularly expensive computationally and can be done at the same time (by default) I think.

**Comment by microsud** [comment]
In addition to Leo's comments:

> * The data should end up saved in the `colData` am I right?
`YES`
> * How computationally expensive are these? Should they be done at the same time or individually?
```
library(microbiome)
data("GlobalPatterns")
start_time <- Sys.time()
ev_test <- evenness(GlobalPatterns)
end_time <- Sys.time()
end_time - start_time
```
```FOR Global patterns with microbiome::evenness() it took 8.95 secs on a 
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363) 
8GB RAM 
```


EDIT: It calculated five indices here (camargo,pielou,simpson,evar,bulla) in one go... Took 8.9 secs

**Comment by FelixErnst** [comment]
@antagomir 

I found the following code snippet for some of the indices (`bulla` for example):
```
if (!zeroes) {
  x[x > 0]
}
```

What is expected to happen here, if zeroes is FALSE?

**Comment by antagomir** [comment]
Aah.. I checked now and as far as I can see, this should not be relevant for the (included) evenness indices. There are some other ecological indices where excluding zeroes would have some effect. From this I think it safe to leave out, we can add it later rather easily if needs arise.

**Comment by FelixErnst** [comment]
ca237db
