### ISSUE TITLE
loadFrom* documentation

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#332]
The function `loadFromBiom` has outdated example section:

- refers to `se` (not `tse`) as function output, although the function seems to return TreeSE
- converts SE to TreeSE although the object is already SE before the conversion

Suggestion: fix this and check other functions for similar issue.

This is the problematic example:

```
   if(requireNamespace("biomformat")) {
       library(biomformat)
       # load from file
       rich_dense_file  = system.file("extdata", "rich_dense_otu_table.biom",
                                      package = "biomformat")
       se <- loadFromBiom(rich_dense_file, removeTaxaPrefixes = TRUE)
     
       # load from object
       x1 <- biomformat::read_biom(rich_dense_file)
       se <- makeTreeSEFromBiom(x1)
       # Convert SE to TreeSE
       tse <- as(se, "TreeSummarizedExperiment")
       tse
     }

```

**Comment by kakonodia** [comment]
Hello @antagomir 
i would like to work on this issue 
would you assign it to me ?

**Comment by antagomir** [comment]
Would be great if you can check the other functions / R files for the same issue on the same go!

**Comment by antagomir** [comment]
Hi @kakonodia are you still taking this one?

**Comment by TuomasBorman** [comment]
This is already done @RiboRings ?

**Comment by RiboRings** [comment]
Hi! Yes, this is done.
