### ISSUE TITLE
Cannot load from metaphlan

### ISSUE THREAD

**Issue by marcelladane** [microbiome/mia#333]
Hello, I am trying to use the function "loadFromMetaphlan" mentioned in the tutorial.
But the function doesn't seem to be implemented. 

Can you please fix it? 
Otherwise, to use shotgun metagenomic data, I would need to first convert the metaphlan to a phyloseq. Is that correct?

Thank you.

**Comment by antagomir** [comment]
Hi! This function is (or should be) implemented in the latest versions of mia, I just confirmed.

Can you check your version of mia (e.g. R `sessionInfo()`)?

Latest Bioc devel version installs with this (although this functionality is in the current release as well): 
BiocManager::install("mia", version="devel")

Edit: if you get this working, there is no need to go through via phyloseq route but you can load directly to TreeSE.

**Comment by marcelladane** [comment]
Hello, I used the Bioconductor, and the version is 1.2.7 (it was installed yesterday).

**Comment by antagomir** [comment]
Hi - the current Bioc release version is [1.6.0](https://www.bioconductor.org/packages/release/bioc/html/mia.html) and the Bioc development version is [1.7.0](https://www.bioconductor.org/packages/devel/bioc/html/mia.html); the very latest bleeding edge development version in Github is [1.7.4](https://github.com/microbiome/mia). 

It seems that you are having an outdated version for some reason.

We can try to troubleshoot that if you provide the output of `sessionInfo()` in R and the exact installation command.

Or you can try to install the latest version from Github with:
remotes::install_github("microbiome/mia")

However Bioc installation might be more stable with dependencies, it should install with 
`BiocManager::install("mia", version="devel")`

but if you tried that already, then I would next check which R version you are using (`R.Version()`)

**Comment by marcelladane** [comment]
Hey, I managed to install the 1.7.4 using the install_github.

Thank you very much. =)

**Comment by antagomir** [comment]
Great,all feedback is very welcome :)
