### ISSUE TITLE
Error in readQZA(featureTableFile) : could not find function "readQZA"

### ISSUE THREAD

**Issue by IshtiakRashid** [microbiome/mia#335]
I was trying to create a TreeSummarizedExperiment object but while adding this: 

assay <- readQZA(featureTableFile)

i found error: Error in readQZA(featureTableFile) : could not find function "readQZA"

**Comment by antagomir** [comment]
You may have an old version of the mia package.

Can you try `remotes::install_github("microbiome/mia")` ,then restart and load the package. 

If the problem persist, copypaste here the output of R `sessionInfo()` command.

**Comment by IshtiakRashid** [comment]
Dear Leo,

Thanks for your suggestion & it worked!

Best
