### ISSUE TITLE
adonis2/dbRDA/permanova automation wrappers?

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#358]
The OMA section "Testing differences in community composition between sample groups" currently shows how to do dbRDA/PERMANOVA with vegan::adonis2. It might be beneficial to standardize this for TreeSE objects to support reporting (tables) and visualization. Not sure, however, if benefits outweight the costs. To discuss & consider.

**Comment by TuomasBorman** [comment]
Done.
