### ISSUE TITLE
New demo data set

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#368]
Add new data set in mia.

Clone mia R package
https://github.com/microbiome/mia

Test the following:
`devtools::test()`
`devtools::build()`
`devtools::run_examples()`

Use the data from [Tengeler et al. 2020](https://github.com/microbiome/course_2022_radboud/tree/main/data/Tengeler2020)

Save the TreeSummarizedExperiment data set in rds format in:
https://github.com/microbiome/mia/blob/master/data/

Document the data set here, include reference to the original publication:
https://github.com/microbiome/mia/blob/master/R/mia.R
then run `devtools::document()`

Test that the data set can be loaded after 
`devtools::load_all()` or `devtools::install()` with
`data(Tengeler2020)`

Open new PR to mia with these changes.

Remember to store the clean source code that converts the original data into TreeSE.

**Comment by antagomir** [comment]
The Wickham & Bryan online resource can help with building R packages and adding data: [R packages](https://r-pkgs.org/data.html)

**Comment by antagomir** [comment]
Check if the above script import can be simplified.

In particular, check if you could use directly the new function
https://microbiome.github.io/mia/reference/makeTreeSEFromBiom.html

**Comment by 0xMuluh** [comment]
I am raising a quick PR for new demo dataset but unable to get a good description of the Tengeler2020 dataset. Any pointers?

**Comment by antagomir** [comment]
Hmm picking key points from the abstract of data description of the original publication?
