### ISSUE TITLE
Naming of importers

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/mia#371]
As discussed in here https://github.com/microbiome/mia/pull/370, the naming of importers is not unified.

`load*` should create `TreeSE` from provided file path (e.g., path to BIOM file).
`make*` should create `TreeSE` from provided object (e.g. BIOM object).

Check that importers follow this convention, and improve the documentation accordingly.

**Comment by antagomir** [comment]
Could we close this already?

**Comment by 0xMuluh** [comment]
We have now import* and convert*. This issue is stale.
