### ISSUE TITLE
Unify documentation

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/mia#372]
To polish the package, the documentation should be unified (this applies also to packages). This improves the readability and overall quality of the packages.

These listed things came to my mind, please extend it if you come up with other things

1. How we tag classes (\code{} or other). Discussed in here https://github.com/microbiome/mia/pull/370
2. Parameters. Some parameters are like `thisIsParameter`, others like `this.is.parameter`. We agreed to use the latter.
3. The error messages of input checks are not unified. If parameters `A` and `B` require a boolean value, the error message should be the same for them (e.g., "'A' must be a boolean value").
4. Similar to point 3. The parameter description should be unified. First give the expected class then explain what the parameter does.

**Comment by antagomir** [comment]
@Daenarys8 is this ready?

**Comment by antagomir** [comment]
Also related to #585
