### ISSUE TITLE
clusterFeatures wrapper

### ISSUE THREAD

**Issue by Basil-Courbayre-Dussau** [microbiome/mia#379]
So far in mia there's a function to cluster features or samples, but for the features, it's common to do a CLR-transformation before the clustering. This issue is to see whether a wrapper for the CLR-transform + clustering is useful or not.

Here's an example to do feature clustering as of now:
```R
tse <- transformCounts(tse, assay.type = "counts", method = "clr", pseudocount = 1, MARGIN = "features")
tse <- cluster(tse, assay.type = "clr", KMeansParam(centers = 2), MARGIN = "features")
```

With a wrapper, it could look like this:
```R
tse <- clusterFeatures(tse, assay.type = "counts", method = "clr", pseudocount = 1, KMeansParam(centers = 2))
```

I think the wrapper can be handy because it avoids to repeat basic information (x and MARGIN params). But I also think that it would take a lot of parameters which may be overwhelming to do two basic operations.

What do you think @antagomir @TuomasBorman ?

**Comment by TuomasBorman** [comment]
Thanks!

Hmmm, I can see the benefit. However, there are some things to consider... For example, this adds maintenance workload, makes things little bit less transparent, and additionally clr transformation is usual transformation so it would be done anyways, I guess...

So in my opinion, the benefits does not exceed the disadvantages

**Comment by antagomir** [comment]
Yep I tend to agree that it is not worth a new function.

In the first example, are you missing specification of `assay.type`?

The example could show how to explicitly name that new field in `rowData`.

Add new example in OMA ch. 6.3:
- switch to using hclust with ward.D2 method in the example (default recommendation)
- show how to print histogram showing the resulting CAG size distribution (with ggplot)
- additionally show how to use `mergeRows` to collapse the data to the identified CAGs

**Comment by Basil-Courbayre-Dussau** [comment]
I did forget assay.type yes.
I'll add that to OMA.
