### ISSUE TITLE
Metaphlan & counts

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#383]
The metaphlan pipeline is providing only the relative abundance assay, and not counts. This is sometimes inconvenient for various standard metagenomic analysis methods and workflows that expect counts.

The curatedMetagenomicData resource has solved this as follows (see `?curatedMetagenomicData::curatedMetagenomicData`)

> Finally, if a ‘relative_abundance’ resource is requested and ‘counts = TRUE’, relative abundance proportions will be multiplied by read depth and rounded to the nearest integer.

It could be useful if mia provided such functionality, at least for metaphlan import and potentially more broadly. Then the users could always have access to "counts" assay and more readily use standard tools.

**Comment by changrong1023** [comment]
> 

https://github.com/biobakery/MetaPhlAn/blob/master/metaphlan/metaphlan.py#L281

**Comment by antagomir** [comment]
Thanks! Indeed the ideal solution is to export counts from Metaphlan. 

In my experience this very often is not readily available for the analyst, after the data has been passed on. 

We can either 

1. stick to only those outputs that Metaphlan itself generates, and expect that users will make sure the pipeline is run including the preferred options; or 
2. add some helper functions while making sure that all is in line with the usual conventions of Metaphlan.
3. expect that users will themselves troubleshoot what is needed.


These both have their pros & cons. I like more option (1) but then in practice I frequently get questions from applied scientists who received the data from somewhere, and have found out they only have the relative abundance data available for Metaphlan. It does not always seem feasible for them (in a reasonable time frame) to go back and ask to rerun pipelines with new settings, then option (2) could help. The option (3) is where we are currently.

**Comment by antagomir** [comment]
It could be one of the transformation options. So we only have transformations for counts (in transformCounts). 

Why not a more generic function `transformAssays`? The name `transformCounts` is also misleading since it allows transformations also for other than count assays.

**Comment by antagomir** [comment]
Importantly, see discussion in #4 and in particular this one:

"Just a really quick plug advocating against the idea of rescaling relative abundances (obtained from shotgun or amplicon) by absolute abundances. The reasons for the strong no are here (https://elifesciences.org/articles/46923) and an alternative is here (https://www.biorxiv.org/content/10.1101/761486v1)."

**Comment by TuomasBorman** [comment]
It seems that this is not that straight forward. The default option of metaphlan is relative abundances with some kind of normalization. https://forum.biobakery.org/t/metaphlan3-relative-abundance/564

We could have metagenomics chapter in OMA which describes preferred options without overlapping the metaphlan documentation.

**Comment by antagomir** [comment]
It seems that this issue can be closed. We can open a new one in OMA later if necessary.
