### ISSUE TITLE
agglomerateByRank issue

### ISSUE THREAD

**Issue by flappysmurf** [microbiome/mia#385]
agglomerateByRank (version 1.8) always returns the following error even though I run its examples :(

Error in set_grid_context(X[[1]], X[[2]]) : 
  argument "current_viewport" is missing, with no default

**Comment by TuomasBorman** [comment]
Hello!

Does it work now? There was an issue in dependent package, and they fixed it

-Tuomas

**Comment by flappysmurf** [comment]
Thank you so much! It works!
