### ISSUE TITLE
agglomerateByRank returns only species name not genus.species 

### ISSUE THREAD

**Issue by microsud** [microbiome/mia#39]
@FelixErnst and @antagomir 

Currently, we have Species information in rowData. While it is logical to have only species name, biological is best interpreted with genus and species name. e.g. *Genus.species* like _Bacteroides.uniformis_

```
library(mia) # v0.98.22
library(microbiomeDataSets)
tse <- SilvermanAGutData()
tse.sp <- agglomerateByRank(tse, "Species", na.rm = T)
getTaxonomyLabels(tse.sp[1:3,])
##### Output #####
# only species names are returned as output. 
[1] "uniformis" "ulcerans"  "piscolens"
```

Also, when `na.rm = F` in `agglomerateByRank()`  we get `Species:uniformis` as row.name/rowID
```
tse.sp.2 <- agglomerateByRank(tse, "Species", na.rm = F)
rowdt <- rowData(tse.sp.2)
rowdt[1:3,3:7]

##### Output #####
DataFrame with 3 rows and 5 columns
                        Class         Order         Family       Genus     Species
                  <character>   <character>    <character> <character> <character>
Genus:Alistipes   Bacteroidia Bacteroidales  Rikenellaceae   Alistipes          NA
Species:uniformis Bacteroidia Bacteroidales Bacteroidaceae Bacteroides   uniformis
Genus:Bacteroides Bacteroidia Bacteroidales Bacteroidaceae Bacteroides          NA

```

So would it be an idea to return *Genus.species* because at the moment species is the lowest rank we have? Even in future if there are strain-level profiling e.g. with long read sequencing or WGS, this can be extended to *Genus.species.strain* 

EDIT: https://github.com/fionarhuang/TreeSummarizedExperiment/issues/59  linked to this on `TreeSummarizedExperiment`

**Comment by antagomir** [comment]
Something like this is indeed very useful in practice.

**Comment by FelixErnst** [comment]
So I don't get this either. What doesn't work currently? 

I need an example to understand what kind of output and behavior you would expect.

**Comment by microsud** [comment]
Species names are not always unique. These can be shared between diverse genera. This is also at genus level with same genus name classified in diff families, many more complexities regarding polyphyletic nature of certain taxa. But for now Genus.Species at least can be taken care of.
E.g. 
*Methanothrix soehngenii* and *Anaerobutyricum soehngenii* now if we return only species name *soehngenii* it's not useful. 

Therefore, I think returning only species names is not the ideal behaviour. The values returned by `agglomerateByRank()` at species level (when available) should return genus.species combination and not just species name.

**Comment by FelixErnst** [comment]
Well this is something I didn't want to make as the default, since the solution to generating the result when need is a oneliner:

`rownames(x)[!is.na(rowData(x)$Species)] <- paste(rowData(x)$Genus,rowData(x)$Species)[!is.na(rowData(x)$Species)]`

Why introduce another option, which has to be tracked through multiple functions, which can be solved by any user how the like that easily?

**Comment by microsud** [comment]
This is a very software developer perspective and not user oriented with assumptions of required level of training prior to using the tool. 
For microbiologists (or any taxonomists), it is a default setting in the brain to use genus.species.
If it is a big task, we make this one liner and other similar operations clear in the `miaBook` 😉

**Comment by FelixErnst** [comment]
That might be the case. However, I would argue, that anyone using `ggplot` knows how to paste together a string. The other option would be introduce a special argument, just in case species information is available, which than would have to be looked up in the man page in any event. The ROI doesn't look good in my opinion, or do you have a catchy name for such an argument, which doesn't require more than 2 or 3 words? `mergeGenusSpecies` is the shortest I could come up with and that is just a weird non-descriptive name, which does not work without the man page.

The `MiaBook` is the best place to put these things.

**Comment by microsud** [comment]
Your suggestions seems a good one. 
If a generic one is needed, it can be  `mergeRankLabels` ?

**Comment by FelixErnst** [comment]
To unspecific. It only has meaning for Genus and Species. Any if you want to provide a function, you have to take into account the reality, that many datasets contain the genus-species combination in the species column. See `GlobalPatterns` for example.

That are few `ifs`, which will end up being the reason for a few issues opened here on GitHub, because the one special format of a user was not taken into account. And thats without all the qiime data with their nice little prefixes.

**Comment by microsud** [comment]
Okay. I was thinking from an end user perspective. With `microbiome` pkg we always try our best to empower the user with tutorials for data handling outside of the pkg functionality. It was a good idea to have the `MiaBook` for this and other related practical issues that might arise after we have active users for the `TSE` n `mia` ecosystem.

**Comment by antagomir** [comment]
Yes for MiaBook examples. But I also like to add that there might indeed be some demand for easy and intuitive shortcuts. Whether those should go to mia or some other package, that's a different question.

**Comment by fionarhuang** [comment]
@microsud For the closed issue submitted in TSE,  if I understand it correctly, the main feature required was to store some rowData separately from the taxonomy table. My suggestion would be to store the so-called `new_slot`  (a data frame) as a column of the `row_data` instead of really creating a new slot. In this way, different rownames are allowed. The subsetting works and the access to the new_slot is quite easy.

```
> row_data <- DataFrame(Genus = LETTERS[1:10],
+                       Species = letters[1:10])
> rownames(row_data) <- paste0("row", 1:10)
> # different rownames are allowed in the new slot
> new_slot <- DataFrame(var1 = 1:10,
+                       var2 = "A")
> rownames(new_slot) <- paste0("new", 1:10)
> row_data$new_slot <- new_slot
> row_data
DataFrame with 10 rows and 3 columns
            Genus     Species    new_slot
      <character> <character> <DataFrame>
row1            A           a         1:A
row2            B           b         2:A
row3            C           c         3:A
row4            D           d         4:A
row5            E           e         5:A
row6            F           f         6:A
row7            G           g         7:A
row8            H           h         8:A
row9            I           i         9:A
row10           J           j        10:A
> # easy to access
> row_data$new_slot
DataFrame with 10 rows and 2 columns
           var1        var2
      <integer> <character>
new1          1           A
new2          2           A
new3          3           A
new4          4           A
new5          5           A
new6          6           A
new7          7           A
new8          8           A
new9          9           A
new10        10           A
> # subset works for both row_data and new_slot
> row_data[1:4, ]
DataFrame with 4 rows and 3 columns
           Genus     Species    new_slot
     <character> <character> <DataFrame>
row1           A           a         1:A
row2           B           b         2:A
row3           C           c         3:A
row4           D           d         4:A
```

**Comment by microsud** [comment]
Hi @fionarhuang - Apologies for closing the issue before you could comment on it. Yes you are right and your solution seems to be a good one. Was not aware of the possibility to store Data frame as column in `SE/TSE`. Thanks!
