### ISSUE TITLE
Deprecate mergeRows/mergeCols

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#392]
Add an alias as follows

- mergeRows -> mergeFeatures
- mergeCols -> mergeSamples

For an example on how to do this, check a similar case for instance in getTopTaxa vs. getTopFeatures.

Deprecate mergeRows/mergeCols with a warning that they have been replaced with another name. See other deprecated functions for an example on how to deprecate an argument name.

Also remember to update manpage examples, vignettes, unit tests in ./tests/ 

Open an [issue to OMA](https://github.com/microbiome/OMA/issues) to make corresponding changes there after merging this.

**Comment by antagomir** [comment]
Suggesting to add some more renaming in this PR as follows:

- mergeCols -> mergeSamples
- mergeRows -> mergeFeatures
- agglomerateByRank -> mergeFeaturesByRank (logical to use similar naming in both functions)
- agglomerateByPrevalence -> mergeFeaturesByPrevalence (same logic)

Some background discussion in #389

**Comment by TuomasBorman** [comment]
This is done I believe @ake123 ?
