### ISSUE TITLE
Rename transformCounts to transformAssay

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#394]
The `transformCounts` is somewhat misleading name bc this function allows transformation for any assay (not just counts assay). 

Let us change the name to `transformAssay` and deprecate `transformCounts`.

Remember to update
- unit tests
- manpage
- vignettes
- oma
- miaViz
- miaSim
- miaTime

**Comment by antagomir** [comment]
Merged - remember to update the other resources as well.

It might be easiest to do this after we first updated this mia version to Bioconductor devel; we have many updates recently and it is good to bring them there for further testing (if not done already) ping @TuomasBorman when the time allows?

**Comment by TuomasBorman** [comment]
Bioc devel should be updated in couple of days

**Comment by antagomir** [comment]
Still on thing to fix.

Load example data first:

```
library(mia)
data(GlobalPatterns, package="mia")
```


Then running `transformCounts(GlobalPatterns)` gives:
> Error in transformCounts(GlobalPatterns) : 
>   could not find function "transformCounts"

-> This means that the `transformCounts` has not been deprecated properly. The old function name should continue working during some transition period. Looking at the code, [line 236 onwards](https://github.com/microbiome/mia/blob/master/R/transformCounts.R#L236) it seems that this actually should throw a warning but work. Investigate why it throws an error instead or warning. I also think that line 237 should have `.Deprecate` message instead of `warning`?

**Comment by antagomir** [comment]
@ake123 can you check?

**Comment by TuomasBorman** [comment]
This is also done @ake123 ? And this and other functions are deprecated properly? (Old ones are still available but function gives deprecation message)

**Comment by ake123** [comment]
it was done!

**Comment by antagomir** [comment]
can you close issues that are ready? after checking that deprecations are OK in mia, and function names corrected also in miaViz, miaTime, miaSim, OMA (if used in those)

**Comment by ake123** [comment]
All fixed!
