### ISSUE TITLE
 Enabling rowData variables in mergeRow

### ISSUE THREAD

**Issue by 0xMuluh** [microbiome/mia#397]
see: issue: #389 
We discussed about enabling rowData variables in mergeRows. Currently, the groups must be fed as a vector (f parameter) but it would be nice to be able to specify the grouping variable directly from rowData as a column name. (Same for mergeCols).

**Comment by antagomir** [comment]
Agreed.

**Comment by TuomasBorman** [comment]
Can you @Daenarys8 create a draft for this?

**Comment by 0xMuluh** [comment]
definitely.

**Comment by antagomir** [comment]
Closed via #408
