### ISSUE TITLE
merge by variable name

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#400]
Enable rowData variables in mergeRows. 

Currently, the groups must be fed as a vector (f parameter) but it would be nice to be able to specify the grouping variable directly from rowData as a column name. 

Same then for mergeCols.

Ping @Daenarys8 

For some background discussion see #389

**Comment by 0xMuluh** [comment]
okay noted. I was a bit confused which to do first, the variable change or the deprecation. I will do the deprecation then do a separate pr for the variable change.

**Comment by antagomir** [comment]
Right, it is a bit in the air. Sounds good.

**Comment by antagomir** [comment]
Closed via #408
