### ISSUE TITLE
renaming makeTreeSummarizedExperimentFromqiime2

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#41]
This could be renamed as makeTreeSummarizedExperimentFromQIIME2 since QIIME2 is also otherwise typically written in capital letters.?

**Comment by FelixErnst** [comment]
@yiluheihei ?

**Comment by yiluheihei** [comment]
absolutely agree

**Comment by FelixErnst** [comment]
Can you prepare a PR?

**Comment by yiluheihei** [comment]
OK, no problem.
