### ISSUE TITLE
Rarefaction as optional strategy for alpha diversity

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#417]
Ref: Pat Schloss' [recent analyses](https://www.biorxiv.org/content/10.1101/2023.06.23.546313v1.full.pdf) on rarefaction in alpha & beta diversity. This addressess well some of the long debates and controversies surrounding rarefaction in microbial ecology.

Based on this I tend to think that rarefaction should be provided as an option for alpha diversity calculations. 

Here rarefaction refers to averaging alpha diversity estimates across many random rarifications (100x and 1000x are used in the preprint). This makes most difference in less diverse and low abundance environments but may influence also more rich ecosystems (see the preprint).

Options:
- write an apply/do loop around estimateDiversity and just provide that as an example in mia vignette / OMA
- provide rarefaction as an option in estimateDiversity directly (including user defined arguments for the number of rarification rounds, and for the read count threshold with some automated default such as the smallest read count among samples)

I am in favour of the second option.

Note:
- we have estimateDiversity, estimateRichness, estimateDominance etc.; these all should be updated
- or we can consider combining them into a single estimateAlpha function to simplify procedures and maintenance (perhaps a separate issue to deal with first to minimze extra work)

**Comment by ChouaibB** [comment]
I agree with the second option and then still show an example at vignette and/or OMA for example.
Would for instance `estimateAlphaWithRarefaction` be a better naming? upon which the function would take as argument the functions:  estimateDiversity, estimateRichness, estimateDominance?

**Comment by antagomir** [comment]
Lets do: "estimateAlpha" at least for now
