### ISSUE TITLE
could not find function "transformAssay"

### ISSUE THREAD

**Issue by gomong** [microbiome/mia#421]
Hi. I'm new to use mia package.
And I have some problems to start a project.

While I was trying to start with a tutorial and my data samples, following error came out.

> tse <- transformAssay(tse, assay.type = "counts", method = "relabundance")
Error in transformAssay(tse, assay.type = "counts", method = "relabundance") : 
  could not find function "transformAssay"

> tse <- mia::transformAssay(tse, assay.type = "counts", method = "relabundance")
Error: 'transformAssay' is not an exported object from 'namespace:mia'

I first thought it came from missing dependencies while package installation.
Even though I reinstall all the packages, this error is continued.

Can you give me any advice on how to solve theproblem?

**Comment by gomong** [comment]
I figured out.

I have used Bioconductor version 3.17 and mia version 1.8.0 but now I updated them to ver 3.18 and ver 1.9.11, respectively. And no more same error comes out.

They are still for developers, so you may be supposed to use codes like `version="devel"`.

**Comment by antagomir** [comment]
We noticed the same last week, we should clarify the documentation in that regard. Hopefully this will also stabilize soon.

In the meanwhile, the mia installation instructions in OMA should probably recommend using the Bioconductor "devel" version, and currently not suggest the "release" version at all. Let us add that.

**Comment by antagomir** [comment]
We noticed the same last week, we should clarify the documentation in that regard. Hopefully this will also stabilize soon.

In the meanwhile, the mia installation instructions in OMA should probably recommend using the Bioconductor "devel" version, and currently not suggest the "release" version at all. Let us implement that.

**Comment by gutmicrobe** [comment]
Is there any approximate time for users to expect the naming of key functions in 'miaverse' to become stable?

**Comment by antagomir** [comment]
We should aim to stabilize fast. Recently there was more active thinking of the names but this would benefit from a more systematic approach and look at the function names in order to provide a more "final" version. 

In general, looking at a Bioc half-year release cycle would be a good target in principle.

However, old names should continue working for quite some time with the deprecation mechanism.
