### ISSUE TITLE
Update mia-datasets docs

### ISSUE THREAD

**Issue by RiboRings** [microbiome/mia#427]
Hi! I am updating the [mia-datasets vignettes](https://microbiome.github.io/mia/reference/mia-datasets.html) and I am considering some options.

How about having one main general page that links to a separate page for each dataset? This way info on the datasets doesn't get confused with one another.

Let me know what you think. I'm working on it.

**Comment by antagomir** [comment]
I also noticed that the website generated with mia 1.9.10 whereas the latest version in master is 1.9.11. The website should generate automatically and I [do not see any failures](https://github.com/microbiome/mia/actions/workflows/pages/pages-build-deployment). Would be good to make sure first that the website is up-to-date and vieweable version corresponds to the current code.

I agree that it is more clear to keep manpages separate for every data set.

The file `pkgdown/_pkgdown.yml` seems to be used somehow, can you check if this is up-to-date also more generally and if this could be used to solve this. It now only has this for data:

```
- subtitle: Datasets
- contents:
  - GlobalPatterns
```

How would the page render if other data sets were added here?

Or perhaps mixing of the different data informations can be solved by changeing `@name mia-datasets` in the beginning of each data set roxygen text into data set specific one, like `@name Tengeler2020 dataset`. Perhaps that already does the trick? Not sure which way is better, would be useful to check.
