### ISSUE TITLE
mia website outdated

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#428]
I noticed that [mia homepage](https://microbiome.github.io/mia/) is on version 1.9.10 although the current mia version is higher (1.9.11 as of now). This indicates that something in the automated GHA build has failed although I do not see such failure [in actions](https://github.com/microbiome/mia/actions/workflows/pages/pages-build-deployment). 

-> Check whether the automated build of website works in mia package or if not, how to fix.

The site can be locally build for testing purposes with:
`pkgdown::build_site("./")`

That also seems to fail. Perhaps the explanation lies there?

**Comment by ake123** [comment]
It looks like it has updated already!

**Comment by TuomasBorman** [comment]
Everything's good
