### ISSUE TITLE
Suggestion to remove `na.action` argument from `runRDA`

### ISSUE THREAD

**Issue by RiboRings** [microbiome/mia#432]
Hi!

What do you think about removing the `na.action` argument from `runRDA` and instead providing instructions in OMA how users can filter missing values themselves?

This could simplify the code of `runRDA` and prevent bugs due to differing dimensionality between tse and rda object.

**Comment by antagomir** [comment]
Sounds good to me at least. Should be fine when it is clear in the mia and OMA examples. Simplifying code is useful too.

**Comment by TuomasBorman** [comment]
That would lead subset of TreeSE which is not the optimal case. Currently, the output of runRDA includes all the samples (samples with missing values are added to vegan::rda result)

One option is to catch the na.action parameter and give more informal error message.

**Comment by antagomir** [comment]
@RiboRings could you check the status of this one, if we can handle & close the issue. This seems straightfwd.

**Comment by RiboRings** [comment]
Ok I'll have a look
