### ISSUE TITLE
Deprecation messages

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/mia#439]
It seems that deprecation messages occurs in wrong places. For example, `mergeFeaturesByRank` gives deprecation message about `agglomerateByRank`. Of course it should not.

There are also some other functions that use deprecated functions internally --> gives warning. Run tests and you will see all the warnings that must be removed (assuming that tests are using the latest naming scheme which they should).

**Comment by TuomasBorman** [comment]
@ake123 Do you have time to check this?

**Comment by TuomasBorman** [comment]
What is the status? Is everything done? @ake123

**Comment by ake123** [comment]
It's done!
