### ISSUE TITLE
subset functions and trees

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/mia#443]
It seems that subset functions do not have parameter for updating the `rowTree` (`mergeFeatureByRank` has...). Moreover, `agglomerateByPrevalence` seems to drop `rowTree` completely

--> check

**Comment by TuomasBorman** [comment]
`mergeFeatureByRank`'s `agglomerateTree` seems not to agglomerate the tree but rather create a new one from the agglomerated `rowData`

I think it should just drop those tips that are not present anymore

**Comment by antagomir** [comment]
@ake123 is this ready?

**Comment by ake123** [comment]
yes it's ready

**Comment by antagomir** [comment]
Can you close all issues that are ready?
