### ISSUE TITLE
Clean up the manpages

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#450]
The html manpages do not always render well, see e.g.
https://microbiome.github.io/mia/reference/getExperimentCrossAssociation.html

**Comment by 0xMuluh** [comment]
Do we have pending tasks to clean up rendering in manpages?

**Comment by antagomir** [comment]
Could you for instance browse through all reference pages in mia, miaViz, miaTime and see if you notice anything that could be easily improved / clarified? 

If examples throw warnings it might be good to either modify the example to get rid of warnings, or comment on why those warnings appear and show how to deal with them.

This task is secondary priority if more urgent tasks pop up.

**Comment by 0xMuluh** [comment]
Sure will take a look while pending feedback on some commits I pushed earlier.

**Comment by antagomir** [comment]
Status of this one @Daenarys8 ?

**Comment by 0xMuluh** [comment]
mia and  miaViz  are addressed in #603 and https://github.com/microbiome/miaViz/pull/140 respectively.
Will add a PR for miaTime.

**Comment by antagomir** [comment]
Ok can we close this one or better to keep open still?

**Comment by 0xMuluh** [comment]
I think we can close.

**Comment by antagomir** [comment]
Great. Please actively close all issues as they become ready.
