### ISSUE TITLE
Harmonizing documentation

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/mia#458]
Package documentation is not harmonized. For example, we describe boolean parameters in the parameter description as "must be a single boolean value" and "must be TRUE or FALSE". I think these should be harmonized in addition to other documentation as well (including error messages). This would make the documentation more clear and make it easier to follow the documentation.

This issue affects all the packages: mia, miaViz, miaSim, MGnifyR...

**Comment by antagomir** [comment]
Use the "@inheritParams" roxygen functionality for this.

**Comment by 0xMuluh** [comment]
ping #603

**Comment by antagomir** [comment]
Please close after the PR is merged.
