### ISSUE TITLE
makeTreeSummarizedExperimentFromQIIME2.R functions

### ISSUE THREAD

**Issue by exod1a** [microbiome/mia#46]
Hi
I have been trying to use the file "mia/R/makeTreeSummarizedExperimentFromQIIME2.R" at [https://github.com/FelixErnst/mia/blob/master/R/makeTreeSummarizedExperimentFromQIIME2.R](url) but I am having trouble with the functions that come from the "Modstrings" library including .is_a_bool, .is_non_empty_string, etc. I have downloaded the library using

`BiocManager::install("Modstrings")`
and loaded it as well as using

`library("Modstrings")`
confirmed that it is loaded in my RStudio using 

`search()` and it shows "package:Modstrings"
However, I continue to get the error message: 

Error in .is_a_bool(removeTaxaPrefixes) : could not find function ".is_a_bool"

and similarly for the other functions in the "Modstrings" library. Is there a fix for this?
Thanks

**Comment by FelixErnst** [comment]
Hi Chandler,

I am a bit confused, why you would even know about an internal function `.is_a_bool`. It is implemented in `mia` in the utils.R file.

I mean I am a bit flattered, that you found out, that the same ***internal*** function is also used in `Modstrings`, but that is coincidence.

From the limited information you gave us, my guess would be that you sourced the file with `source`, am I right? If that is the case, please install mia using `BiocManager::install("FelixErnst/mia")` and trash you R session, to avoid any conflict with the sourced functions.

For me to comment on this further, I would like to ask you to post a `sessionInfo` and also tell us how you installed the `mia` package from GitHub.

Felix

**Comment by exod1a** [comment]
Hi
I managed to install mia using `BiocManager::install("FelixErnst/mia")` and now it seems to work and the problem is with the files not the function
Thanks!
