### ISSUE TITLE
Rarified beta diversity calculations

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#463]
Would be nice to have beta diversity calculations with rarefaction, as described in [Pat Schloss recent preprint](https://www.biorxiv.org/content/10.1101/2023.06.23.546313v1).

Now, this can be achieved by using `vegan::avgdist` function as follows.

I am not sure if we need to create a new wrapper for this in mia or anything. Although it could be potentially simplified. But not much. 

Shall we just explain in OMA how it works? What do you think?

```
library(mia)
library(vegan)
library(scater)

data(GlobalPatterns)
tse <- GlobalPatterns
x <- assay(tse, "counts")

tse <- runMDS(tse, assay.type="counts",
                           ntop=nrow(GlobalPatterns), # runMDS option; set to total number of features in tse so that they are not filtered
                           FUN = avgdist, # Custom distance that includes rarefaction, from vegan package
                           sample=min(colSums(assay(tse, "counts"))), # rarefaction depth (min read count over samples)
			   distfun=vegdist,  # Use vegdist distance function
                           dmethod = "bray", # Bray-Curtis dissimilarity
			   iterations = 10, # 10x rarefaction for distance calculations should be fine			   
			   ) 

p <- scater::plotReducedDim(tse, "MDS")
print(p)
```

**Comment by antagomir** [comment]
Some things to do nevertheless:

1) Some additional tests would be useful to ensure that it works as expected; like sample=Inf would do no rarefaction and it should return the same result than just running the runMDS with corresponding vegdist without rarefaction as usually done (instead of avgdist that is used in the above example)

2) with iterations=1 it should also work that way

3) with more iterations the distances should converge rapidly to some stable mean


One potential issue with the above ready-made solution is that it does not allow using transformations since they need to be done after the rarefaction. But the `vegan::avgdist` has the `transf` argument and we can do.. 

```
# Define custom transformation function..
clr <- function (x) {
  vegan::decostand(x, method="clr", pseudocount=1)
}

# Here we also run transformation after rarefactions before calculating the distances..
tse <- runMDS(tse, assay.type="counts",
                           ntop=nrow(GlobalPatterns), # runMDS option; set to total number of features in tse so that they are not filtered
                           FUN = avgdist, # Custom distance that includes rarefaction, from vegan package
                           sample=min(colSums(assay(tse, "counts"))), # rarefaction depth (min read count over samples)
			   distfun=vegdist,  # Use vegdist distance function
                           dmethod = "euclidean", # dissimilarity
			   iterations = 10, # 10x rarefaction for distance calculations should be fine
			   transf=clr
			   ) 

# Check how it looks
p <- scater::plotReducedDim(tse, "MDS")
print(p)
```

For this latter example it would also essential to make some manual checks (or unit tests) that the outputs are really as expected. But this seems rather robust now.

**Comment by antagomir** [comment]
However I am not sure how to add such tests, in case this will be only included in OMA as an example. At least some quick manual tests to make sure it is used correctly in the example.

**Comment by antagomir** [comment]
If `calculateDistance` function is added back to mia, then rarefaction like here can be made optional part of that and tested properly.

**Comment by TuomasBorman** [comment]
I think that we could add calculateDistance back but it calculates only distances, not ordination, We could also do a wrapper for scater::runMDS --> the default function could be vegan::avgdist instead of base::dist function

**Comment by antagomir** [comment]
Yes both things could be useful.

Although I am not sure if it is worth wrapper if we could write `mia::runMDS()` instead of just `scater::runMDS(..., FUN=vegan::avgdist)`

**Comment by TuomasBorman** [comment]
Well, true. mia::runMDS() would be overkill

**Comment by antagomir** [comment]
@himmil when you have time you could check this, let's start with an OMA example, then consider if any new functionality (in mia) is really needed. Also good opportunity test if OMA contribution guidelines are easy to find and up-to-date :)

**Comment by antagomir** [comment]
Related to https://github.com/microbiome/OMA/issues/332

**Comment by antagomir** [comment]
Perhaps need to open a separate issue about opening `calculateDistance` back to mia, and that should include the said rarefaction option (for counts)

**Comment by antagomir** [comment]
Also be aware about the ready made rarification function that can be used https://github.com/microbiome/mia/pull/536

**Comment by antagomir** [comment]
OMA has [examples](https://microbiome.github.io/OMA/docs/devel/pages/beta_diversity.html#rarefaction-to-mitigate-impacts-of-uneven-sequencing-effort) on doing beta diversity with rarefaction now.

Making generic function for this is more complex because after rarefaction one usually makes also some transformation before calculating dissimilarities and then finally the ordination. Automating this multi-step process in a general case will require remarkable flexibility (-> maintenance burden).

One could consider a simple wrapper for special common cases, like:
- MDS with Bray-Curtis for compositional data
- PCA with Aitchison
- etc.

However, these might be better to re-evaluate again if they become more common choices.
