### ISSUE TITLE
consider removing set.seed() inside the functions

### ISSUE THREAD

**Issue by erawijantari** [microbiome/mia#468]
When I run BiocCheck::BiocCheck(), it was suggested to remove set.seed inside the functions, `subsampleCounts.R` has 1 line that set seed inside the functions (line 133)

**Comment by antagomir** [comment]
PR welcome.

**Comment by erawijantari** [comment]
Based on the suggestions here: https://support.bioconductor.org/p/110439/, I removed the set.seed() inside the function and specify that user can define seeds before applying subsampleCounts().
