### ISSUE TITLE
More layouts for plotAbundanceDensity

### ISSUE THREAD

**Issue by artur-sannikov** [microbiome/mia#481]
There are only three possible layouts for [plotAbundanceDensity](https://microbiome.github.io/miaViz/reference/plotAbundanceDensity.html) function. Resulting plots are often cluttered and not informative. More plot options can be added, for example boxplots that can measure counts by bacterium by a metadata from `colData`, i.e., grouped boxplot. See examples [here](https://www.statology.org/grouped-boxplot-r-ggplot2/).

**Comment by antagomir** [comment]
This issue should be moved to miaViz?

**Comment by antagomir** [comment]
@Daenarys8 can you move the issue to miaViz and see if the issue could be solved as well?

**Comment by antagomir** [comment]
Close this after moved to miaViz
