### ISSUE TITLE
Error with loadFromMetaphlan

### ISSUE THREAD

**Issue by J5886** [microbiome/mia#497]
hello all, 

thanks a lot for the wonderful package,

I'm trying to use loadFromMetaphlan to create a TreeSummarizedExperiment with Metaphlan 4 output. 
"file_path <- system.file("extdata", "metaphlan_taxonomic_profiles.txt", package = "mia")
# Import data
tseobj<- loadFromMetaphlan(file_path)" 
tseobj
I got this error 
"<html>
<body>

Error: 'file' must be a single character value.
--
 
  |  
 

<br class="Apple-interchange-newline">
</body>
</html>"

I tried with the output of metaphlan 4 tutorial and it works properly, but not with my file 
[merged_abundance_table (metaphlan 4 tutorial output).txt](https://github.com/microbiome/mia/files/14454403/merged_abundance_table.metaphlan.4.tutorial.output.txt)
[metaphlan_taxonomic_profiles (My output).txt](https://github.com/microbiome/mia/files/14454404/metaphlan_taxonomic_profiles.My.output.txt)

I'm using mia version 1.8.0

Could you please help me with this issue?

Regards

**Comment by antagomir** [comment]
Current version is 1.11.5. Can you try again after updating the pkg with 

`remotes::install_github("microbiome/mia")`

**Comment by J5886** [comment]
> remotes::install_github("microbiome/mia")

Hi @antagomir 
thanks for the prompt reply,
I updated the package to the latest version
but still the same error
> library("mia"); packageVersion("mia")
[1] ‘1.11.5’
> file_path <- system.file("extdata", "metaphlan_taxonomic_profiles.txt", package = "mia")
> # Import data
> tseobj <- loadFromMetaphlan(file_path)
Error: 'file' must be a single character value.

**Comment by TuomasBorman** [comment]
Hello!

So you are trying to import your own Metaphlan file to TreeSE format?

`system.file()` function here in our examples is just for pointing to mia packages example file directory.  Instead, you should do something like this:

`file_path <- "your_directory/your_metaphlan_file.txt"`

-Tuomas

**Comment by J5886** [comment]
> Hello!
> 
> So you are trying to import your own Metaphlan file to TreeSE format?
> 
> `system.file()` function here in our examples is just for pointing to mia packages example file directory. Instead, you should do something like this:
> 
> `file_path <- "your_directory/your_metaphlan_file.txt"`
> 
> -Tuomas

Hi Tuomas,
thanks for your reply,

I changed the command, but the same error still exists.

file_path <- read_tsv("metaphlan_taxonomic_profiles.txt")
tseobj <- loadFromMetaphlan(file_path)
Error: 'file' must be a single character value.

any suggestions will be appreciated

Regards

**Comment by TuomasBorman** [comment]
`file_path` is not actually a path. (Print it, it is `data,frame` now).

This should work

`tseobj <- loadFromMetaphlan("metaphlan_taxonomic_profiles.txt")`

**Comment by J5886** [comment]
Thanks a lot for your help,
I got this error;
> tseobj <- loadFromMetaphlan("metaphlan_taxonomic_profiles.txt")
Error: Error while reading metaphlan_taxonomic_profiles.txt
Please check that the file is in merged Metaphlan file format.

the file is a metaphlan4 output (by biobakery_workflow wmgx)

**Comment by TuomasBorman** [comment]
Hard to say what is the problem. Metaphlan4 should be supported but there might be some error. Is your data sensitive or can you share it for example via email?

**Comment by J5886** [comment]
> hello all,
> 
> thanks a lot for the wonderful package,
> 
> I'm trying to use loadFromMetaphlan to create a TreeSummarizedExperiment with Metaphlan 4 output. "file_path <- system.file("extdata", "metaphlan_taxonomic_profiles.txt", package = "mia")
> 
> # Import data
> tseobj<- loadFromMetaphlan(file_path)" tseobj I got this error "
> 
> Error: 'file' must be a single character value. --     |    
> "
> I tried with the output of metaphlan 4 tutorial and it works properly, but not with my file [merged_abundance_table (metaphlan 4 tutorial output).txt](https://github.com/microbiome/mia/files/14454403/merged_abundance_table.metaphlan.4.tutorial.output.txt) [metaphlan_taxonomic_profiles (My output).txt](https://github.com/microbiome/mia/files/14454404/metaphlan_taxonomic_profiles.My.output.txt)
> 
> I'm using mia version 1.8.0
> 
> Could you please help me with this issue?
> 
> Regards

I already provided the outputs here my output and the metaphlan4 tutorial output

 thanks for your time

**Comment by TuomasBorman** [comment]
Ohh sorry, I missed that. Is your file a direct output from the pipeline (you haven't done any manual modifications)? Can you give me more information on what version of pipeline are you running?

The file does not have those common metaphlan identifiers which is why the function says that the input is incorrect.

**Comment by J5886** [comment]
yes this is the exact output file 

for the information you mean, I noticed that but I thought it was not necessary for the downstream analysis

The metaphaln version is 4.0.6 (I Mar 2023)

the missed inf. you mentioned "mpa_v0ct22_CHOCOPhlAnSGB_202212" 

BTW, as I told you, this is the output of Biobakery_workflow which includes workflow for QC processing by KneadData, taxonomic profiling with Metaphlan, and functional profiling with HUMAnN

thank you

**Comment by J5886** [comment]
> mpa_v0ct22_CHOCOPhlAnSGB_202212

the issue was solved
I just included the database name "mpa_v0ct22_CHOCOPhlAnSGB_202212" at the top of the Metaphlan output and the command works properly

thanks a lot for your time and help

**Comment by TuomasBorman** [comment]
Yes. But I think you had to also modify column name from taxonomy to clade_name? (The database name is not actually required.)

The function checks that there are correct columns specifying the taxonomy. "taxonomy" is not currently in the list, but I will add it.

**Comment by J5886** [comment]
> Yes. But I think you had to also modify column name from taxonomy to clade_name? (The database name is not actually required.)
> 
> The function checks that there are correct columns specifying the taxonomy. "taxonomy" is not currently in the list, but I will add it.

Yes, that is what I did, removed the #taxonomy and replaced it with clade_name to be similar to the tutorial output

**Comment by TuomasBorman** [comment]
OK, thanks! It is little bit weird that there is # before "taxonomy" since in metaphlan files that usually means  comment. However, it seems that taxonomy is one of the possible column name for a column specifying a taxonomy so I will add support for that.

**Comment by J5886** [comment]
Hi @TuomasBorman,
thanks for your efforts
Sorry to reopen the issue,  I'm trying to add the metadata to tse object. But, I got this Warning 

tseobj <- loadFromMetaphlan("metaphlan_taxonomic_profiles.txt", meta)
Warning message:
The sample names in 'colData' do not match with the data. The sample metadata is not added.

Bc I can't share the metadata Info. file,  this is just an example
  SampleID	treatment
    sample1	Before
  sample11	After
  sample13	After
    sample5	Before
even when I changed the names of SampleID to be compatible with metaphlan's output, I got the same warning.
Regards!

**Comment by TuomasBorman** [comment]
Are those sample names in rownames? https://microbiome.github.io/mia/reference/loadFromMetaphlan.html

**Comment by antagomir** [comment]
@J5886 if you can easily provide artifical metadata file that that could also help with debugging.

**Comment by J5886** [comment]
Hi @TuomasBorman @antagomir 

The names are correct in the metadata file, but Metaphlan added the "taxonomic_profile" to the sample ID.
Even when I changed the names in the metadata file to be like the output of Metaphlan, the same warning was introduced.

this is an artificial example of the metadata file,
[Metadata.txt](https://github.com/microbiome/mia/files/14469674/Metadata.txt)

thanking your help

**Comment by TuomasBorman** [comment]
You can always add sample metadata to colData with `colData() <- `

1. Check that samples are in correct order in metadata table. The order of samples in **metadata table's rows** and **TreeSEs columns** must match.
2. Add `colnames(tse)` to `rownames(metadata)`
3. Add metadata to TreeSE: `colData(tse) <- metadata`

**Comment by antagomir** [comment]
I hope that works. 

Non-standard cases are more tricky as they can vary case-by-case.

But in this case I understood from the thread that mia could not read the files as they come out from the processing pipeline - correct me if I am wrong. That sounds somewhat standard.

Is there anything to do to automate this further for standard cases, and/or ensure that there is a clear import example on the manpages (and potentially in OMA)?

**Comment by TuomasBorman** [comment]
The file in this issue contains "#" before column names. That is the only case where I have seen that kind of file structure and based on this, we cannot standardize the function more, because it is relying on

1. All rows starting with # are comments
2. The column names contain Metaphlan specific columns.

Of course, we can check the Metaphlan in more detail.

I think https://microbiome.github.io/mia/reference/loadFromMetaphlan.html is clear enough. I just noticed that

`tse <- loadFromMetaphlan(file_path, remove.suffix = TRUE)`

might work here in the metadata issue.

**Comment by J5886** [comment]
> You can always add sample metadata to colData with `colData() <- `
> 
> 1. Check that samples are in correct order in metadata table. The order of samples in **metadata table's rows** and **TreeSEs columns** must match.
> 2. Add `colnames(tse)` to `rownames(metadata)`
> 3. Add metadata to TreeSE: `colData(tse) <- metadata`

I'll try using "colData() <-"  

> But in this case I understood from the thread that mia could not read the files as they come out from the processing pipeline - correct me if I am wrong. That sounds somewhat standard.

the output from Metaphlan was a little bit different, by adding #taxonomy instead of clade_name, the information of the database was missed as well, by doing these changes it works. However, I still doubt that because I ran the Metaphaln within Biobakey_workflows (wmgx) these differences occurred, soon I'll run the Metaphlan alone and compare the results. 

Regards

**Comment by J5886** [comment]
> You can always add sample metadata to colData with `colData() <- `
> 
> 1. Check that samples are in correct order in metadata table. The order of samples in **metadata table's rows** and **TreeSEs columns** must match.
> 2. Add `colnames(tse)` to `rownames(metadata)`
> 3. Add metadata to TreeSE: `colData(tse) <- metadata`

the colData function works poreprly to add the metadata to the tse, but when tried to convert the tse to phyloseq an error found
phy <- makePhyloseqFromTreeSE(tse)
Error: 'assay.type' must be a valid name of assays(x)

without adding metadata or using the colData(), it was possible to convert to phyloseq object as follows;
" physeq <- makePhyloseqFromTreeSE(tseobj)
physeq 
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 824 taxa and 4 samples ]
tax_table()   Taxonomy Table:    [ 824 taxa by 7 taxonomic ranks ]"

I really appreciated your help,

**Comment by J5886** [comment]
Hi @TuomasBorman 
I tried using the created  tse object from Metaphlan to calculate diversity  via function estimateDiversity, and even  for preparing the data for DA analysis with transformAssay, but I got an error  
Error: 'assay.type' must be a valid name of assays(x)

any suggestions are highly appreciated
regards

**Comment by TuomasBorman** [comment]
Can you paste the print() of your object?

**Comment by antagomir** [comment]
Also pasting code example that generates the error should help I guess

**Comment by J5886** [comment]
> print()

> print(tse)
class: TreeSummarizedExperiment 
dim: 824 4 
metadata(0):
assays(1): ''
rownames(824): s__GGB741_SGB955 s__GGB781_SGB1024 ...
  s__Methanomassiliicoccaceae_unclassified_SGB380 s__TM7_phylum_sp_oral_taxon_352
rowData names(0):
colnames(4): P01 C11 P13 C5
colData names(5): Sample age treatment gender BMI
reducedDimNames(0):
mainExpName: NULL
altExpNames(0):
rowLinks: NULL
rowTree: NULL
colLinks: NULL
colTree: NULL
 
I want to calculate the alpha and beta diversity and then do the DA analysis.


> Also pasting code example that generates the error should help I guess
for the diversity
tse <- mia::estimateDiversity(tse, 
                              assay.type = "counts",
                              index = "shannon", 
                              name = "shannon")
for DA 
tse <- transformAssay(tse,
                      assay.type = "counts",
                      method = "relabundance")
both generated the same error

I can send both files (Metaphlan output and metadata) via email if that could help

thanking your help

**Comment by TuomasBorman** [comment]
See the TreeSE object. Your assay is named as "" for some reason. (It should be "counts" by default when importing with mia tools)  Can you also give the code before this point? (I can check your files in detail if I cannot solve the problem by just looking the code)

This should fix your problem for now

`assayNames(tse) <- "counts"`

**Comment by J5886** [comment]
> assayNames(tse) <- "counts"

I just loaded the Metaphlan file then read the metadata and created the tse object as follows:

tseobj <- loadFromMetaphlan("metaphlan_taxonomic_profiles.txt", remove.suffix = TRUE)

meta <- read.table("Metadata.txt", header = T)
colData <- DataFrame(meta)
tse <- TreeSummarizedExperiment(tseobj,
                                colData = colData)

tse

I used the assayNames(tse) <- "counts"

> assayNames(tse) <- "counts"
> tse <- transformAssay(tse,
+                       assay.type = "counts",
+                       method = "relabundance")
Error in mat + pseudocount : non-numeric argument to binary operator
> tse <- subsetByPrevalentFeatures(tse,
+                                  rank = "Genus",
+                                  prevalence = 10 / 100)
Error: 'rank' must be a value from 'taxonomyRanks()'
> tse <- mia::estimateDiversity(tse,
+                               assay.type = "counts",
+                               index = "shannon",
+                               name = "shannon")
Error: BiocParallel errors
  1 remote errors, element index: 1
  0 unevaluated and other errors
  first remote error:
Error in t.default(mat): argument is not a matrix

I think the differences between the outputs of Metaphaln and other pipelines such as qiime2 introduced such errors, I used mia with 16S data (qiime2) and it worked pretty.

**Comment by TuomasBorman** [comment]
```
tseobj <- loadFromMetaphlan("metaphlan_taxonomic_profiles.txt", remove.suffix = TRUE)

meta <- read.table("Metadata.txt", header = T)
colData <- DataFrame(meta)
tse <- TreeSummarizedExperiment(tseobj,
colData = colData)
```

tse_obj is TreeSE, so adding metadata line is incorrect, Instead of constucting new TreeSE (which is done incorrectly since TreeSE constructor should not take TreeSE as input), you can just insert metadata to existing one.

So the corrected code above:

```
tse <- loadFromMetaphlan("metaphlan_taxonomic_profiles.txt", remove.suffix = TRUE)

meta <- read.table("Metadata.txt", header = TRUE)
colData(tse) <- DataFrame(meta)
```

Difference between Metaphlan and Qiime2 should not be an issue. We have personally used mia with those pipelines listed and also others. So they are tested.

1. Your initial issue was that your file was not detected. That was because your Metaphlan included # character in a place where it is not usually.

Usually in Metaphlan files, # means a comment that states the used database. That database info is in first line of the file. Your file did not have that database information.

In the second line, Metaphlan files usually have headers. This line does not usually have #. For some reason, your first line included # and headers which was read as a comment. --> So the function did not find the headers from the file which is why it told that the file is not Metaphlan file.

2. This second issue that is now occurring is related to incorrect TreeSE construction. TreeSE constructor is used incorrectly. You are feeding your TreeSE object to assay slot of new TreeSE. (Your assay slot includes TreeSE instead of matrix. Try `assay(tse)` )

Hopefully now it works

**Comment by J5886** [comment]
> ```
> tseobj <- loadFromMetaphlan("metaphlan_taxonomic_profiles.txt", remove.suffix = TRUE)
> 
> meta <- read.table("Metadata.txt", header = T)
> colData <- DataFrame(meta)
> tse <- TreeSummarizedExperiment(tseobj,
> colData = colData)
> ```
> 
> tse_obj is TreeSE, so adding metadata line is incorrect, Instead of constucting new TreeSE (which is done incorrectly since TreeSE constructor should not take TreeSE as input), you can just insert metadata to existing one.
> 
> So the corrected code above:
> 
> ```
> tse <- loadFromMetaphlan("metaphlan_taxonomic_profiles.txt", remove.suffix = TRUE)
> 
> meta <- read.table("Metadata.txt", header = TRUE)
> colData(tse) <- DataFrame(meta)
> ```
> 
> Difference between Metaphlan and Qiime2 should not be an issue. We have personally used mia with those pipelines listed and also others. So they are tested.
> 
> 1. Your initial issue was that your file was not detected. That was because your Metaphlan included # character in a place where it is not usually.
> 
> Usually in Metaphlan files, # means a comment that states the used database. That database info is in first line of the file. Your file did not have that database information.
> 
> In the second line, Metaphlan files usually have headers. This line does not usually have #. For some reason, your first line included # and headers which was read as a comment. --> So the function did not find the headers from the file which is why it told that the file is not Metaphlan file.
> 
> 2. This second issue that is now occurring is related to incorrect TreeSE construction. TreeSE constructor is used incorrectly. You are feeding your TreeSE object to assay slot of new TreeSE. (Your assay slot includes TreeSE instead of matrix. Try `assay(tse)` )
> 
> Hopefully now it works

Hi @TuomasBorman 
it works 
thanks a lot for your time and patience 

Thanks @antagomir for your comments and help

best regards!

**Comment by TuomasBorman** [comment]
Cool! Thanks for the feedback and all, this helps us to develop the ecosystem

**Comment by li-fangyeo** [comment]
Hi Tuomas, 

I am commenting here because I have a similar problem but because I can't see how you fixed it.

tse <- loadFromMetaphlan("direct_merged_abundance_table.txt",remove.suffix = TRUE)
Error: Error while reading direct_merged_abundance_table.txt
Please check that the file is in merged Metaphlan file format.

Below is what my abundance table looks like. This was generated directly from metaphlan4 pipeline.

#mpa_vOct22_CHOCOPhlAnSGB_202212
	J02	J04	J09	J10	J14	J16	J18	J24	J26	J31	J38	J41	MLY001	MLY003	MLY004	MLY005	MLY006	MLY007	MLY008	MLY009	MLY010	TM016M	TM017F	TM037F	TM039M	TM056F	TM114M	TM123M	TM125F	TM167F	TM168M	TM169M	TM175F	TRk011F	TRk025M	TRk041F	TRk064F	TRk069F	TRk094M	TRk123F	TRk125M	TRk136M
0_k__Bacteria|p__Bacteroidetes	14.21387	9.30559	17.8508	22.17351	23.75456	7.68234	29.58171	30.61931	30.2766	18.66608	16.32892	26.18605	3.86991	0.07652	7.00662	4.81564	0.0712	0.04451	12.77285	10.15245	23.25373	17.55976	3.32568	56.77206	15.03867	25.41218	2.01775	32.47226	37.51645	33.89894	33.78358	20.20556	7.2365	38.01969	10.0458	6.0783	15.98744	31.19649	17.42712	30.42884	4.49577	16.17224
0_k__Bacteria|p__Proteobacteria	1.53576	10.16739	2.43154	1.69223	1.73525	0.53312	3.49442	0.58825	1.90923	1.33682	3.59572	0.70626	1.06557	1.02509	0.60291	0.39171	0.99698	1.39508	2.54197	0.37144	1.97369	0.626	1.05989	2.30433	0.96816	1.60888	0.7685	8.95977	1.22741	8.7506	23.19424	8.9451	2.87948	3.18107	1.24811	0.77836	0.75058	3.12907	2.60392	0.70095	0.13257	0.65896

**Comment by antagomir** [comment]
Hi! Make sure that you use the latest mia version, see devtools::install_github("microbiome/mia") in R, and then the updated importer https://microbiome.github.io/mia/reference/importMetaPhlAn.html

**Comment by li-fangyeo** [comment]
Hi! Thank you =D 

I managed to import it and also I modified my Metaphlan output column to match the example data and then mia can read my file.
