### ISSUE TITLE
addHierarchyTree replaces existing tree

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/mia#498]
Currently, `addHierarchyTree` (`addTaxonomyTree`) replaces existing tree. Consider adding option for adding tree instead of replacing.

**Comment by 0xMuluh** [comment]
should we implement an addTree option to append the  rowTree and colTree slots ?

**Comment by TuomasBorman** [comment]
Maybe there could be name parameter. By default, it could be "phylo". Then you could check if a tree named "phylo" is already existing and give warning if it is.

The created internal function could follow this structure https://github.com/microbiome/mia/blob/b627edce620807af20d3ed85c6667f4b8ef8f2ea/R/utils.R#L310. Also take into account the MARGIN in this internal function
.

**Comment by antagomir** [comment]
Is this issue something we could close already @Daenarys8 @TuomasBorman

**Comment by TuomasBorman** [comment]
Yes, I believe. Each row must be linked only once (rowLinks can have only one link per row). Based on this, it is not possible to not overwrite the existing tree
