### ISSUE TITLE
man page for transformCounts is malformated 

### ISSUE THREAD

**Issue by FelixErnst** [microbiome/mia#52]
Hi @tvborm 

the man page looks malformated on my end

![image](https://user-images.githubusercontent.com/17824332/106579042-83e3f880-6540-11eb-9bf0-4e477ac66dd1.png)

Can you confirm, this looks the same for you? If yes, can you fix it?

Thanks!

Felix

**Comment by TuomasBorman** [comment]
Yeah, it looks strange. In fact, the estimateDominance has the same problem. I fix them.

-Tuomas

**Comment by FelixErnst** [comment]
1c6f90e
