### ISSUE TITLE
"tsemelt"

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#54]
For fast exploration purposes it would be useful to have `TSE` equivalent to `phyloseq::psmelt` (i.e. `tsemelt` :-) ).

**Comment by FelixErnst** [comment]
I think this is already implemented

https://felixernst.github.io/mia/reference/meltAssay.html

However, it might good to think about reusing an alternative function name from MultiAssayExperiment, `longFormat`, if the generic is available in `BiocGenerics`.

**Comment by antagomir** [comment]
Ah, great! I leave this open for the latter suggestion.

**Comment by FelixErnst** [comment]
@microsud Can you have a look whether the genric is available from `BiocGenerics`? It yes, just add a wrapper for `meltAssay`

**Comment by microsud** [comment]
Could not find a `melt` or `longFormat` generic.

**Comment by FelixErnst** [comment]
So we have the implementation we can have.
