### ISSUE TITLE
mergeSEs: tree merging

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/mia#558]
Tree merging part just check if tree row can be found from set of trees. It finds the smallest number of trees that can present the rows and adds them to TreeSE. However, correct way is to merge the tree into single tree https://www.rdocumentation.org/packages/ape/versions/5.8/topics/bind.tree

**Comment by 0xMuluh** [comment]
Create random trees:

```
 x <- ape::rtree(5)
 y <- ape::rtree(10)

 x <- ape::makeNodeLabel(x, prefix = "x_")
 y <- ape::makeNodeLabel(y, prefix = "y_")

 combined_tree <- tree1
```
Get unique taxa in both trees

```
 taxax <- x$tip.label
 taxay <- y$tip.label
common_taxa <- intersect(taxax, taxay)
common_mapping <- match(common_taxa, y$tip.label)

```

Remove common taxa from y to avoid duplication

` z <- drop.tip(y, common_taxa)`

Bind the remaining part of tree2 to tree1 at the common taxa nodes

`combined_tree <- bind.tree(combined_tree, z, where = common_mapping[i])`



![Rplot01](https://github.com/microbiome/mia/assets/127390183/b2755306-454c-4f0b-9c32-b97b90069c15)
![Rplot](https://github.com/microbiome/mia/assets/127390183/be7c398c-1d2d-4159-b785-5455db5ebbf2)
![Rplot02](https://github.com/microbiome/mia/assets/127390183/dc36efea-86ee-4e42-9056-f20d7da67bfb)
![Rplot03](https://github.com/microbiome/mia/assets/127390183/c053f5fe-8618-4b6e-8467-d526fc75afdb)

**Comment by TuomasBorman** [comment]
I don't have now time to check in detail, but row can be also linked with internal node. Then the row cannot be found from tip. If you then use drop.tip, it might remove also internal node that represent row. We have .prune_tree function that takes this into account. Explore that.
