### ISSUE TITLE
Add coverage to estimateDiversity 

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#58]
The  [coverage index](https://github.com/microbiome/microbiome/blob/master/R/coverage.R) is a type of diversity index. Sometimes used in ecological literature and sketched in microbiome pkg. This could be incorporated as an additional option in `estimateDiversity` function?

**Comment by FelixErnst** [comment]
Can you author a PR?

**Comment by antagomir** [comment]
Me or @tvborm can do it as the time allows.

**Comment by TuomasBorman** [comment]
It is now added

https://github.com/FelixErnst/mia/pull/71

**Comment by antagomir** [comment]
Have you added unit tests as well @tvborm ?

**Comment by FelixErnst** [comment]
c2f55aa
