### ISSUE TITLE
Detection vs prevalence improve documentation

### ISSUE THREAD

**Issue by artur-sannikov** [microbiome/mia#580]
In `getPrevalence` ([code](https://github.com/microbiome/mia/blob/devel/R/getPrevalence.R)) documentation, the difference between `detection` and `prevalence` is not very clear.

Prevalence is a common term in biology, but `detection` is much less. It's nicely explained in [OMA](https://microbiome.github.io/OMA/docs/devel/pages/12_quality_control.html#prevalence):

> The function arguments detection and as_relative can also be used to access how many samples pass a threshold for raw counts. Here, the population prevalence (frequency) at the absolute abundance threshold (as_relative = FALSE) at read count 1 (detection = 1) is accessed.

Can be rewritten

> Detection threshold for absence/presence.  If as_relative = FALSE, it sets the counts threshold for a taxon to be considered present. If as_relative = TRUE, it sets the relative abundance threshold for a taxon to be considered present.

Or we can rewrite the `Details` section to clarify this aspect with a couple of examples.

**Comment by antagomir** [comment]
PR welcome !
