### ISSUE TITLE
Overlap between samples

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#60]
The [microbiome::overlap](https://github.com/microbiome/microbiome/blob/master/R/overlap.R) function returns the overlap index between communities, used in Bashan, A., Gibson, T., Friedman, J. et al. Universality of human microbial dynamics. Nature 534, 259–262 (2016) https://doi.org/10.1038/nature18301 - could be potentially added in mia as well. In a sense this is a beta diversity index but not a typical one.

**Comment by microsud** [comment]
I came across a bootstrap implementation of this used by [Gao, C., Montoya, L., Xu, L. et al. Fungal community assembly in drought-stressed sorghum shows stochasticity, selection, and universal ecological dynamics. Nat Commun](https://www.nature.com/articles/s41467-019-13913-9#Sec9) and code is [here](https://github.com/Russel88/DOC)
Your thoughts?

**Comment by FelixErnst** [comment]
Probably a nice implementation, but the code is a repo, which we cannot use, since it is not on CRAN or Bioconductor. I don't want to just use their code.

Nice idea, but I don't see a way to implement it with/within/for mia.

**Comment by antagomir** [comment]
The license in Geo et al. is MIT and probably it would be possible to switch to Artistic with permission from the author. If this code can improve the function that we previously wrote in microbiome pkg then it should be possible to convert and add directly in mia. 

How this should be prioritized w.r.t other things is another discussion.

**Comment by FelixErnst** [comment]
Any news on this? @microsud

**Comment by microsud** [comment]
This one fell off the radar. Sorry. I can or @TuomasBorman (if he has time and energy) try to implement the `microbiome` R pkg code in `mia`

**Comment by TuomasBorman** [comment]
@microsud Yep, I can do that when time allows

**Comment by antagomir** [comment]
The microbiome pkg version can be moved easily but if the Gao paper has clear benefits it would be good to considered this at the same go when one of us can go through this.

**Comment by FelixErnst** [comment]
If it is MIT make the origin of the code clear, but check for license compatibility first. There must be how-to or something somewhere. IT is a good exercise for either of you.
