### ISSUE TITLE
mia::importHUMAnN() problem

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#627]
Critical sample matching issue reported in:
https://github.com/finrisk2002/finriskR/issues/34

Related to #622

**Comment by antagomir** [comment]
Was this already solved? @himmil do you know?

**Comment by himmil** [comment]
I don't actually know. This is not related to the missing hyphen issue

**Comment by TuomasBorman** [comment]
What I understood from the issue in Finrisk was that the issue is not in mia but in Finrisk code. This issue can be closed in mia; the issue in Finrisk stays open.
