### ISSUE TITLE
agglomerateByVariable should have `na.rm` parameter?

### ISSUE THREAD

**Issue by artur-sannikov** [microbiome/mia#654]
`agglomerateByRank` has `na.rm` parameter, but `agglomerateByVariable` does not. Is there a reason for this?

```R
library(mia)
data("GlobalPatterns", package = "mia")
tse <- GlobalPatterns

tse_sub <- agglomerateByVariable(tse, by = "cols", group = "SampleType",
                                 na.rm = TRUE) # Won't work
tse_sub
```

```
Error in .local(x, ...) : unused argument (na.rm = TRUE)
```

What if there are some NA values in microbial abundances?

I'm using mia_1.13.45.

**Comment by antagomir** [comment]
I agree it would be logical to have similar behavior for both. The na.rm should be dealth with argument passing.

That being said, should be investigated more closely.

**Comment by TuomasBorman** [comment]
`agglomerateByVariable` uses `scuttle::summarizeAssayByGroup` (for cols) and `scuttle:sumCountsAcrossFeatures` (for rows) internally. These functions do not have `na.rm` parameter.

For columns, this can be easily fixed: just add `na.rm`: If `na.rm=TRUE`, all `NA` values will be converted to 0.

For rows, we cannot do that directly, because `sumCountsAcrossFeatures` can also calculate average, and converting NA to 0 would lead to wrong answer.

--> requires some thinking what to do

**Comment by TuomasBorman** [comment]
Thing to note is that `na.rm` in `agglomerateByRank` is controlling whether we remove those rows that do not have taxonomy information in specified taxonomy level. Summing NAs still lead to NA:
```

> agglomerateByRank(tse, rank = "Kingdom", na.rm = TRUE) |> assay()
            CL3     CC1    SV1 M31Fcsw M11Fcsw M31Plmr M11Plmr F21Plmr M31Tong M11Tong LMEpi24M SLEpi20M  AQC1cm  AQC4cm  AQC7cm    NP2     NP3     NP5 TRRsed1 TRRsed2
Archaea      NA    1248  28811      33      57      42     112     140     303      30      131      145    4459   24692   28051   1826   43197   33996     843    8418
Bacteria 862815 1134209 668698 1543418 2076419  718901  433782  186157 2000099  100157  2117461  1217167 1163289 2332489 1671242 521808 1435768 1618758   57845  484708
         TRRsed3   TS28    TS29   Even1  Even2   Even3
Archaea    14250   1598    1690     150     23      91
Bacteria  265454 935868 1209381 1215987 971050 1078150
```

`na.rm` was not working in `agglomerateByVariable` by column, but by row it was working. The behavior is similar to `agglomerateByRank`; whether to remove rows that have NA value in group ID.

```
> agglomerateByVariable(tse, by = 1, group = "Kingdom", na.rm = TRUE) |> assay()
            CL3     CC1    SV1 M31Fcsw M11Fcsw M31Plmr M11Plmr F21Plmr M31Tong M11Tong LMEpi24M SLEpi20M  AQC1cm  AQC4cm  AQC7cm    NP2     NP3     NP5 TRRsed1 TRRsed2
Archaea      NA    1248  28811      33      57      42     112     140     303      30      131      145    4459   24692   28051   1826   43197   33996     843    8418
Bacteria 862815 1134209 668698 1543418 2076419  718901  433782  186157 2000099  100157  2117461  1217167 1163289 2332489 1671242 521808 1435768 1618758   57845  484708
         TRRsed3   TS28    TS29   Even1  Even2   Even3
Archaea    14250   1598    1690     150     23      91
Bacteria  265454 935868 1209381 1215987 971050 1078150
```
The question is that whether the behavior of `na.rm` is intuitive? Most of the functions use `na.rm` to control whether `NA` values are excluded in calculation, e.g. `sum(c(NA, 1, 3), na.rm = TRUE)`. For instance, `agglomerateByRank` could be

`agglomerateByRank(tse, rank = "Kingdom", empty.rm = TRUE, na.rm = TRUE)`

where `empty.rm` behaves similarly to current `na.rm`, and `na.rm` works like `sum(na.rm=TRUE)`. However, the function is already rather established so it is problematic if we just change the behavior.

**Comment by artur-sannikov** [comment]
`na.rm` is also present in many functions in other packages. My naive expectation was that if I want to sum up abundances by a column from colData, I should be able to do that even if there are some NAs for a species/metabolite.

For example, I can have a column "organ" with two values "liver" and "heart". I should be able to aggregate all abundances by the "organ" even if some metabolite/microbe is not present in just one sample.

**Comment by antagomir** [comment]
I tend to agree with @artur-sannikov and I would support the default assumption that `na.rm` ignores NAs in the calculation, and I think that this should behave similarly for all functions (except possibly in some rather special cases). 

Even if `agglomerateByRank` is in use already, I think it could be acceptable change. We could even add an automatic warning that can stay for some releases. It is easier to change now than later in any case, and it is also problematic if users have misleading expectations about the behavior or can't do the standard things easily.

We can also (try to) suggest PRs to `scuttle` if that helps.
