### ISSUE TITLE
ReadCount?

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#66]
Should we have a shortcut / wrapper to calculate ReadCount or LibrarySize for the samples in a given `TSE` object? 

Motivation: can make code more readable and provides an easy shortcut for a commonly used functionality.

**Comment by FelixErnst** [comment]
Do you mean with `librarySize` the reads per sample? `librarySizeFactors` is available from `scuttle` to calculate relative library sizes. `colSums` is the function to get absolute values

**Comment by antagomir** [comment]
Yep it would be an alias for `colSums`. More explicit for microbiome context but perhaps also more problematic and not really needed.

**Comment by FelixErnst** [comment]
Thats what I would say. I think there is no benefit to wrap a base R concept with microbiome terms. This will only lead to non-reusable knowledge. However, the concept can be explained in `MiaBook`
