### ISSUE TITLE
getTaxa

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#67]
I propose to add function `getTaxa` that would return a list of all taxa present in the data (given assay). This would be a rough equivalent to `microbiome::taxa`.

We already have `getTopTaxa` that could be used for this but it emphasizes "top" taxa and it emphasizes the most abundant taxa:

`getTopTaxa(x)
`[1] "549656" "331820" "279599" "360229" "317182"

I also noticed another related issue that has to be sorted out at the same time. We have the function `getDominantTaxa` whose name is very similar but output is of different form. I propose to change naming scheme to avoid confusion here. We could replace the name `getDominantTaxa` for instance with `summarizeDominantTaxa`?

`getDominantTaxa(x)

   dominant_taxa     n rel.freq rel.freq.pct
   <chr>         <int>    <dbl> <chr>       
 1 331820            3     11.5 12%         
 2 549656            3     11.5 12%         
 3 550960            3     11.5 12%         
 4 319044            2      7.7 8%

**Comment by FelixErnst** [comment]
What should `getTaxa` do? What would be different compared to `taxonomicRanks(x)` or `rowData(x)[,taxonomicRanks(x)]`?

**Comment by antagomir** [comment]
`taxonomicRanks(x)` lists the available ranks and `getTaxa(x)` would return taxa within a given rank.

In this sense, it would be similar to `rowData(x)[,taxonomicRanks(x)]` (which returns a data.frame) but instead return a vector that corresponds to a specific rank. 

Hence, `getTaxa(x, "Genus")` would be a shortcut to `rowData(x)[, "Genus"]`.

Perhaps unnecessarily simple to implement. Again, more intuitive naming scheme but relatively minimal improvement and no other advantage.

**Comment by antagomir** [comment]
I open another issue of the second observation.

**Comment by microsud** [comment]
This would be something like phyloseq::get_unique_taxa(X)
https://rdrr.io/bioc/phyloseq/man/get_taxa_unique.html

rowData(x)[, "Genus"] will return all not just unique.
These are useful functions when exploring data.

**Comment by antagomir** [comment]
Yes, even though the unique could be an optional function argument (perhaps TRUE by default).

These are useful for data exploration also in my experience. This is why I have opened the issue and I think we should facilitate these things. 

Of course some of that could go to other utility packages if that is somehow better.

**Comment by FelixErnst** [comment]
I think this should be linked the summarization issue #69 There are a few related functions, which should be moved to a single man page to provide a better overview with a single man page and not having to go through several.

**Comment by FelixErnst** [comment]
Closed by 470fdbe #104
