### ISSUE TITLE
Map levels

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#68]
We could add a function that would map between different taxonomic levels, for instance from genera to species, or from species to genera etc. (either way, from lower to higher levels and vice versa). This can be handy in many cases.

This would be a rough equivalent to [microbiome::map_levels.R](https://github.com/microbiome/microbiome/blob/master/R/map_levels.R).

**Comment by FelixErnst** [comment]
I am not 100% sure, what this function should accomplish.

If I understand it correctly, this would be the equivalent result?
```
td <- rowData(x)[,taxonomicRanks(x)]
td[!is.na(td$Phylum) & td$Phylum == "Verrucomicrobia","Genus"]
```

**Comment by antagomir** [comment]
Yes. The idea is to add easy-to-use shortcuts for common functionalities. 

`map(x, from = "genus", to = "species") ` (or something like that) could be more rapidly readable than the expression above. 

Although the specific way to implement and write that could be debated, the idea is to provide an intuitive shortcut.

**Comment by FelixErnst** [comment]
Can you describe a scenario in, which you use this function? What is the aim that should be accomplished or the question which should be answered?

**Comment by FelixErnst** [comment]
bumping this. Any additional information/example you can provide?

**Comment by antagomir** [comment]
Thanks - we frequently need to ask 
1. what more refined groups (ASVs, species..) are included in a particular phylum or family
2. what is the corresponding phylum (or other higher level) for a given ASV, species or genus

We use this frequently in miscellaneous data wrangling & interpretation tasks, there is `microbiome::map_levels` for phyloseq objects.

If this does not fit mia, we can consider `miautilities` package in a similar vein to @microsud `microbiomeutilities` that could have such shortcuts/wrappers for common tasks.
