### ISSUE TITLE
Naming scheme: getDominantTaxa to summarizeDominantTaxa?

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#70]
`getTopTaxa(x) ` returns a vector
"549656" "331820" "279599" "360229" "317182"

`getDominantTaxa(x)` returns a data.frame:

dominant_taxa n rel.freq rel.freq.pct
1 331820 3 11.5 12%
2 549656 3 11.5 12%
3 550960 3 11.5 12%
4 319044 2 7.7 8%

Suggestion; rename `getDominantTaxa` as `summarizeDominantTaxa` for a more consistent naming scheme.

**Comment by FelixErnst** [comment]
This a triplet of the discussion we are having in #69 and #67. Lets focus it in one thread and make sure we discuss the individual functions in the grant scheme of things. #69 seems to be the best fit for the general idea behind all this.

**Comment by FelixErnst** [comment]
Closed by 470fdbe #104
