### ISSUE TITLE
cannot install on R 4.0.3

### ISSUE THREAD

**Issue by carlosmandoz** [microbiome/mia#72]
Hi,

I tried all kinds of routes to install but in the end I always end up at:

```
ERROR: dependencies ‘scuttle’, ‘microbiomeDataSets’ are not available for package ‘mia’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/mia’
Error: Failed to install 'mia' from GitHub:
  (converted from warning) installation of package ‘/var/folders/7m/550c9p9104v0k6t0yk9y324w0000gn/T//Rtmp6dTISb/file269f78456d06/mia_0.98.40.tar.gz’ had non-zero exit status
```

It does not matter whether Windows, Mac OS on different Computers. This indicates for me that the simple 

```
BiocManager::install("FelixErnst/mia")
```

does not work universally. Any ideas how to resolve this?

**Comment by FelixErnst** [comment]
Hi,

the error message gives it away. `scuttle` and `microbiomeDataSets` are not installed on your system. For a more comprehensive answer, you need to provide the full output of your call to `BiocManager::install` and the ouput of `sessionInfo()`.

In the meantime: to install `scuttle`, try this:
```
BiocManager::install("scuttle")
```

For `microbiomeDataSets` try this:
```
BiocManager::install("microbiome/microbiomeDataSets@release")
```

If you cannot install either packages, then my guess would be that something is wrong with your R and/or Bioconductor version.

**Comment by FelixErnst** [comment]
@carlosmandoz could you solve your problem?

**Comment by carlosmandoz** [comment]
Dear Felix,

thanks for getting back so quickly. I could partially solve it: I could install scuttle. But when I install microbiomeDataSets I get the following error message:

```
Error: object ‘referenceSeq<-’ is not exported by 'namespace:TreeSummarizedExperiment'
Execution halted
ERROR: lazy loading failed for package ‘microbiomeDataSets’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/microbiomeDataSets’
Error: Failed to install 'microbiomeDataSets' from GitHub:
  (converted from warning) installation of package ‘/var/folders/7m/550c9p9104v0k6t0yk9y324w0000gn/T//RtmpBZqzzG/file165cb10cd687b/microbiomeDataSets_0.99.0.tar.gz’ had non-zero exit status
```


I tried to install TreeSummarizedExperiment using Biocmanager and tried again but that did not help. Updated to R 4.0.4 and tried all again, also without success.

**Comment by FelixErnst** [comment]
Thats because you need the development version of `TreeSummarizedExperiment`. You have to upgrade `R-devel` and Bioc 3.13 or install `TreeSummarizedExperiment` from GitHub.

In addition, I would like to remind you to post complete calls and outputs and the your `sessionInfo` next time.

**Comment by carlosmandoz** [comment]
This worked!

**Comment by diedie9** [comment]
Hi, I tried to install mia, but after use if (!requireNamespace("BiocManager", quietly = TRUE))    install.packages("BiocManager") and BiocManager::install("mia") to install.
It gave me Warning messages:
1: In install.packages(...) :
  installation of package ‘DirichletMultinomial’ had non-zero exit status
2: In install.packages(...) :
  installation of package ‘mia’ had non-zero exit status

and when I use library("mia")
it has error.
Error in library("mia") : there is no package called ‘mia’

And I have already tried to install DirichletMultinomial. It returned the same result then install and library again.
Could you help me to solve this issue?

**Comment by TuomasBorman** [comment]
Hi,

it says that it is not possible to install DirichletMultinomial package. However, mia requires that

--> What is the error message when you try to install DirichletMultinomial package? It might be that you are missing some system dependency
