### ISSUE TITLE
Rename calculateDistance

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#77]
The `calculateDistance` is using the various dissimilarity indices that are available through vegan. Some of those are not _distances_, for instance Bray-Curtis is not a distance (it does not satisfy triangle inequality). This is an important difference.

I propose to rename this function as `calculateDissimilarity`.

In addition, it could be mentioned more clearly in the manpage that these same indices are often called beta diversity in (microbial and other) ecology.

**Comment by FelixErnst** [comment]
This function will be removed as well, since the functionality was just there to support `runMDS2`. There is need for it anymore.

**Comment by antagomir** [comment]
Add a .Deprecate note on this function, if this is going to be removed?

**Comment by TuomasBorman** [comment]
So function that will be removed is:

- `calculateDistance`

These functions utilize `calculateDistance`:
- `estimateDivergence`
- `calculateUniFrac`
- `calculateJSD`

I am not sure what was meant to do with these 3 functions

**Comment by antagomir** [comment]
Ok, so it was used for multiple functions. We can either 

1) Keep this available but then I would change the name to maintain conceptual clarity

2) Hide the function (unexport), it could still be utilized by those other functions; but then Deprecation message would be necessary since some users may still have workflows with this.

**Comment by FelixErnst** [comment]
I think `calculateDistance` could be wrapped internally and the deprecation of the exported function done for current devel. It would gone by Bioc 3.15.

The usage in 
- estimateDivergence
- calculateUniFrac
- calculateJSD
can be switched to the internal wrapper now and the deletion after deprecation would be straightforward

**Comment by antagomir** [comment]
Ok to me.

**Comment by FelixErnst** [comment]
Can this be closed?

**Comment by TuomasBorman** [comment]
I think all is done for now, removing the function is the next step

So yes, this can be closed
