### ISSUE TITLE
Rename runCCA

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#78]
The function `runCCA` performs Canonical Correspondence Analysis.

CCA refers also to Canonical Correlation Analysis, which is another widely used technique that is relevant to multi-omics data integration (equivalent of PCA for two data sets). It is very much possible that this will be implemented in mia or related packages in the foreseeable future.

In order to avoid confusion, I would suggest renaming this function to  `runCanonicalCorrespondenceAnalysis` 

In function manpage: "Canonical Correspondance Analysis" -> "Canonical Correspondence Analysis"

**Comment by FelixErnst** [comment]
I think this is something for the future. Currently it is a wrapper for the `cca` function from `vegan` and alos links to it. I don't see a problem there for now. The notion that there might be a clash for me is to preemptive.

Please feel free to open this, when a Canonical Correlation Analysis is to be implemented.
