### ISSUE TITLE
Will it be possible to speed up tests?

### ISSUE THREAD

**Issue by microsud** [microbiome/mia#8]
During `R CMD check`  running `tests` is slow on a system that has 8GB RAM and 13GB virtual memory 
```
   Examples with CPU (user + system) or elapsed time > 5s    
                  user system elapsed     
   calculateJSD 767.19   1.78  799.25    
```
Maybe reducing test data inside tests can speed up the calculations or the calculations itself can be made faster?

**Comment by FelixErnst** [comment]
Hi Sudarshan @microsud 

on three of the machines I have access to this takes about 5-10sec on a single core. Therefore, I am quite sure, that the times given above are exaggerated at best.

However, I am not saying performance cannot be improved, but with such a low run time to start with, it is probably not a high priority and worth our time at this moment.

If you can provide additional benchmarks proving your point, we of course continue investigating.

Felix

edit: 

On a single core of a Xeon 6136 3.0-3.7 Ghz 
```
> microbenchmark::microbenchmark(calculateJSD(enterotype), times = 10)
Unit: seconds
                     expr     min       lq     mean   median       uq      max
 calculateJSD(enterotype) 2.65809 2.683333 2.790472 2.770039 2.817343 3.141899
 neval
    10
```

Funny thing is that `bench::mark` does not complete a single run in 5 min. So I couldn't report memory consumption, but nothing obvious sticking out, so I think memory is not the issue.

**Comment by microsud** [comment]
It seems an issue with my system. Time for clean up :expressionless:
will close the issue.

**Comment by FelixErnst** [comment]
Hi Sudarshan @microsud ,

did you by any chance test this on R 4.0.3? I just did upgrade one machine and this is taking now a bit longer. Thanks for feedback.

Felix

**Comment by microsud** [comment]
Yes I am working with R 4.0.3

**Comment by FelixErnst** [comment]
Yeah somehow there was a speed bump, which actually make me come up with serious improvement in the whole thing. Fix is on its way
