### ISSUE TITLE
Potentially confusing colData augmentation

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#80]
Just noticed that the `estimateDiversity` and other related functions are directly adding new columns to colData, even if the colData already has elements with the identical names. 

Not knowing this, it took a while to realize that one error message that I got was related to this. Potentially confusing and error prone.

We could either overwrite the past values that had the same name, or provide warning or error if new elements with identical names are being added to colData. 

Any comments / recommendations, how does this compare to other standard practices with `SE` objects?

```
library(mia)
data(esophagus)
tse <- esophagus

esophagus <- estimateDiversity(esophagus)
cd <- colData(esophagus)
print(colnames(cd))

print("---------")

esophagus <- estimateDiversity(esophagus)
cd <- colData(esophagus)
print(colnames(cd))


```

**Comment by FelixErnst** [comment]
I don't see the problem. The user can always choose a different name for the values to be added to and if he/she/they uses the default values and in the special users context they don't apply, it is not our fault.

For example: If the user save values to the `colData` named `shannon` and runs `estimateDiversity` and expect the original value to be present, he ran `estimateDiversity` without reading the man page. One could argue a warning might be in order, but its still a layer 8 problem.

`runMDS` and all other functions I know of, like `addPerCellQC`, behave the same way.

> Not knowing this, it took a while to realize that one error message that I got was related to this. Potentially confusing and error prone.

I would like to see the context of this error message.

edit: `addPerCellQC` just does `cbind`, which in the context of a `DataFrame`, leads to a very specific behaviour (The colnames do not need to be unique and extracting the second values gets weird)

**Comment by antagomir** [comment]
The error message I mentioned came when I tried to pick a field by its name, and got unexpected values. Then, investigating this I noticed that the colData had several columns with the same name and picking a field by its name returned one that had the same name but different contents. 

If the general idea is to help users by implementing the functionality so that unexpected errors do not happen easily by mistake, it would make sense to generate a warning at least.

**Comment by FelixErnst** [comment]
Then it would be good to add this check into `.add_values_to_colData`. That way you catch it for all functions. See comments in #79

**Comment by antagomir** [comment]
Yes, it came up while digging that one. I can add this in that PR.

**Comment by antagomir** [comment]
I am now adding a warning in the other PR. However, continuing discussion in this issue because I would like to ask if it is completely out of question to add an argument that would allow the user to override the previous values..

Like: `tse <- estimateDiversity(tse, replace = TRUE)`

**Comment by FelixErnst** [comment]
The values need to be overwritten always. The user has the option to use another name.

However, if the name already exits, a warning is issued. Thats it.

edit: The rational behind it is as follows:
- the user has the option to choose a name he likes or thinks is best
- this is implemented in a single option
- If the user messes up, we let him know

**Comment by antagomir** [comment]
Just checking - if the name already exists, and a warning is issued + new field with the identical name added, then the values will not become overwritten. What does it then mean in this context that the values need to be overwritten always?

**Comment by FelixErnst** [comment]
No. the values gets replaced. I mean you can spell the problem out in the warning, if you want to but it comes down to `read the manual`

**Comment by FelixErnst** [comment]
> What does it then mean in this context that the values need to be overwritten always?

That the current behaviour is correct. The value will be replace. The only addition is, that the user gets warned about it.

**Comment by antagomir** [comment]
The previous values are not replaced. A new field is added instead. 

With "value is replaced" I get that the values in the previously created field would get overwritten. This does not happen in the present implementation. Do you mean that it does happen now, or that we should change the implementation so that it would happen this way in the future version?

Do we understand the terms in a different way, or do we have a different take on of how the function behaves currently?

**Comment by FelixErnst** [comment]
I messed up. It should be replaced ... arg... Thats was on piece of paper ToDo List.. I will have a look at the PR and think about it.

**Comment by antagomir** [comment]
Ok great! :-) I was confused for a reason.
