### ISSUE TITLE
Add Faith's phylogenetic alpha diversity

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#81]
Add implementation of Faith's phylogenetic alpha diversity in `estimateDiversity`. 

This is tree-based alpha diversity measure and would nicely complement the other (non-tree) based ones.

The `picante::pd()` provides one implementation (GPL2). It would add a dependency here, or we could add our own implementation to reduce dependencies. This measure is not overly complex.

**Comment by FelixErnst** [comment]
For this to be implemented, first it has to be decided, whether you want to reuse the `estimateDiversity` function name. If yes, three things need to be adjusted:

1. the generic has to be expanded with a `tree` arguments, which is then `missing` for all functions currently implemented.
2. a method has to be added for a signature `c(x="SummarizedExperiment",tree="phylo")`, which splits the workflow on the currently implemented methods and the ones, which depend on the tree aka. the new faith index.
3. a method has to be added for a signature `c(x="TreeSummarizedExperiment",tree="missing")` extracting the `rowTree` and dispatching to the method in 2.

If you want to use a special function name unrelated to the current ones, only 2. and 3. have to be implemented.

**Comment by antagomir** [comment]
In my opinion it would be good to have also 1. implemented. The alpha diversity are all conceptually similar, Faith is just able to take into account some additional information not used by the other indices.
