### ISSUE TITLE
Loading Mothur data

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#88]
We seem to miss Mothur importer, this could be added similar to [mia::loadFromQIIME2](https://github.com/microbiome/mia/blob/master/R/loadFromQIIME2.R).

We have one in [microbiome::read_mothur2phyloseq](https://github.com/microbiome/microbiome/blob/master/R/read_mothur2phyloseq.R) and this might help to get it started.

**Comment by FelixErnst** [comment]
This seems reasonable. Can you implement it?

**Comment by antagomir** [comment]
Me or @tvborm
