### ISSUE TITLE
Add new method to transformCounts for returning ranks of abundances

### ISSUE THREAD

**Issue by antagomir** [microbiome/mia#94]
Rank index is needed in certain non-parametric operations. I suggest to add this as one transformation. 

Abundances would be transformed as: `x <- order(x)`

Related to #93

**Comment by FelixErnst** [comment]
The concept is not clear to me.

In addition the command `x <- order(x)` is ambiguous for any two dimensional object and I also would like point out two things problematic with concept as laidout above:
1. `order` returns an ordering integer vector. Overwriting `x` with it probably does not make sense. Did you mean `sort`?
2. Ordering of `SE` object is already available via `se[new_order_row,new_order_col]`. This makes it very versatile, because the user can create an enormous amount of different orders using data from `rowData` or `colData`. There is no wrapping function needed.

I think this is a case of "use/teach base R behaviour" to avoid any unneccessary sugar.

**Comment by antagomir** [comment]
Rank tests are a routine workhorse for non-parametric tests and having the ability to add such assay easily through a transformation would be useful. Because such transformation needs to be done for certain tests or visualizations.

The `x <- order(x)` was a brief example on how to do this per row or per column. In practice a sweep will be needed. Order returns the rank for each entry. I did mean the rank order and not sort.

The idea is not to reorder rows or columns but transform the abundances to their corresponding ranks per sample (or per taxa).

**Comment by FelixErnst** [comment]
So the idea would be more like function named `getRankOfAbundance`?

**Comment by FelixErnst** [comment]
or more like `transformCounts(..., method = "rank")`?

**Comment by antagomir** [comment]
The latter, yes.

**Comment by antagomir** [comment]
I got to test this now. The `.calc_rank` function internally uses the `ties.method` argument (of colRanks function). This has been set to `ties.method="min"`. This is not the default in colRanks, and the user is not given an option to change this. 

I propose the following changes:
- default should be ties.method="first"
- user should have access to this argument through `transformCounts` (`"..."` option)
- example could be added, including an example on how to change the ties.method in `transformCounts`
- unit tests should be modified to match this

**Comment by FelixErnst** [comment]
I am of two minds on this

1. This method implements a specific fixed rank calculation.
2. If it is just a wrapper of colRanks, maybe we should skip implementing the wrapper and just use `assay(se,"whatever") <- colRanks(assay(se, "whichever"))`

So from that point of view, I thought this was a specific use case, which warrants fixing the `ties.method` argument. If that is not the case, removing the whole function again would make sense

**Comment by antagomir** [comment]
Right. No strong opinion as long as the use case is shown for instance in OMA.

We can have (1) by providing the well-thought default value, even if we allow other choices through `ties.method`. 

But it is also true that the other transformations do not have such flexibility.

I could do with either option. For now, I would propose keeping (1) and changing the default to `ties.method="first"` (unless we like to allow other choices). When we accumulate more experience, this can be either kept or removed.

**Comment by antagomir** [comment]
The point (2) does  not seem to work out of the box

```
data("esophagus")
x <- esophagus
assay(x, "rank_average") <- colRanks(assay(x, "counts"), ties.method="average")
```

**Comment by FelixErnst** [comment]
How about 
```r
assay(x, "rank_average", withDimnames = FALSE) <- t(colRanks(assay(x, "counts"), ties.method="average"))
```
?

edit:

Alternative, which should be faster
```r
assay(x, "rank_average", withDimnames = FALSE) <- colRanks(assay(x, "counts"), ties.method="average", preserveShape = TRUE) 
```

**Comment by antagomir** [comment]
Yes that's ok. I added an example.
